### ISSUE TITLE
How to design pagination? 

### ISSUE THREAD

**Issue by mattwells424** [salesforce/design-system-react#1041]
How should pagination be designed for use with the data table. Below is a sample of a simple (back, next) button pagination design. I have also heard something about a continues scroll. Which or are either of these the correct UX for implementing this?

<img width="765" alt="screen shot 2017-08-07 at 12 48 50 pm" src="https://user-images.githubusercontent.com/5672803/29036798-ec73c610-7b6e-11e7-8697-ee026b2d0aed.png">

**Comment by interactivellama** [comment]
We are going with data tables should not be paginated as the UX patttern standard. Closing.
