### ISSUE TITLE
Support webpack bundling of icons

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1044]
I'm not promoting this usage, but it's an option some might like if they would not like all the icons bundled in, but want some bundled in. Something like: https://www.npmjs.com/package/react-svg-loader that would parse the JS and see what's being used.

It would not work when the data determines the icons though. For example:
```
const accounts = [
    { id: '1', label: 'Acme', subTitle: 'Account • San Francisco', type: 'account' },
    { id: '2', label: 'Salesforce.com, Inc.', subTitle: 'Account • San Francisco', type: 'account' },
    { id: '8', label: 'Acme Construction', subTitle: 'Account • Grand Marais, MN', type: 'account' }
];

const accountsWithIcon = accounts.map((elem) => Object.assign(elem, {
    icon: <Icon
        assistiveText="Account"
        category="standard"
        name={elem.type}
    /> })
);
```

The current path of this library is all icons (set a NODE ENV during build for a 730KB JS file, see how the bundle works) or none (use external paths/ host your own icons). If someone would like to set this up, so that you can selectively bundle icons with DSR, please create a pull request and base the work on top of #959.

**Comment by interactivellama** [comment]
Closing unless someone is interested in this feature.

**Comment by jschlichtholz** [comment]
Hi, just want to make sure I got this issue right: there is no easy way I can use bundled icons (like in 0.6.x) when using 0.7.x?

**Comment by interactivellama** [comment]
You can use the bundle of everything `design-system-react.js` which has the icons or you (run your own build)[https://github.com/salesforce/design-system-react/blob/master/scripts/dist.sh#L24] of the library with a node env set to include the icons.

The icon inclusion was nice to have when the icon library was small. The icons have grown to 400KB and I don't think folks use all of them on initial load, I would highly recommend not including all those icons in your Javascript file for the sake of your user and plan to serve them like you do with other images.

**Comment by jschlichtholz** [comment]
Thanks! We are currently figuring out a nice way to do exactly this. We were not able to use the full bundle with webpack. Just thought there might be a simple solution to use in the meantime.
