### ISSUE TITLE
Inline Picklist menu with a scrollbar becomes blank on mouseover [Windows][IE11]

### ISSUE THREAD

**Issue by minevskiy** [salesforce/design-system-react#1051]
Environment: Windows 8.1, IE11 (not reproducible in Windows 7)

Repro steps:
1. Go to Popover playground: https://react.lightningdesignsystem.com/components/popovers/
2. Add a Picklist with isInline={true} with 6 or more items to a popover content
* you want an inline picklist with a vertical scrollbar in the menu - see an example below
3. Open the popover, open the picklistm mouse over an item
4. Observe that menu content is shifted. It appears that its original offsets are doubled. 

```
<Picklist
	className="slds-m-bottom--large"
	label="Lead Source"
	onSelect={(option) => { console.log('selected: ', option.label); }}
	options={[
			{ label: 'Third Party Program', value: 'A0' },
			{ label: 'Cold Call', value: 'B0' },
			{ label: 'LinkedIn', value: 'C0' },
			{ label: 'Direct Mail', value: 'D0' },
			{ label: 'Third Party Program', value: 'A01' },
			{ label: 'Cold Call', value: 'B01' },
			{ label: 'LinkedIn', value: 'C01' },
			{ label: 'Direct Mail', value: 'D01' },
			{ label: 'Other', value: 'E0' }
	]}
	placeholder="Select Lead Source"
	value="B0"
	isInline={true}
/>
```

<img width="284" alt="win8-ie11-menu-picklist" src="https://user-images.githubusercontent.com/14121307/29391568-0cf75042-82ad-11e7-8729-6f0dadaa0e81.png">

This also affects Filter component:
<img width="408" alt="win8-ie11-popover" src="https://user-images.githubusercontent.com/14121307/29391569-0cf768b6-82ad-11e7-97dc-dcf577a43c12.png">

**Comment by interactivellama** [comment]
Closing. Feel free to re-open for combobox.

**Comment by hikkitada** [comment]
@interactivellama, could you please let me know which release version contains the fix of the issue? Thanks!

**Comment by interactivellama** [comment]
Combobox was added in v0.6.23. Picklist has been deprecated.

**Comment by hikkitada** [comment]
@interactivellama , I went to the combo playground with Windows 8 IE 11: https://react.lightningdesignsystem.com/components/comboboxes/
None of the combo boxes shows :( (see screenshot)
I will reopen this bug for that.

![screen shot 2017-11-28 at 11 50 14](https://user-images.githubusercontent.com/613273/33340966-5357b6cc-d432-11e7-8467-040bb05343b2.png)

**Comment by interactivellama** [comment]
IE11 doesn't have `object.assign` if you look in the console for those examples. You may want to bundle an `assign` polyfill if you support IE11. I'm looking into the scroll issue in Edge.
