### ISSUE TITLE
Notification component throws uncaught type error when toggling isOpen state

### ISSUE THREAD

**Issue by jjangsfdc** [salesforce/design-system-react#1057]
You can see the exception in console when opening/closing the notification examples - https://react.lightningdesignsystem.com/components/notifications/

We(Platform Integration Tools Team) currently have code where
 
```
fetch(someEndpoint, {method: 'POST'})
.then(function(response) {
   if(response.status == 200) {
     .. do stuff and set Notification state to isOpen with success  **// Exception is thrown when isOpen=true and it goes to catch clause!**
   }
.catch((error) => {
   set Notification state to be isOpen with error
}
```
 
So we always see error notification even in happy path. I can work around by changing the code to not catch the exception right now, but the root problem is caused from the Notification component.

**Comment by interactivellama** [comment]
I'm
