### ISSUE TITLE
Update Toast Examples

### ISSUE THREAD

**Issue by kwilloughby** [salesforce/design-system-react#1072]
The items below need to be fixed on the Notifications page (https://react.lightningdesignsystem.com/components/notifications/). 

Note: the colors in the latest version of SLDS have changed a little (e.g. Base was blue now gray).

General:
- The section name should be changed to "Alerts & Toasts" or something similar. A "Notification" in SLDS is a totally different component.
- Currently the Toast text color is being overwritten by .site [class*=slds-text-heading]. It should be white in all instances except for the warning.

Alerts & Toasts:
- The icons should align with those used on the SLDS website (https://www.lightningdesignsystem.com/components/alert and https://www.lightningdesignsystem.com/components/toast). For example, the Toast Success bell on the React website should be a checkmark.

Toasts:
- Toasts should be stacked as specified on the SLDS website (https://www.lightningdesignsystem.com/guidelines/messaging/components/toasts). If we aren't going to stack them on the React website it might be better to replace or hide any other visible Toasts. My concern is people might assume it's okay to cover a Toast up with another Toast. Doing the same for Alerts might also be a good idea.
- We should remove the "Open modal with notification" example. For errors, people should use a popover (https://www.lightningdesignsystem.com/guidelines/messaging/components/popovers).

**Comment by interactivellama** [comment]
* "Open modal with notification" example has been removed from examples. Will be fixed in next release
* `.site [class*=slds-text-heading]` ovverride is fixed.

Closing issue and moving test of issues to #1153 and #1154
