### ISSUE TITLE
Removing/deselecting selection in Picklist with multiselect

### ISSUE THREAD

**Issue by jjangsfdc** [salesforce/design-system-react#1083]
Two issues:
1) What is the expected behavior if you click on the checked cell in Picklist with multiselect. Will it toggle to not checked or still checked? Right now, cell is still checked but once you close the dropdown, the associated pill is removed and if you open the dropdown again that cell is now not checked.

2) Before multiselect feature,  user can only select one cell and you can always find out what is the changed cell from onSelect handler. However with current implementation of multiselect, there is no way to find out which cell is deselected when associated pill is X'ed. There needs to be a handler for this remove action. In related to the first question, I am not sure if you should be able to deselect a cell from the drop down in when multiselect=true. If this should be possible then there needs to be another handler or reuse the same handler as the pill.

I am working on a story(W-4070483) that requires multiselect picklist and I can work on the two fixes above if you guys also feel that they are needed.

@interactivellama @donnieberg

**Comment by interactivellama** [comment]
Feel free to re-open and fix, but it sounds like we've got Combobox working in our last meeting. Would it add clarity to remove the multiple prop from the docs of picklist.
