### ISSUE TITLE
Multiselect picklist remove pill is broken after #1045 PR

### ISSUE THREAD

**Issue by jjangsfdc** [salesforce/design-system-react#1094]
It looks like when multiselect=true picklist, pill remove is broken after #1045 PR.

I will fix it.

**Comment by interactivellama** [comment]
@jjangsfdc Feel free to re-open and fix, but it sounds like we've got Combobox working in our last meeting.

**Comment by jjangsfdc** [comment]
@interactivellama I already fixed it here - https://github.com/salesforce/design-system-react/commit/33bcbdf07f039637368e7b204133aa01ad6d6b0d
