### ISSUE TITLE
Should have visual regression testing

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1099]
All changes should be visual regression tested to ensure quality. It should be automated, and should run as part of the current PR testing process.

The framework was added in #1241. Examples just need to be added and tested. This should probably be broken up into multiple issues and most used components prioritized.

**Comment by interactivellama** [comment]
This should probably be broken up.

**Comment by interactivellama** [comment]
We should start with these when we work on this issue:
* [] Combobox / Lookups / Picklist
* [] Data Tables
* [] Icons
* [] Input
* [] Menus
* [] Page Headers
* [] Tooltips
* [] Trees

**Comment by futuremint** [comment]
Theoretically: if we have the ability to automatically validate that our markup matches what is specified in SLDS, do we need visual regression testing?  I ask because visual regression testing is slow, fragile, and complicated... and to keep a high quality developer experience in my opinion we should avoid it unless we absolutely need it.

**Comment by interactivellama** [comment]
The most recent backstory on this is with that stories were manually checked with the CSS `--` to `_` BEM modifier change and `VerticalNav` broke and VRT would have blocked me from releasing that broke.

One option (which is similar to what SLDS does and is close to how a 3rd party VRT would work) is that the code review person would generate the snapshot image before code commits and after code commits and do a compare to better enable their code review. 

Large codebase changes and side effects (one component changes another) are the primary issues we are trying to highlight here.

**Comment by interactivellama** [comment]
Closing with #1987 merged in and #2098 highlighting which components are missing from tests
