### ISSUE TITLE
Add ability to hide "Enabled"/"Disabled" text on toggle checkbox

### ISSUE THREAD

**Issue by jimmydief** [salesforce/design-system-react#1138]
The text is unnecessary in some cases and hiding it through CSS requires beating the specificity of SLDS styles or using `!important`, neither of which are great solutions. Unless the text is needed for accessibility (doesn't seem to be the case for screen readers), I think that it should be hideable through code.

**Comment by futuremint** [comment]
@jimmydief thanks for your input!  We welcome pull requests and we have a [clear and detailed](https://github.com/salesforce/design-system-react/blob/master/CONTRIBUTING.md) contribution guide. Want to try sending us a PR for your idea?

**Comment by lexishanson** [comment]
@jimmydief Did you start on this? If not I will take it on.

**Comment by interactivellama** [comment]
@lexishanson Double check with accessibility team, please, before you start. There may be concerns outside of screenreaders.

**Comment by lexishanson** [comment]
@jimmydief we ran this by the accessibility team and they are hesitant to allow for no visible label on the toggle checkbox without a visible cue to indicate to a user what they enabling/disabling. This could be good feedback to take to SLDS and they can consider a specific design for this. Closing out for now but let me know if you have other thoughts.

**Comment by jimmydief** [comment]
Thanks @lexishanson, will share that feedback with our designer.
