### ISSUE TITLE
Add package-lock.json to .gitignore

### ISSUE THREAD

**Issue by lexishanson** [salesforce/design-system-react#1144]
I'm on a newer version of NPM (v5), and a `package-lock` file is generated when I run `npm install`. I could revert my NPM version, but given that others might run into this I'd propose we add `package-lock.json` to our `.gitignore`.

Additionally, we could create an `.npmrc`file to prevent `package-lock.json` from getting generated in the first place (see https://codeburst.io/disabling-package-lock-json-6be662f5b97d).

**Comment by interactivellama** [comment]
We can pursue package locks after Tether gets removed. https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

Until then, `.gitignore` is fine.

**Comment by dennismphil** [comment]
Shouldn't we check in the `package-lock.json` always? 

https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md
> This file is intended to be committed into source repositories

**Comment by interactivellama** [comment]
`package-lock.json` has been implemented.
