### ISSUE TITLE
"Getting Started" page references wrong github org

### ISSUE THREAD

**Issue by cordeliadillon** [salesforce/design-system-react#1147]
The "Installation with npm" section on the [Getting Started](https://design-system-react.herokuapp.com/getting-started/) page references `github.com/salesforce-ux/design-system-react`, but should probably reference `github.com/salesforce/design-system-react`.

**Comment by interactivellama** [comment]
Thanks. Updated. https://design-system-react.herokuapp.com/getting-started/
