### ISSUE TITLE
Add headings to all site examples

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1165]
Title headings at the top of examples would be nice on the doc site. We could do this with exports I think.

We could assign a string to the class with the name of the example and then render that in the doc site.

**Comment by pradumangoyal** [comment]
Hi @interactivellama, I am really interested in working on this issue. Can you please provide some more specifications on this issue.

**Comment by interactivellama** [comment]
The doc website is pretty just a shell and all the content comes from the library NPM module itself https://react.lightningdesignsystem.com/components/comboboxes/#examples

Right now, it is confusing since as you can see in the Combobox example. It's just a bunch of comboboxes. How does someone know what the example is--which Comobobox is read-only and which is auto-complete, etc.

The comment at the top of the `site-stories` files should add some more context: https://github.com/salesforce/design-system-react/blob/master/components/combobox/__docs__/site-stories.js#L1

One option would be to use the `displayName` of the component another would be to add another class property that is more explicit `exampleClass.docSiteExampleHeading="Read-only single select Combobox"` ?

If you don't want to do all examples, you can start with components that have many examples like `Combobox` and `DataTable`.

The website is not open source right now, but I can share the JSX page that renders the CodeMirror examples if you are interested in this thread. 

I can pull down and test the doc site locally in the code review process.

**Comment by interactivellama** [comment]
Here are the two files that render the examples
parent: https://gist.github.com/interactivellama/23a40d0352c7e4b5ac6763aa891dd435
child: https://gist.github.com/interactivellama/264351d5ffc4ae7355d87d6ed3e71dea

The heading would go somewhere around here: https://gist.github.com/interactivellama/264351d5ffc4ae7355d87d6ed3e71dea#file-component-examples-jsx-L86

**Comment by pulkonet** [comment]
@interactivellama I wanted to discuss this further:

If I am right, this LOC maps the nodes from `site-stories.jsx` present in each component's `__docs__` folder.

```
{Snippets[snippetFile].map((node, index) => (
	<CodeMirror key={component + index} codeText={node} />
))}
			
```
So currently, the node is a module being exported from the `__examples__` folder. I skimmed through the code and felt that it would be difficult to add something like `exampleClass.docSiteExampleHeading="Read-only single select Combobox"` as it is difficult to harvest the prop out of the particular example.

What I am proposing here is, changing the `siteStories` array shape. It is currently a module, but it can be converted to an object with the module and its name as keys. Something like:

```
const siteStories = [
	{ module: require('raw-loader!@salesforce/design-system-react/components/combobox/__examples__/base.jsx'),
          title: 'Base' }
];
```

This way we will be able to use the title right away in the example.

What are your suggestions ?

**Comment by interactivellama** [comment]
I think that is thoughtful solution and probably less likely for someone to forget than a display name or class property, especially if all the other objects in the array have a title in them. I like it.

**Comment by pulkonet** [comment]
I can change the `site-stories.jsx` file in `Combobox` but changes need to be made in the doc site renderer files also. How are we going to do that?
