### ISSUE TITLE
Combobox Read Only variant: Add disabled property

### ISSUE THREAD

**Issue by jschlichtholz** [salesforce/design-system-react#1169]
Add a boolean disabled property to the combobox setting the HTML disabled attribute on the input tag.

@interactivellama Added
Add `readOnlySingleInputDisabled` prop to allow disabling input when in read-only single input variant.

**Comment by interactivellama** [comment]
The current plan is to allow this on read-only aka "Picklist" with `readOnlySingleInputDisabled`
