### ISSUE TITLE
Inline Combobox does not resize properly and looks poorly on multiple lines 

### ISSUE THREAD

**Issue by nhazar** [salesforce/design-system-react#1170]
<img width="1060" alt="screen shot 2017-11-09 at 11 15 04 am" src="https://user-images.githubusercontent.com/1245611/32624829-4b1527a8-c53f-11e7-951c-323beefd222f.png">
<img width="1062" alt="screen shot 2017-11-09 at 11 15 16 am" src="https://user-images.githubusercontent.com/1245611/32624832-4c821bbe-c53f-11e7-96b7-eeae450abb4c.png">

**Comment by interactivellama** [comment]
Thanks, I agree. I think that's an issue with the CSS though. You might want to file an issue with the [Design System](https://github.com/salesforce-ux/design-system/issues) and PR'd a fix over there. This library tries to limit the non-SLDS CSS we use. Once the CSS is present, I'll re-open. I'm going to close this unless you find that it's a JavaScript issue or the wrong markup from [Combobox](https://latest-212.lightningdesignsystem.com/components/combobox).
