### ISSUE TITLE
Allow a more generic dropdown component

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1171]
Design like the UI cleanness of putting complicated UIs in dropdowns

One of our consumer developers would like a generic dropdown container. It could probably piggyback with the current dropdown, but will need more controls. `onSelect` would be defined by consumer. `onClickOutside` could be halted, etc.

**Comment by tanhengyeow** [comment]
Started work on prototyping this :)

**Comment by interactivellama** [comment]
The Dialog Combobox https://design-system-react-co-pr-1735.herokuapp.com/?selectedKind=SLDSCombobox&selectedStory=Dialog&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel might be good enough for this feature (Dialog Combobox as just added to the Design System in the last few months). Have you gotten very far in exploring this? @tanhengyeow

**Comment by tanhengyeow** [comment]
@interactivellama Not too much, have been dealing with other `menu-dropdown` issues to get more inspiration on an ideal generic dropdown component. Great that you clarified early! 😄
