### ISSUE TITLE
Provide guidance on React 16 compat

### ISSUE THREAD

**Issue by avisser** [salesforce/design-system-react#1174]
Currently the library requires consumers to run `"react": ">=15.4.1 <16"`.

Can you provide some guidance in the readme on whether that is going to stay or is planned on changing in the next 3/6/12 months? You can even safe-harbor the crap out of any guidance given.

**Comment by interactivellama** [comment]
Are you asking about React 16 in compatibility mode? The components have not been tested with React 16. I know that some of the "dev libraries" and unit tests are not compatible with React 16 at this point. They still create console warnings in v15.5.

I'd like to see everything be compatible with v16. There is not a roadmap yet. Any confirmation or list of libraries that need to be upgraded would be helpful. This is a truly open source library (externally and internally). I'm open to removing the `<16`, but that makes 16 the default and it currently crashes the contributor dev environment. We might be able to add the React <16 part to the `devDependencies` or fork to a branch for a while, but I'm not sure I feel confident leading folks on that everything works in v16 until the dev environment and unit tests prove it. 

I'd accept any pull requests that were compatible with v15.5 if that helps in getting us closer to 16 compatibility.

**Comment by avisser** [comment]
I work for an ISV that writes software that runs on top of Salesforce. We're looking to move to React-based UIs for some of our stuff.

I'm pretty new to React. I was trying to figure out pros & cons of ES6-style components vs `createReactClass`. But upon further digging, it seems that I can move forward w/ ES6-style (aka the future) regardless of v15 or v16.

So it probably matters a lot less than I initially thought, but would be nice to know if we find ourselves wanting/needing some v16 features.

**Comment by interactivellama** [comment]
Didn't used to be this way, but now [non-extended ES6 classes are preferred](https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#react-create-class), mostly because that's the "expected" React way in all the official docs and such.

I'm going to close, feel free to re-open if you want to contribute to making it more v16 compatible. Just finding all the bugs and putting them in a list would be helpful.
