### ISSUE TITLE
Split View component

### ISSUE THREAD

**Issue by kevinlambert** [salesforce/design-system-react#1190]
We're needing the Split view component for Advertising Studio.

https://lightningdesignsystem.com/components/split-view

Will contribute back once done.

**Comment by interactivellama** [comment]
It looks like a PageHeader on top of a Menu. I'd like to see something like PageHeader (maybe even re-used as `pageHeader={PageHeader}` paired with an `options` prop. Combobox is the newest menu component. I'd recommend following Combobox's patterns for active menu items and a11y, etc. I'm not sure on the column heading though. Maybe steal some prop names from DataTable's `column` like `sortDirection`. It doesn't look like you can click to sort though.

I'd love your feedback though, once you get into it.

**Comment by interactivellama** [comment]
Feedback from SLDS team is that it the listbox can be sortable in theory, but it didn't get implemented, so you are welcome to choose what you want to do based on your needs.

**Comment by kevinlambert** [comment]
Cool. Will have a look at those and see what I can re-use.

**Comment by kevinlambert** [comment]
@interactivellama This is what I've come up with so for the structure. What do you think?


```javascript
const CustomSplitViewListItem = ({ children, ...props }) => (
	<SplitViewListItem {...props} >
		<Icon name={children.iconName} /><span>{children.name}</span>
	</SplitViewListItem>
);
CustomSplitViewListItem.displayName = SplitViewListItem.displayName;
```

```HTML
<SplitView>
	<SplitViewMaster
		isOpen={true}
	>
		/**
		 Where <SplitViewHeader ...> is a HOC of
		 <PageHeader className={'slds-split-view__header'} ...props />
		*/
		<SplitViewHeader
			contentRight={contentRight}
			iconAssistiveText="User"
			iconCategory="standard"
			iconName="lead"
			info="10 items • sorted by name"
			label="Leads"
			navRight={navRight}
			title={<h1></h1>}
			truncate
			variant="objectHome"
		/>

		/**
		 SplitViewList could be a HOC of DataTable 
                 and SplitViewListItem a HOC of DataTableColumn.
		 Essentially the list is a single column table.
		*/
		<SplitViewList
			title={'LEAD SCORE'}
			onSort={ () => {} }
			items={ [] }
			selection={ {} }
			onChange={ () => {} }
		>

			<SplitViewListItem
				primaryProperty={'id'} // Required
				isUnReadProperty={'isUnRead'}
				topLeftTextProperty={'name'}
				topRightTextProperty={'leads'}
				bottomLeftTextProperty={'company'}
				bottomRightTextProperty={'status'}
			/>
			// OR
			<CustomSplitViewListItem />

		</SplitViewList>

	</SplitViewMaster>

	<SplitViewDetail>

		<h1>My detail view</h1>
		<div>{selectedItem.name}</div>

	</SplitViewDetail>

</SplitView>
```

**Comment by interactivellama** [comment]
There should be a default render that will be something like the following. You can just do the default if you only need the default, or do a default to achieve the example in SLDS and make a `menuItem` prop to override it.


```
const CustomListItem = (props) => (<span>
	{props.option.label}
	{props.option.secondaryColumns.map((item) => {
		// make the odds right aligned
		// make the events left aligned
	})}
</span>);
```

This is primarily a fancy menu.
```
<SplitView
	assistiveText={{}}
	isOpen={true}
	header={<SplitViewHeader
		contentRight={contentRight}
		icon={<Icon name="lead" category="standard" assistiveText="User" />}
		info="10 items • sorted by name"
		label="Leads"
		navRight={navRight}
		title={<h1></h1>}
		truncate
		variant="objectHome"  //Add object home
	/>}
	labels={{
		columnHeader: 'Lead Score'
	}}
	listItem={CustomListItem}
	onSort={ () => {} }
	options={[ 
		{ label: 'Riley Schultz'
			secondaryColumns: [item.leadScore, item.company, item.status]
		}
	]}
	items={ [] }
	selection={ [] }
	onSelect={ () => {} }
	unread={ [] }
/>
```

I was considering something like this
```
<SplitView>
	{options.map((item) => {
		// children are an array of `ListItem` components
		<SplitViewListItem
			label={{item.label}} // Required
			secondaryColumns={[{label, ...item}]}
		/>
	})}
</SplitView>

```
But that would mean using `children` to find the active item, which I not sure that is a good idea. See Combobox activeItem state [here](https://github.com/salesforce/design-system-react/blob/master/components/combobox/combobox.jsx#L216) or [here](https://github.com/salesforce/design-system-react/blob/master/components/combobox/combobox.jsx#L417) to get an idea of how to use an internal index to pass focus. All our menu-like listbox components use an `options` array, so I'd like to stick to that somehow. Also, JSX children look very HTML-like which is great for layout, but you have to parse types of components from an array of components to find out which is needed if we used them for data. It also assumes that the layout isn't going to change. For example, the header may become a footer, so we try to be data focused in our API.
