### ISSUE TITLE
Datepicker years limited to +/- 5 years

### ISSUE THREAD

**Issue by andyengle** [salesforce/design-system-react#1191]
Currently, the datepicker component is limited to +/- 5 years, which might constrain some dates users may wish to select.  A better option might be to provide an input field where the user may enter a year, or have something similar to an infinite-scroll option for year selection which would go beyond 5 years.

**Comment by interactivellama** [comment]
`relativeYearFrom` and `relativeYearTo` should work. Any suggestions to the Datepicker pattern should be submitted to https://github.com/salesforce-ux/design-system . Please re-open those props do not meet your needs.
