### ISSUE TITLE
Missing title attribute from tree branches/items

### ISSUE THREAD

**Issue by danjersoft** [salesforce/design-system-react#1193]
When implementing the Tree component in a narrow container, the branches and items are properly truncated, but there doesn't seem to be a way to add a way to display the text non-truncated.

After comparing the markup, it looks like the `<span/>`s are missing the `title` attribute that would give us the browser's hover text automatically.

I will have a PR shortly to fix this.

**Comment by interactivellama** [comment]
Great, thanks!
