### ISSUE TITLE
Button component is setting state after being removed from page

### ISSUE THREAD

**Issue by cremedios** [salesforce/design-system-react#1202]
We use a `Button` component that dismisses a modal. As this component lives inside the modal, it will also get removed.

It's clickHandler [code](https://github.com/salesforce/design-system-react/blob/master/components/button/index.jsx#L153)  calls setState on an unmounted component, therefore showing a warning message on the console.

If the code in this handler was to be inverted, the problem would be solved. Something similar to :

handleClick: 
```
this.setState({ active: !this.state.active });
if (this.props.onClick) {
	this.props.onClick(event);
}
```

another option is to invoke `this.props.onClick` in the `setState` callback

**Comment by interactivellama** [comment]
@andyengle This may be the issue you are having with the setState console error.

**Comment by interactivellama** [comment]
@cremedios This is one of the older components. I'm not even sure why we need an active. Could you do some discover and see if it's something we still need?

**Comment by andyengle** [comment]
Ah, good find, @interactivellama .  I'll see I'm using that component.  Thanks for the tip!

**Comment by cremedios** [comment]
will do, I'll get back to you guys tomorrow
