### ISSUE TITLE
implementing dynamic menu dsr

### ISSUE THREAD

**Issue by woshichensida** [salesforce/design-system-react#1206]
Hi, per contributor guide, I am creating an issue to implement dynamic menu dsr. The component slds is [here](https://latest-212.lightningdesignsystem.com/components/dynamic-menu/#content).
As part of our work on previous release, we already implement the over 10 items variation with search box in our repo iot-ui. And we are planning to move the code over and start from there. Let me know what you guys think. Thanks

**Comment by interactivellama** [comment]
I'll try to get you what I'd think the API would like as a DSR component on Monday and we can compare notes. Thanks so much! Looking forward to it.

**Comment by interactivellama** [comment]
This is what I was thinking after 15 minutes:

```
const propTypes = {
    assistiveText: shape({
        popoverLabel: PropTypes.string
    }),
    children: PropTypes.node, // trigger/Button
    classNamePopover: PropTypes.oneOfType([PropTypes.array, PropTypes.object, PropTypes.string]),
    combobox: PropTypes.node, // Combobox component
    hasStaticAlignment: PropTypes.bool,
    isOpen: PropTypes.bool,
    menuItem: PropTypes.func, // SLDS list item shown should be default, but this custom render prop is optional to include
    popoverMenuItem: PropTypes.func, // SLDS list item shown should be default, but this custom render prop is optional to include
    popoverPosition: PropTypes.oneOf(['absolute', 'overflowBoundaryElement', 'relative']),
    popoverOptions: PropTypes.array
};

const Example = () => (
    <DynamicMenu
        combobox={
            <Combobox
                id="combobox-unique-id"
                labels={{
                    placeholder: 'Search Favorite',
                    noOptionsFound: 'You can favorite any page!',
                    noOptionsFoundHeading: 'My Favorites'
                }}
                options={accountsWithIcon} // Combobox will probably need a heading list item added to it, that is removed from the a11y keyboard interactions and events
            />
        }
        popoverOptions={[
            <Button label="Favorite this page" onClick={function () {}} icon={<Icon category="utility" name="add" />} />,
            <Button label="Favorite this page" onClick={function () {}} icon={<Icon category="utility" name="edit" />} />
        ]}
    >
        <Button icon={<Icon category="utility" name="favorite" variant="icon" />} />
    </DynamicMenu>
);
```

I haven't looked at the markup too closely, but seems like a case to reuse a bunch of component API and clone/modify them as they are passed in. If the Combobox options are less than 10, then we will probably need a `hideInput` prop passed to combobox, I think.

**Comment by woshichensida** [comment]
Hi, thanks for the note, here is our note
`const propTypes = {
    containerClassName: PropTypes.oneOfType([PropTypes.array, PropTypes.object, PropTypes.string]),
    menuItems: PropTypes.array, // items shown as selection
    searchInput: PropTypes.string, // input value on the searchbox
    onChangeInput: PropTypes.func, // callback on input change
    onRemoveSelection: PropTypes.func // callback on remove search selection
    searchSelection: PropTypes.object, // current selection on the searchbox
    extraOptions: PropTypes.array,
    noOptionFound: PropTypes.string, // text shown when user search and no option is found
    optionHeader: PropTypes.string // header text displayed on top of all items, if left empty, there will be no header
};

const Example = () => (
    <DynamicMenu
        searchInput="account"
        noOptionFound="you can favourite any page"
        searchSelection={category="utility" name="favorite" variant="icon"}
        optionHeader="My Favourite"
        extraOptions={[
            <Button label="Favorite this page" onClick={function () {}} icon={<Icon category="utility" name="add" />} />,
            <Button label="Favorite this page" onClick={function () {}} icon={<Icon category="utility" name="edit" />} />
        ]}
    />
);`
couple things:

- i am thinking of not implementing it as a popover since popover is already a dsr and ppl can just combine this two together if they want the same as slds, in our use case we donnot use popover, and I suspect this could be use case for a lot of ppl and leaving the flexibility would be easier for ppl to use
-hiding the combobox implementation from the api(it will not show combo box if less than 10 items, if over would show automatically, or expose a variant for different variations)
- have a separate component for list items since combobox list item popover is kinda separated from the searchbox as a separate div, the rendering it is not actually quite the same as one in dynamic menu which rendering kinda in the same div, also have a separate component for list item would make it easier to implement other variations since they also need to display the list item

Let me know what you think, thanks

**Comment by lexishanson** [comment]
@interactivellama @woshichensida 

Stephen and I chatted offline and I wanted to add details here so we're on the same page. Stephen and I talked about adding a separate ```dynamicMenu``` render variant inside of ```Combobox```, where we will modify the mark up for the list items to show up below the input in a list-box, outside of a menu. 

We will also need to add a ```hideInput``` prop to ```Combobox``` to handle the other variants of ```dynamicMenu```.

@interactivellama, @woshichensida is proposing that we just take in the props and handle all the markup for what is ```dynamicMenu``` inside of the added render in ```Combobox```, rather than adding this as an entirely new component in DSR. What do you think about this?
 @woshichensida let us know if you have anything to add here.

**Comment by woshichensida** [comment]
@lexishanson thanks for initiating the thread.
@interactivellama to sum up we are proposing instead of implementing a new component, we add a new variation -- dynamic menu within combobox to render the outcome of dynamic menu in slds(potentially including the buttons at the bottom as well) and also we are considering just automatically hide input box when variation is dynamic menu and item under 10 since the hideinput would only make sense with dynamic menu under 10 items)

so the usage would be something like
`<Combobox variation="dynamicMenu"/>`

let me know what you think, thx

**Comment by interactivellama** [comment]
@woshichensida Yes, that sounds great. You don't need to have the array of `<Button>` that I called `popoverOptions` and you called `extraOptions ` render inside the `Combobox`. The primary reason for using the Combobox is so we can reuse the Listbox navigation and get all the accessibility yumminess of Combobox.

On further thought, `actions` might be a good name for that array of Buttons. They seem like they are actions that the user takes to change the Combobox options.

Are you considering something like this?
```
<Popover>
    <Combobox
        variant="dynamic-menu"
        actions={[<Button label="Add favorite" />
    />
</Popover>
```
I'll have to look at the `DynamicMenu` markup again to see what is inside of the `<div class="slds-combobox" />` and what's not.

**Comment by woshichensida** [comment]
cool,
```
<Combobox
        variant="dynamic-menu"
        actions={[<Button label="Add favorite" />
/>
```

sounds good, we will start implementing it this way. Thanks

**Comment by interactivellama** [comment]
@woshichensida @lexishanson I looked at the SLDS markup today and the actions are in the popover footer. I'm not sure how you could implement this without using a `Popover`, since the actions are in the Popover footer. We can't put the actions within the `Combobox` form element node and we can't return an array of JSX nodes. I will follow up with an email.

**Comment by interactivellama** [comment]
The mostly done submitted code is [here](https://github.com/salesforce/design-system-react/tree/dynamic-menu) if anyone wants to pick this up in the future.
