### ISSUE TITLE
Popover looks wrong when changing position

### ISSUE THREAD

**Issue by george-norris-salesforce** [salesforce/design-system-react#1211]
[![https://gyazo.com/0a3eee7bcdcedec09728142ca74c75ce](https://i.gyazo.com/0a3eee7bcdcedec09728142ca74c75ce.gif)](https://gyazo.com/0a3eee7bcdcedec09728142ca74c75ce)

• When there is room on screen, popover resizes and does not look good (the pointer is located at the top, and does not keep locked at the target button).

Would be nice to have an option to have pointer anchor to one position and not change position, or to have the popover alignment change (always keeping the pointer locked at the target) when there is limited room.

**Comment by interactivellama** [comment]
There is a `hasStaticAlignment` https://design-system-react.herokuapp.com/components/popovers/#prop-hasStaticAlignment option if you'd prefer it to go off the page. Looks like the description isn't making it into the docs though. I'll take a look at the doc parsing.

Flipping the arrow is still a feature that needs to be added if you want to take a crack at it. It would require getting the info from PopperJS that the Popover had flipped and re-rendering.

**Comment by george-norris-salesforce** [comment]
I can take a crack at the arrow flipping.

It appears that `hasStaticAlignment` does not work correctly though..
[![https://gyazo.com/b4738d371e871aa8badbc98bf58c225f](https://i.gyazo.com/b4738d371e871aa8badbc98bf58c225f.gif)](https://gyazo.com/b4738d371e871aa8badbc98bf58c225f)

**Comment by interactivellama** [comment]
@Vintik I've assigned this to @garygong. He will be working on this in the next two weeks.

**Comment by interactivellama** [comment]
@garygong @Vintik worked this into #1404. Apologies for the back and forth! 😞

**Comment by interactivellama** [comment]
Fixes #1211
