### ISSUE TITLE
Links to contributing and resources on Getting Started page are broken

### ISSUE THREAD

**Issue by mkelley33** [salesforce/design-system-react#1212]
See the text starting with "...concepts and Best Practices section of the [Contributing](https://react.lightningdesignsystem.com/contributing)" and "...the tips and tutorials on the [Resources](https://react.lightningdesignsystem.com/resources)." The links go to blank pages.

Opening the developer tools console on Chrome reveals:

`resources:1 The SSL certificate used to load resources from https://react.lightningdesignsystem.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.`

**Comment by interactivellama** [comment]
Looks like it just needs a `/`. The doc site is in a private repo. I'll put it on my todo list. Thanks!

**Comment by interactivellama** [comment]
Fixed.
