### ISSUE TITLE
Lookup throw error on input focus

### ISSUE THREAD

**Issue by NuclleaR** [salesforce/design-system-react#1213]
Dialog component needs position prop and marked as required but in Lookup component this prop is missing. So Dialog doesn't render.

**Comment by interactivellama** [comment]
Fixed by #1214.

@NuclleaR https://github.com/salesforce/design-system-react/releases/tag/v0.8.4 is out with the fix. We now have NPM modules, too https://www.npmjs.com/package/@salesforce/design-system-react
