### ISSUE TITLE
[PROPOSAL] Refactor data components

### ISSUE THREAD

**Issue by aputinski** [salesforce/design-system-react#1217]
I'd like to submit a proposal for making it easier to work with components that accept some sort of "data" prop (`<Combobox />`, `<Dropdown />`, `<Tree />`, etc).

Currently, these components require the data prop to be in a specific shape. For example, `<Combobox />` requires an `options` prop that must be an `Array<Object>` each containing an `id` and `label` property. If your data does not conform this this shape, it makes using the component much more cumbersome.

It'd be great if these types of components accepted props that would be used to extract the necessary properties for each item:

```jsx
const options = Immutable.List.of(Immutable.map({ key: "a", name: "A" }));

<Combobox
  // A function that will receive the option and should return an id
  getId={option => option.get("key")}
  // A function that will receive the option and should return a label
  getLabel={option => option.get("name")}
  // A function that will receive the option and should return a boolean
  // indicating if the option is selected
  isSelected={option => option.get("isSelected")}
  // Anything that can be iterated via Symbol.iterator
  options={options}
/>;
```

With this proposal, `<Combobox />` would no longer care about the data shape / type of `options`. This should be backwards compatible with the current API.

**Comment by interactivellama** [comment]
Do you think we should just have one callback mapper function? With combobox, you've got `subTitle`, too I think? Like an `onGetOption` or `parseOption`? Multiples certainly add clarity to what you can do. One callback, might be more extendable.

I'm generally against having selected state within "the data," but if that's how apps are already rolled, then allowing them to do it in their code is fine.

**Comment by interactivellama** [comment]
`getOption` would align with Tree's `getNodes` and you could even convert a tree of nested objects into an array if you wanted to with a mapping function.

**Comment by aputinski** [comment]
I tried doing something like:

```jsx
<Combobox
  options={options
    .toList()
    .map(o => ({
      id: o.get("key"),
      label: o.get("name")
    }))
    .toArray()}
/>
```

but the problem ended up being that I actually had to save the transformed data into my state so that I could reference it again for `selection`. I'd be open to just refactoring `selection` to be a function which would allow me to use the code above and not really need the `getOption` function.

**Comment by interactivellama** [comment]
Allowing an overwrite of the default find selection function is good. I'm sure many folks have it has a child object key in an array instead of in another array. I figure a filter on an array isn't too costly if there aren't 100s of items.

I'm thinking `getSelection` in order to align with `getNodes`.
