### ISSUE TITLE
SVG icon state possible?

### ISSUE THREAD

**Issue by george-norris-salesforce** [salesforce/design-system-react#1220]
Are there are any, or is it possible to have stateful icons (e.g. based on state). 
e.g.
```
<Icon
  assistiveText="units icon"
  category="utility"
  name={this.state.someState ? 'chevrondown' : 'chevronup'}
  size="x-small"
/>
```

Only the first icon (first loaded) icon shows up. Also tried two Icons elements, and changing disabled style—same result.

**Comment by interactivellama** [comment]
I wonder if this is a side effect of SVGs being in their own iframe like container due to the external file sprite. Are you able to figure if this is SVGs in general or just our library?

**Comment by interactivellama** [comment]
We certainly re-render icons over one another have you tried putting the ternary before icon--to swap the whole icon?

**Comment by interactivellama** [comment]
@george-norris-salesforce Is this still an active issue?

**Comment by interactivellama** [comment]
I'm going to say that it's limitation of the DOME/SVG and that conditionals should be used outside the `<Icon>` tag. If that doesn't work, please reopen.
