### ISSUE TITLE
Previewer iframes 404ing

### ISSUE THREAD

**Issue by george-norris-salesforce** [salesforce/design-system-react#1222]
Hello..

All iframes in the previewer are 404ing: 

GET REQUEST: `GET /__IFRAME__?component=alert&variant=base&title=default&index=0&id=dqVS1avCapJbHxPHIkH_tWBk HTTP/1.1
`

Contributing steps seem out of date: 
https://github.com/salesforce/design-system-react#contributing-to-the-code-base
Are there any steps not mentioned in this doc ^^ that needs to be done to make these examples work?

Opening up `http://localhost:3003/` shows this response :
[![https://gyazo.com/8ed3c516108f4c34ae1b5da999d9976b](https://i.gyazo.com/8ed3c516108f4c34ae1b5da999d9976b.gif)](https://gyazo.com/8ed3c516108f4c34ae1b5da999d9976b)

**Comment by interactivellama** [comment]
Is this meant for https://github.com/salesforce-ux/design-system ?
