### ISSUE TITLE
Navigation: the anchors don't need aria-describedby

### ISSUE THREAD

**Issue by arodenbeck** [salesforce/design-system-react#1235]
The current implementation has an aria-describedby on each anchor. This would cause a screen reader to read additional descriptive text, but I can't understand why this would be necessary.

**Comment by donnieberg** [comment]
This component is following the SLDS HTML spec. I think the reason why the links are `aria-describedby` each section heading is to provide a more explicit grouping to screen readers. If it's ok with you @arodenbeck, I'm going to close this one.

Here's the link to the SLDS markup: https://latest-214.lightningdesignsystem.com/components/vertical-navigation/

**Comment by arodenbeck** [comment]
I agree. I'm not a fan of the extra verbosity this adds, but I can address that with the SLDS team.
