### ISSUE TITLE
Progress Indicators: Needs updates to the assistive-text

### ISSUE THREAD

**Issue by arodenbeck** [salesforce/design-system-react#1238]
This component has similar issues to Tooltips, see #1228. From this examaple, it seems like there is visual indication as to whether a step has been completed. Is there also visual indication as to which step is currently displayed? If so, I would like to see aria-selected added to the current step.

**Comment by interactivellama** [comment]
Create programatic way for complete, disabled, and selected to be recognized by the user. 

* Update of the assistiveText of the step `Button` with accurate state of whether the step is completed and disabled. Add `assistiveText` keys `disabled` and `complete` to enable state completed and disabled steps to be controlled by component.
* For selected state, add `aria-selected=true` to the button.

**Comment by interactivellama** [comment]
@iamnickvolpe Would you be interested in pair programming on this issue sometime in the next two weeks?

**Comment by interactivellama** [comment]
![screen shot 2018-05-07 at 3 25 03 pm](https://user-images.githubusercontent.com/1290832/39726011-e053f4c2-520a-11e8-973b-dc08fbe378b9.png)

![screen shot 2018-05-07 at 3 27 49 pm](https://user-images.githubusercontent.com/1290832/39726126-45b45636-520b-11e8-880f-c71c6a0f7a9f.png)


![screen shot 2018-05-07 at 3 24 31 pm](https://user-images.githubusercontent.com/1290832/39725985-cfd62764-520a-11e8-9fa6-dc6006ec8367.png)

**Comment by arodenbeck** [comment]
The updated aria spec allows for marking something as current. Rather than aria-selected="true", we should use aria-current="step". @kchan902 @interactivellama

**Comment by donnieberg** [comment]
That sounds great @arodenbeck!

**Comment by interactivellama** [comment]
@arodenbeck @donnieberg Should we be filing any of this back onto the SLDS framework?

**Comment by arodenbeck** [comment]
@interactivellama I did ask Simon for his thoughts on using that instead of the assistive text. He thought it was a good idea, but I did not consider asking about getting it into SLDS. I'll ask and report back.

**Comment by kchan902** [comment]
@arodenbeck OK thank you Adam. Sorry for the late reply, I didn't see the @mention
