### ISSUE TITLE
IconSettings only takes one child node

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1239]
Since `return this.props.children` is the [render function](https://github.com/salesforce/design-system-react/blob/master/components/icon-settings/index.jsx#L39) of `IconSettings`, we should tell folks that it only takes a single child on the doc site within the prop types. `props.children` should be added to it anyways.

@kevinparkerson Does this sound like your question?

**Comment by kevinparkerson** [comment]
@interactivellama yeah this is accurate 👍
