### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by zaki-yama** [salesforce/design-system-react#1256]
Hi I just started using design-system-react.
I found a few typos in the document while setting up. Am I correct?

1) In [Getting Started](https://react.lightningdesignsystem.com/getting-started/),

```javascript
onst path = require('path'); // <-- Missing "c" at first
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

...
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loaders: ['babel'],
                include: [
                    path.join(__dirname, 'public/src'),
                    path.join(__dirname, 'node_modules/design-system-react'), // <-- we need `@salesforce` namespace after `node_modules`
                ]
            },
```

2) In [docs/webpack.md](https://github.com/salesforce/design-system-react/blob/master/docs/webpack.md),

2.1) postinstall script is written in JavaScript, but treated as bash script.
2.2) In App.jsx,

```javascript
import IconSettings from 'design-system-react/components/icon-settings';
```

I think we need `@salesforce` namespace here, too.

**Comment by zaki-yama** [comment]
I fixed the docs/webpack.md and set PR in #1257 .
But I couldn't find the document file corresponding to [Getting Started](https://react.lightningdesignsystem.com/getting-started/).

**Comment by interactivellama** [comment]
Thanks, we are transitioning to NPM modules. The git tags don't have a namespace at this time I've been trying to keep the breaking changes to minimum. I do think it's a good idea to promote NPM module use though!

**Comment by interactivellama** [comment]
@zaki-yama It's a private repo at this time unfortunately. I'll make a note to update it.

**Comment by zaki-yama** [comment]
@interactivellama 
Thank you very much for replying and merging!
I'm sorry I didn't fully understand your answer, 

> Thanks, we are transitioning to NPM modules. The git tags don't have a namespace at this time I've been trying to keep the breaking changes to minimum.

Does it mean, Installing via npm ( `npm install` ) is not usual way using design-system-react now?

**Comment by interactivellama** [comment]
This project wasn't open source until last November and it was not published to NPM until two months ago.

**Comment by zaki-yama** [comment]
Oh, I understood. Thank you.
