### ISSUE TITLE
Modal demo is not working correctly

### ISSUE THREAD

**Issue by george-norris-salesforce** [salesforce/design-system-react#1263]
Modal demo is not working correctly
https://react.lightningdesignsystem.com/components/modals/
Testing in Chrome 64
[![https://gyazo.com/af84ab18b9c9277e4b2cd2fe45dd81c5](https://i.gyazo.com/af84ab18b9c9277e4b2cd2fe45dd81c5.gif)](https://gyazo.com/af84ab18b9c9277e4b2cd2fe45dd81c5)

**Comment by interactivellama** [comment]
Yes, a few other teams noticed this morning. The markup is present I'm guessing it's something to do with CSS classes.

**Comment by interactivellama** [comment]
Should have a fix for you by tomorrow.

**Comment by interactivellama** [comment]
@george-norris-salesforce  https://github.com/salesforce/design-system-react/releases/tag/v0.8.7

**Comment by george-norris-salesforce** [comment]
Ok cool! Just wanted to make sure you all knew about it.
