### ISSUE TITLE
Drop down menu on Lookup with menuPosition="overflowBoundaryElement" doesn't align correctly

### ISSUE THREAD

**Issue by davidlygagnon** [salesforce/design-system-react#1267]
When creating a lookup with `menuPosition="overflowBoundaryElement"`, the drop down menu doesn't align to the start of the input (see screenshot).

![screen shot 2018-02-06 at 6 05 44 pm](https://user-images.githubusercontent.com/1821787/35894747-23cd34b8-0b69-11e8-88a4-8d108672d310.png)

I looked at the code and I think there's a bug in the function `getPopperOffsets(popper, referenceOffsets, placement)` on this line: 

`popperOffsets[mainSide] = referenceOffsets[mainSide] + referenceOffsets[measurement] / 2 - popperRect[measurement] / 2;`

If mainSide is "left", we should just be setting `popperOffsets[mainSide] = referenceOffsets[mainSide]`.

I actually don't understand why we would do `+ referenceOffsets[measurement] / 2 - popperRect[measurement] / 2` in that particular case.

Any help?

**Comment by davidlygagnon** [comment]
I just realized that this bug is in a dependency package. I'm still interested in knowing whether you guys have faced this issue before when using the lookup ?

**Comment by interactivellama** [comment]
PopperJS was just added this fall. I believe the `inheritTargetWidth` should be turned on but it doesn't look like it's working. Can you confirm that `inheritTargetWidth` is broken in `≤Dialog/>` utility component?

**Comment by davidlygagnon** [comment]
I think `inheritTargetWidth` is fine. For `Lookup`, it's always set to true and that prop is used to calculate the width of the popper.

 I think the issue is that when alignment is "bottom left", it should really just calculate from the left of the screen with `popperOffsets[mainSide] = referenceOffsets[mainSide]` instead of `popperOffsets[mainSide] = referenceOffsets[mainSide] + referenceOffsets[measurement] / 2 - popperRect[measurement] / 2;`. That probably holds true for "top left". 

I'm thinking I can either make a PR in popper.js or make the change in `Dialog` in function `getPopperStyles()` on line : ```const left = `${popperData.offsets.popper.left + propOffsets.horizontal}px`;```

What do you think?

Have we had any consumer of SLDSLookup using `align= "bottom left"` and `menuPosition="overflowBoundaryElement"` facing this issue in the past?

Another option is to try ComboBox but it's also using Dialog / Popper.js so I guess I would get into the same issue.

**Comment by interactivellama** [comment]
Ah, if it's not the default, then it hasn't been tested reviewed, etc. Popover is really the only dialog that has examples written for it for review in the Storybook. BTW, Lookup is deprecated and shouldn't be used in new work. 

We should probably have a Storybook story for each component that has all alignments for components with dropdowns. MenuDropdown, Combobox, etc. then we can use image snapshots to make sure we don't break them once they are fixed.

**Comment by davidlygagnon** [comment]
Yes, makes sense. 

Okay, now I know how to get unblocked. I need to use `placement="bottom-start"` in Popper.js, or `align="bottom left"` on `<Dialog>` in DSR. 

Either I make a PR in DSR to allow passing `align` as a prop to `<Lookup>` but since it's deprecated I can probably use `Combobox`, as you suggested, since it's using "bottom left" by default.

What do you suggest ?

**Comment by interactivellama** [comment]
Combobox is more accessible, so you get the benefit of that.

It looks like you can do a separator:
https://lightningdesignsystem.com/components/menus/
or a subheading
https://lightningdesignsystem.com/components/menus#With-Subheaders

The custom renderer `menuItem` exists in Combobox, but that would make it part of the selectable list and we don't want that, we need the internal state of Combobox `activeOption` to skip the subheadings and the separators. A default subheading and a separator would be the best for everyone.

If you just need the default separator and subheaders, I'd love to see

```
	{
		label: 'Menu Sub Heading',
		type: 'separator',
	},
	// Divider line separator
	{
		type: 'separator',
	},
```

as the API. If folks want to then use `menuItem` to change the look of separator and subheaders in order to do something custom, they can override the render with that function.

I think you'd want to do something like add a `notSelectable` parameter to `combobox.jsx`'s `getNewActiveOptionIndex` or `handleNavigateListboxMenu` and it would make the offset +2 instead of +1. We could say in the proptypes that we don't support two subheaders right after each other. At least that's my quick thoughts on it.

Does that sound good?

**Comment by davidlygagnon** [comment]
Yes, sounds good.

One oversight is that I only want to use a custom renderer for separators. Would it make sense to have a new prop `menuItemSeparator` that similar to `menuItem` but used only when an option is of `type: 'separator'` ?

**Comment by interactivellama** [comment]
I don't think there's a benefit. You'd just add a conditional within your render function and do whatever you want based on the contents of `option`.

**Comment by davidlygagnon** [comment]
Yes, I could do that but then I won't be able to use the `<span>` code from Menu.jsx for regular menu items, that is 

```
{props.menuItem ? (
  <MenuItem
    assistiveText={props.assistiveText}
    selected={selected}
    option={optionData}
  />
 ) : (
   // I would like to keep using this code for menu items that are not separator.
   <span className="slds-truncate" title={optionData.label}>
     {selected ? (
       <span className="slds-assistive-text">
         {props.assistiveText.optionSelectedInMenu}
      </span>
 ) : null}{' '}
   {optionData.label}
</span>
)}
```

I can copy that part of jsx into my custom renderer but that's not great..

That's why I was either proposing a `menuItemRenderer` prop that is a custom render for "separator" only.

What do you think?

**Comment by interactivellama** [comment]
I thought you needed complete control/flexibility. If you are following the default selectable menu, sub headings, and separator markup, then please add the default into `combobox/private/menu.jsx` and don't have any custom renderers.
