### ISSUE TITLE
Make library compatible with React 16

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1282]
While keeping React 15.5 for dev and tests until time can be allotted to update test framework.

There are React 16 users out there and they are not reporting issues, but that's anecdotal.

**Comment by vernak2539** [comment]
So we can use react 16 or is it still not recommended?

**Comment by chuyler** [comment]
@interactivellama, What's the reason for blocking React v16?  Are there a series of reported bugs associated with it that I could work through?  I'd really like to get our project up to date and this is blocking us.

**Comment by interactivellama** [comment]
I haven't seen any bugs reported for React 16, and I know of a few projects using it and just ignoring the peer dependency warning. The Mocha tests just need to be updated from when there written in 2015 in order to make sure everything works in v16 from a maintainer point of view.

 @chuyler, If you'd like to help out. Please install React to v16 and fix whatever bugs you find at `http://localhost:8001` after running `npm start`.

**Comment by chuyler** [comment]
Ok, sounds good.  I'll report and/or fix anything I find.

**Comment by interactivellama** [comment]
@chuyler Are there any updates on DSR usage in React 16? We've had a Modal issue reported, but that should be fixed in #1391.

**Comment by interactivellama** [comment]
Adding to thread for awareness from @davidlygagnon. `componentWillRecieveProps` is deprecated in React v16.3 and replaced with `getDerivedStateFromProps`. This break does not occur until v17.

Overview: https://medium.com/@baphemot/understanding-react-react-16-3-component-life-cycle-23129bc7a705
Docs: https://reactjs.org/blog/2018/03/29/react-v-16-3.html
