### ISSUE TITLE
Modal content has bottom border-radius when no header is present, but a footer is.

### ISSUE THREAD

**Issue by shaundr** [salesforce/design-system-react#1285]
This LOC adds a border radius if there is no header, but does not take in to account the presence of a footer, resulting in some funkiness: https://github.com/salesforce/design-system-react/blob/master/components/modal/index.jsx#L207

![modal border radius](https://user-images.githubusercontent.com/18273277/36452783-cbded03a-1663-11e8-81fd-cbc38297c1d7.png)

This is reproducible with the first example on the demo page https://react.lightningdesignsystem.com/components/modals/ by removing the title prop.

Ideally this would add a border-radius class (using $border-radius-medium design token?) to the modal instead of an inline style, so that we could redefine it in trailhead (our theme's border-radius is 0.5rem for modal windows).

**Comment by interactivellama** [comment]
It seems like we should fix it for this instance and provide a good default of no radius on the bottom, as to custom styles, is `contentStyle` with a SLDS token sufficient?

**Comment by interactivellama** [comment]
Oh, I see what you are saying. If SLDS doesn't have a border radius class (and I don't think it does) https://www.lightningdesignsystem.com/utilities/borders, you will need to file a feature request with them for a class.

For another possible solution, I'm open to using JSON from the design tokens library for inline styles, too. There's not a good framework for it though in this library at this time.

**Comment by pyojo** [comment]
I published a pull request that solve the problem. #1976
