### ISSUE TITLE
Play Benny Hill's Yakety Sax from terminal while building webpack

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1291]
I just discovered https://www.npmjs.com/package/benny-hill

```
npm install -g benny-hill
benny-hill # just play benny hill
```
What do you all think? Would it make the Webpack build _seem_ faster? ;-)

**Comment by chriscorwin** [comment]
OMG yes

Though, I’d like different songs to play at different _times_ during the build process.

_Linting_, for instance, might deserve a different song than, say, building CSS from SASS files.

But overall, this idea has merit.

**Comment by cormacmccarthy** [comment]
😆Haha, this is really funny.

For reasons too obvious to bother stating, we can't make it play automatically, and it's not even obvious to me that you are suggesting that (but you didn't specifically say you _wouldn't_ make it auto-play, so I wanted to explicitly clarify...)

All that said, I would merge --today! this instant!  a PR that allowed you to pass a _flag_ to the build process to make this play. Something like `--go-faster` or `--speed-up-build` or even just `--benny-hill` or `--yakety-sax`.

And I agree with @chriscorwin that it would be even cooler if we had different sounds happen at different stages. I'd love it if passing the `--go-faster` flag made Jeff Goldblum deliver his famous Jurassic Park/Independence Day "must go faster, must go faster" line at the very beginning.

However, we've probably spent more time just writing and reading these comments than it is worth, let alone the time to implement. It has almost zero ROI.

**Comment by davidlygagnon** [comment]
+1 for this idea ! That would definitely increase perceived performance!

**Comment by interactivellama** [comment]
Feel free to re-open this "fun" issue if anyone wants to. Removing from backlog.
