### ISSUE TITLE
SVG icons not showing when including the static resources in a page.

### ISSUE THREAD

**Issue by robertovg** [salesforce/design-system-react#1293]
Hi, we have built a salesforce (SF) application deploying to SF as a static resource.

We execute it from a **Lightning Component** like that.

```html
  <lightning:container aura:id="schedulingContainer" class="schedulingContainerWrapper" src="{!$Resource.schedulingComponentVisjs + '/index.html?lightningContainer=true'}"
    onmessage="{!c.handleMessage}" onerror="{!c.handleError}" />
```

And the entry point of the application is resolved ( because of the ligthing container ) into:

`https://pve-alpha-dev-ed--c.container.lightning.com/lcc/1519322045000/schedulingComponentVisjs/app.bundle.js`

Also we expose this application from a **VF page** like that:

```html
<apex:includeScript value="{!URLFOR($Resource.schedulingComponentVisjs, 'app.bundle.js')}"/>
```

And the entry point from this Page is resolved as:

`https://pve-alpha-dev-ed--c.eu11.visual.force.com/resource/1519322045000/schedulingComponentVisjs/app.bundle.js`

Everything works in both places ( **Lightning Component** and **VF page**  ), even icons from other libraries except with the svg icons used by this design-system-react.

As you can see, **Lightning Component** works, the SVGs have content inside the tags:

![component__showing_icon](https://user-images.githubusercontent.com/570679/36593214-152ca62c-1899-11e8-9991-69d4f0a06338.png)

But for the page, executing exactly the static resource and with the same reference in the SVG, doesn't:

![page__not_showing_icon](https://user-images.githubusercontent.com/570679/36593248-368291ce-1899-11e8-8c65-08a6b963543f.png).

Just to show the third place, when we work locally, we have those icons also working with the application not yet minified and packaged:

![local_showing_icons](https://user-images.githubusercontent.com/570679/36593450-0d0a165e-189a-11e8-8839-2ab237d7066d.png)

We have configured the **IconSettings** in the root of our React application (index.js) like:

```js
render(
    <Provider store={store}>
      <IconSettings
        actionSprite={actionSprite}
        customSprite={customSprite}
        doctypeSprite={doctypeSprite}
        standardSprite={standardSprite}
        utilitySprite={utilitySprite}
      >
        <App />
      </IconSettings>
    </Provider>,
    document.getElementById('app')
  );
```

How could we make those icons to be shown in the **VF page **?

**Comment by mpsenn** [comment]
I suspect that the SVG is attempting to load from the wrong URL. The URL for a Visualforce page is "/apex/pageName", so the SVG is probably trying to load from "/apex/svgName.svg" instead of "/resource/<resourceName>/svgName.svg".

You can verify my suspicion by looking at the Network tab in the Chrome debugger, and look at the Request URL while loading the SVG file.

If this is right, the solution is probably changing the loader for svg files in your webpack.js. Not quite sure.

**Comment by robertovg** [comment]
I finally got the solution and the explanation. Checking the network panel trying to find a problem when loading the SVG from the page, I found exactly what was happening. Adding the configuration on the as I put previously:

```js
<IconSettings
  actionSprite={actionSprite}
  customSprite={customSprite}
  doctypeSprite={doctypeSprite}
  standardSprite={standardSprite}
  utilitySprite={utilitySprite}
>
```

The `VF Page` try to resolve the SVG url to this one:

https://pve-alpha-dev-ed--c.eu11.visual.force.com/apex/eba50582ac0c773b2c45cf502fc7f01c.svg

Instead of the correct one: 

https://pve-alpha-dev-ed--c.eu11.visual.force.com/resource/1519322045000/schedulingComponentVisjs/eba50582ac0c773b2c45cf502fc7f01c.svg

Also I noticed that from the `LCC` it works like a charm resolving the SVG path to this one:

https://pve-alpha-dev-ed--c.eu11.visual.force.com/resource/1519322045000/schedulingComponentVisjs/eba50582ac0c773b2c45cf502fc7f01c.svg

So I tried to pass the static resource URL to the `iconPath` but again it was not working, because of the sub-folders of each type of icons.

At the end I found looking at the network the solution as it follows.

We have the correct structure of the icons always included in SF orgs in the following path: `/_slds/icons`.


So the final solution to have the icons working in Salesforce environment (from the `.page` and from the `.cmp` ) is just add this simple configuration. And not including the SVG in our static resources but instead consume the icons from Salesforce.

```jsx
      <IconSettings iconPath="/_slds/icons">
        <App />
      </IconSettings>
```

I'm sure this information will be very useful to anyone trying to use this library in SF environment.

**Comment by interactivellama** [comment]
Thanks @robertovg for following up with the solution. I'm sure you are not the only one. I know I've been asked questions like this in the past.

Although this is a Salesforce project, I'd prefer to keep platform specific question to a minimum and keep issues focused on the code within this project.

For folks that find this thread in the future:
* Salesforce platform questions: Please visit https://success.salesforce.com,  https://partners.salesforce.com, or https://salesforce.stackexchange.com I think you will find the experts on these topics more active within those resources.
* This project uses SLDS markup, but you should submit HTML/CSS issues to https://github.com/salesforce-ux/design-system.

**Comment by robertovg** [comment]
Thanks, I already tried on those changes but was salesforce miss information than your fault.
Thanks for the support anyway!
