### ISSUE TITLE
Combobox: Expose `required` attribute on input text label

### ISSUE THREAD

**Issue by davidlygagnon** [salesforce/design-system-react#1295]
I need to use a combobox with a (*) required label.

Combobox uses `<Label>` and that component has a required prop defined.

We should expose it in combobox.

I can add a key to `label` prop called `labelRequired`, that is a boolean.

What do you think?

**Comment by interactivellama** [comment]
Yeah, at it's core Combobox is a form element/input.  Checkbox, input, timepicker, textarea and a few others are just `required`, so let's do that for consistency.

```
"required": {
                "type": {
                    "name": "bool"
                },
                "required": false,
                "description": "Highlights the Checkbox as a required field (does not perform any validation)."
            },
```
