### ISSUE TITLE
Add support to defaultValue on `<Input>` component.

### ISSUE THREAD

**Issue by 3den** [salesforce/design-system-react#1305]
We are using DSR on trailhead and we are having issues using the `<Input>` component because it does not accept `defaultValue` currently you can pass `value` but doing that will mean much more complexity than required.

Please can you guys add support for defaultValue? or allow passing inputProps?

**Comment by 3den** [comment]
@interactivellama ^

**Comment by interactivellama** [comment]
I would like to keep DSR components "controlled" as much as we can. See [Codebase Overview](https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#controlled-and-uncontrolled-components). It is [the recommendation from the React team](https://reactjs.org/docs/uncontrolled-components.html), too. Uncontrolled components that use  the DOM to manage state are an anti-pattern. The other thing to worry about is switching from controlled to uncontrolled inputs.

Is this mostly an issue with having a non-redux/flux app where you want the input uncontrolled and are reading the DOM for state via `inputRef` on form submit? Is that an accurate assessment?

**Comment by interactivellama** [comment]
That said, it might be a good idea to allow folks transitioning from other frameworks to allow the DOM to manage state and just add comments and URLs on the prop that say its use is not recommended.

**Comment by 3den** [comment]
@interactivellama thanks for your quick feedback, I agree that managing the form with state is better than using refs, but both ways required a similar amount of boilerplate code to be added to the forms. 
We actually don't use neither to on our forms coz we built a Form component that automatically serializes the `data` so we need the defaultValue only to set the initial value of the forms.

Bellow its an example of our auto serialized `Form`:

```js
export default class Form extends React.PureComponent {
  static propTypes = {
    action: PropTypes.string.isRequired,
    method: PropTypes.string.isRequired,
    onSubmit: PropTypes.func,
    className: PropTypes.string,
    children: PropTypes.node
  };

  onSubmit = (e) => {
    const {onSubmit} = this.props;
    if (!onSubmit) return;
    e.preventDefault();
    
    // serialize function builds the form params based on its input names
    // just like a regular HTML form would.
    const data = serialize(this.form, {hash: true, empty: true});
    onSubmit(data);
  }

  render() {
    const {props: {children, ...otherProps}} = this;

    return (
      <form
        {...otherProps}
        ref={(form) => { this.form = form; }}
        acceptCharset="UTF-8"
        onSubmit={this.onSubmit}>
        <input name="utf8" type="hidden" value="&#x2713;" />
        {children}
      </form>
    );
  }
}
```

The component above can be use on our forms what would need any custom logic to deal with its inputs.

```js
function AboutMeForm({name, email, onSave}) {
    return (
       <Form action="/something" method="post" onSubmit={(data) => onSave(data)}>
          <input name="user[name]" defaultValue={name} />
          <input name="user[email]" defaultValue={email} />
          ...
       </Form>
    );
}
```

**Comment by 3den** [comment]
That said, there are multiple ways to make a cake, in some cases we controlled components are the best option, but that is not always true we don't want the complexity that of managing input state and building the serialized data manually on every single form.

**Comment by interactivellama** [comment]
I should have time to review a pull request for `defaultValue` next Tuesday or Friday--after that it will be a two weeks away. I think a Jest DOM snapshot would the best test, but the `input` doesn't have those set up right now, so Mocha is fine.

Something like `This sets the initial value of the `input` on an uncontrolled `input`. Use sparingly. This prop is only present to support uncontrolled components in applications that do not maintain a flux- like state.`

**Comment by 3den** [comment]
@interactivellama sounds good I will be glad to send a PR ;)
