### ISSUE TITLE
Add Slider Component

### ISSUE THREAD

**Issue by DanFerro** [salesforce/design-system-react#1314]
Initial request for a slider component. Support the following props:
- id
- name
- label
- value
- min
- max
- steps
- disabled
- size
- vertical (default false)
- className
- errorText
- aria-describedby
- assistiveText
- onChange
- onInput

**Comment by interactivellama** [comment]
Awesome! I'm glad you can contribute. I'll try to iterate on this prop list and confirm it's inline with the other components, but at first glance, it looks like you've done some pretty good research on that already based on the names of the props you've proposed.
