### ISSUE TITLE
GlobalHeaderProfile: invalid DOM nesting

### ISSUE THREAD

**Issue by joeferraro** [salesforce/design-system-react#1318]
Version: 0.8.10

The following generates invalid `li` DOM nesting:

```
<GlobalHeader>
  <GlobalHeaderProfile/>
</GlobalHeader>
```

![patient_discovery_cloud](https://user-images.githubusercontent.com/54157/38204836-6346be32-3672-11e8-8abb-61423f13430e.png)

![patient_discovery_cloud](https://user-images.githubusercontent.com/54157/38204649-bf8a9e58-3671-11e8-8d01-266910389662.png)

**Comment by interactivellama** [comment]
Apologies for the late reply. Here's the SLDS component it's modeled after https://www.lightningdesignsystem.com/components/global-navigation/ if you'd like to submit a pull request.
