### ISSUE TITLE
Tree Component - slow to expand

### ISSUE THREAD

**Issue by dennismphil** [salesforce/design-system-react#1320]
Noticing in the [example](https://react.lightningdesignsystem.com/components/tree) a few seconds delay for the branches to expand. 

![tree](https://user-images.githubusercontent.com/4141366/38262595-8e8ddd9a-3722-11e8-8be6-729e09c469ff.gif)

**Comment by interactivellama** [comment]
There is a timeout in the example.
-- 

*--*
STEPHEN M JAMES
Lead User Experience Engineer, Marketing, Commerce & Integration Clouds | s
alesƒorce
@tweetllama <http://twitter.com/tweetllama> :: sjam.es/linkedin
<http://linkedin.com/in/stephenmjames> :: sjames@salesforce.com ::
<sjames@salesforce.com>1-317-379-2814 :: MST/UTC-7:00

**Comment by dennismphil** [comment]
Just noticed the 500ms delay. Thanks!
