### ISSUE TITLE
Add Rich Text Editor

### ISSUE THREAD

**Issue by DanFerro** [salesforce/design-system-react#1325]
Before proposing any API/props etc, I wanted to gauge the need for the [Rich Text Editor](https://www.lightningdesignsystem.com/components/rich-text-editor/) as a component. I know I've ran into some instances in the past where this was beneficial.

**Comment by ButuzGOL** [comment]
Is there any info about this component ?

**Comment by interactivellama** [comment]
No, there are no plans right now to implement it by any of our product teams. I can share that it would probably be a wrapper of https://quilljs.com/ , but no work has been done on it.
