### ISSUE TITLE
Encounter some issue to install this package in my CRA

### ISSUE THREAD

**Issue by lwconquer** [salesforce/design-system-react#1331]
Hi,

I installed the DSR packages from NPM on my ejected Create-React-App app by using: $ npm install @salesforce-ux/design-system @salesforce/design-system-react. The terminal gave me some warning info after the installation saying the version of some packages don't compatible (my react version is 16.2.0).

And then I try to use the component in my app directly (es6 mode),
```
import Button from '@salesforce/design-system-react/components/button';
<Button label="Hello Button"/>
```
And I get some error message:
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/index.259b1640.jsx') is not a valid name.

And the error points to: ReactDOM.render(<App />, document.getElementById('root'));

If I change the import from (CommonJS mode):
```
import { Button } from '@salesforce/design-system-react';
<Button label="Hello Button"/>
```
The button can show up without any style applied. I tried several other component, but they have the same problem.

I don't know if I need some extra Barbel and Webpack configuration work before I can use this package in my app.

Thanks for your kindly help,

**Comment by interactivellama** [comment]
This mostly looks like a usage question, so moving the follow up to [StackOverflow](https://stackoverflow.com/questions/49929362/how-to-use-the-salesforce-design-system-react-package-in-my-create-react-app)
