### ISSUE TITLE
Generate Typescript and Flow type definitions from existing prop-types.

### ISSUE THREAD

**Issue by girishla** [salesforce/design-system-react#1346]
Are there any plans on providing Typescript type definitions  ?

**Comment by interactivellama** [comment]
There is nothing on the roadmap for `*.d.ts` files at this time. I'm open to them being added. We would probably need to add some tests that validate them, so that they don't get out of date.

**Comment by interactivellama** [comment]
How can we do this based on propTypes in an automated way?

Also provide Flow type definitions.

**Comment by futuremint** [comment]
I tried using [dts-gen](https://github.com/Microsoft/dts-gen) from Microsoft last week to create Typescript definitions but couldn't get it working using their basic CLI usage from the npm library.

However I'm sure it'll be straightforward to write up a script that uses the source file to generate type definition files from the PropTypes we've already written.

**Comment by interactivellama** [comment]
We might be able to use something from react-docgen AST parser if we need to do something custom.

**Comment by futuremint** [comment]
I'm going to work on adding a typedef file in October.  I will also look into generating a library definition for flow as well.

**Comment by ChuckJonas** [comment]
instead of trying to keep typedefs in sync, a better solution would just be to convert this to a typescript project 😉.

**Comment by futuremint** [comment]
I don't disagree... but providing a typedef file is a bit orthogonal to this project being typescript or not.  Being typescript would certainly _help_ this cause... but it doesn't prevent it either.  We have other typescript projects around Salesforce, the heavy lifting here would be around integrating `tsc` into the build system, and also around cleaning up the types.  IMHO, typescript's benefits don't really show up until you can turn on `strictNullChecks` without warnings/errors.

All that said... it is open source and we welcome contributions!  I'd be happy to review a PR if you wanted to work on converting to typescript.  We'd need to talk about it internally to see if the main contributors were comfortable with typescript though... we have some contributors who also use flow.

**Comment by ChuckJonas** [comment]
@futuremint I think the biggest benefit would be replacing the clunky `propTypes` definitions with typescript much better typing system.  I think there are other benefits as well, but I was half joking.... It's definitely a big ask.

In my dreamworld ESNextNext just adopts the typescript specification, so you might as well get on board now 😈

**Comment by futuremint** [comment]
Here is a library I found... https://github.com/KnisterPeter/react-to-typescript-definitions

**Comment by futuremint** [comment]
Also, consider using this to generate Flow types? https://github.com/joarwilk/flowgen

**Comment by dehru** [comment]
Hello, has there been any progress on types?

**Comment by interactivellama** [comment]
@dehru I think @futuremint has been pulled into other organizational priorities. 

I'm un-assigning the issue from you @futuremint until you are able to take this up.

**Comment by futuremint** [comment]
Thats fine to un-assign it.  @dehru we're an open sourced project and would welcome a contribution for this if you're inclined to take it on yourself.

**Comment by xoob** [comment]
Hey everyone, we are currently working on adding TypeScript compatibility for `design-system-react` and will provide a pull request that will add strict type definitions for every component and their prop types.

**Comment by ChuckJonas** [comment]
Curious if you are rewriting in ts or just adding type defs?

**Comment by xoob** [comment]
We are adding `.d.ts` files for the existing library. Our work utilizes `tsc` with `allowJs` and `checkJs`, and KnisterPeter/react-to-typescript-definitions. The goal is to be able to import the library into TypeScript projects and get code completion, strict validation, and no import errors, while trying to keep the changes to the library as minimal as possible.

**Comment by Ewilliams90** [comment]
Extremely excited about this @xoob and I would love to help if I can in any way.

**Comment by xoob** [comment]
I'm currently waiting for a number of pull requests to land before we continue on this.

**Comment by interactivellama** [comment]
@xoob Is that pull requests on our side or something internal to you?

@Ewilliams90 Welcome to Salesforce!

**Comment by garygong** [comment]
I think one of the PRs is on our side (https://github.com/salesforce/design-system-react/pull/2514).  I took a look at that one and it generally looks good.

**Comment by djdeimon** [comment]
I just can't wait  those types definitions. It will be really nice feature and finally I will avoid multiple import issues in my project.

**Comment by coler-j** [comment]
> We are adding `.d.ts` files for the existing library. Our work utilizes `tsc` with `allowJs` and `checkJs`, and KnisterPeter/react-to-typescript-definitions. The goal is to be able to import the library into TypeScript projects and get code completion, strict validation, and no import errors, while trying to keep the changes to the library as minimal as possible.

@xoob, I would be really interested in your workflow for this, currently looking into doing something similar. [Made a SO q ](https://stackoverflow.com/questions/65012352/generate-type-definitions-from-js-react-components-that-use-prop-types)to collate my search.
