### ISSUE TITLE
Add Expandable Section Component

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1361]
Simple hide/show. API should probably be similar to Accordion.

https://www.lightningdesignsystem.com/components/expandable-section/

**Comment by kyleheddon** [comment]
This is something my team has worked on for our internal project. Has there been any work done on this?

**Comment by interactivellama** [comment]
No, no one is currently working on it. I'm guessing it's simple enough that teams have been just making their own.

**Comment by interactivellama** [comment]
This is a list of relatively small in scope components that I put together https://github.com/salesforce/design-system-react/labels/base-component earlier this year.

**Comment by interactivellama** [comment]
@kyleheddon 
@kevinparkerson is updating AppLauncher and will be creating an Expandable Section, since App Launcher has one inside of it anyway. If you have anything in the works, could you push it up in a WIP pull request? If not, that's cool, too.

**Comment by kyleheddon** [comment]
@interactivellama We do not have anything ready outside of our internal Pardot repo. It would probably simpler if @kevinparkerson implemented it

**Comment by interactivellama** [comment]
@kyleheddon Sounds good. 

@kevinparkerson Can you write a props proposal for Expandable Section before you begin App Launcher?

**Comment by tanhengyeow** [comment]
For anyone that is following and record purposes, the props proposal can be found [here](https://github.com/salesforce/design-system-react/blob/b3c257f0d08fb74d138e0ca9932de7b70f9a89d8/components/expandable-section/index.jsx#L22), which is part of an ongoing [PR](https://github.com/salesforce/design-system-react/pull/1767).

The `Expandable Section` component sits in the `AppLauncher` component, so the PR includes work done for the `Expandable Section` component too, since it isn't currently present in SLDS React.

**Comment by kevinparkerson** [comment]
I proposed props in comments on the [App Launcher rework issue](https://github.com/salesforce/design-system-react/issues/1648) as well, but I'll move the ExpandableSection proposal to this issue instead.

**Comment by kevinparkerson** [comment]
This is my proposed PropType API for components/expandable-section:
```
const propTypes = {
	/**
	 * **Assistive text for accessibility.**
	 * * `toggleSection`: Label for the icon that expands / collapses the section
	 */
	assistiveText: PropTypes.shape({
		toggleSection: PropTypes.string,
	}),
	/**
	 * Contents of the section
	 */
	children: PropTypes.node,
	/**
	 * Class names to be added to the `slds-section` classed node
	 */
	className: PropTypes.oneOfType([
		PropTypes.array,
		PropTypes.object,
		PropTypes.string,
	]),
	/**
	 * Unique identifier for the expandable section. The id is automatically generated if not provided
	 */
	id: PropTypes.string,
	/**
	 * Specifies whether the section is expanded or collapsed. If not provided, component will use its own state to manage this itself
	 */
	isOpen: PropTypes.bool,
	/**
	 * Specifies whether the section can be expanded or collapsed. Defaults to `false`
	 */
	nonCollapsible: PropTypes.bool,
	/**
	 * Callback for when the section is expanded or collapsed. Passes event object and data object with `isOpen` bool.
	 */
	onToggleOpen: PropTypes.func,
	/**
	 * The title for the section
	 */
	title: PropTypes.string.isRequired,
};
```
