### ISSUE TITLE
Add Listbox Of Pill Options component

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1362]
Pill exists, but not a Listbox Of Pill Options. This will mostly mean pulling Combobox's selected listbox code out and making it a first level component with some additional options.

https://www.lightningdesignsystem.com/components/pills/

The render functions are in https://github.com/salesforce/design-system-react/blob/master/components/combobox/private/selected-listbox.jsx and the logic is in `index.js` class methods like https://github.com/salesforce/design-system-react/blob/master/components/combobox/combobox.jsx#L549

**Comment by kevinparkerson** [comment]
```
/**
 * **Assistive text for accessibility**
 * * `listboxLabel`: This is a label for the listbox. The default is `Selected Options:`.
 * * `removePill`: Used to remove a selected item (pill). Focus is on the pill. This is not a button. The default is `Press delete or backspace to remove`.
 */
assistiveText: PropTypes.shape({
	listboxLabel: PropTypes.string,
	removePill: PropTypes.string,
}),
/**
 * HTML id for Listbox of Pill Options
 */
id: PropTypes.string,
/**
 * **Text labels for internationalization**
 * * `removePillTitle`: Title on `X` icon
 */
labels: PropTypes.shape({
	removePillTitle: PropTypes.string,
}),
/**
 * Accepts an array of pill item objects.
 */
options: PropTypes.array,
/**
 * Function called when a pill is clicked
 */
onClickPill: PropTypes.func,
/**
 * Function called when a pill is 'removed' via the delete key or 'X' icon click
 */
onRemovePill: PropTypes.func,
```

**Comment by kevinparkerson** [comment]
@interactivellama I don't currently have it set up quite like that, but it'd only take a few tweaks to fit this pattern. Let's meet to sync up soon so we can finish this one up!
