### ISSUE TITLE
Update Button Group to use list variant

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1371]
This should allow tooltips trigger `div`'s to be wrapped around buttons within button group (such as in a page header and prevent the following. See list example in  https://www.lightningdesignsystem.com/components/button-groups/

![27f603fc-e3d4-11e6-8270-d72288554c08](https://user-images.githubusercontent.com/1290832/39904938-f7d4dabe-5497-11e8-8fb4-46bf7bd34b98.png)

**Comment by cormacmccarthy** [comment]
I'm not un-interested, but I don't have time at the moment.

**Comment by interactivellama** [comment]
@AnutaK @cormacmccarthy is not working on it. Please proceed.

**Comment by pulkonet** [comment]
I am willing to work on this. @interactivellama
