### ISSUE TITLE
Update DSR to Summer ’18 (SLDS 2.6.0)

### ISSUE THREAD

**Issue by kwilloughby** [salesforce/design-system-react#1372]
The Summer '18 (SLDS 2.6.0) version of SLDS is available on https://lightningdesignsystem.com/ so we should update DSR to use the Summer '18 version.

**Comment by kwilloughby** [comment]
@interactivellama

**Comment by interactivellama** [comment]
@kwilloughby Added to backlog https://github.com/salesforce/design-system-react/milestone/20

**Comment by interactivellama** [comment]
3 Issues from changes from update to SLDS 2.6.0. I will investigate them.

![story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-pill-listbox-of-pill-options-with-icon-1-diff](https://user-images.githubusercontent.com/1290832/40903245-025b7902-6794-11e8-8e0e-5fa05f0265d8.png)
![story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-tooltip-alignment-button-1-diff](https://user-images.githubusercontent.com/1290832/40903246-02794860-6794-11e8-8a53-fa54642d2872.png)
![story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-tooltip-alignment-span-1-diff](https://user-images.githubusercontent.com/1290832/40903247-0292db04-6794-11e8-9b55-0a3cc9e276fd.png)

**Comment by interactivellama** [comment]
A max-width has been added to tooltips and popovers.
