### ISSUE TITLE
Add Edit Dialog pattern

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1373]
# Do not use `EditDialog` within a full page form/record layout. This not a replacement for Inline Edit.

**It is meant for standalone "modify this word" parts of a page.**

This is not an Inline Edit pattern, but does have a similar UX pattern. If you were using an InlineEdit pattern outside a form, then this Edit Dialog variant of input is the replacement component. An Inline Edit UX pattern _within_ a form is A COMPLETELY DIFFERENT THING and is outside the scope of this Github issue. You should go look at #1395 

DSR's Inline Edit Form Input is a different pattern than https://www.lightningdesignsystem.com/components/form-element/#Inline-Edit

* Current `InlineEdit` component should be deprecated. [DONE]
* There is no close or cancel on blur with the new examples. ~Inline Edit appears to be upgrade path to [Fuel UX's Placard pattern](http://getfuelux.com/javascript.html#placard), but this should be discouraged.~ [DONE]
* ~Deprecation warning of current `InlineEdit` should point to a new `Popover` example on the doc site that shows an edit icon triggering a Popover with a base `Input` within it.~ [DONE]
* ~An example of a Inline Edit Form that swaps a read-only `Input` (that has a right-aligned edit icon on it) for a Base variant `Input` should be added to `Input`. Example should look like https://www.lightningdesignsystem.com/components/form-element/#View-Mode and https://www.lightningdesignsystem.com/components/form-element/#Edit-Mode (this is a different issue and outside scope of this issue, that should be considered a new Form component with a docked footer)~ #1395 

~We'll need to do this in consideration of https://github.com/salesforce/design-system-react/issues/273 which involves moving `components/form/InlineEdit` to `components/InlineEdit`, but in agreement with this issue should not be moved. It should be "removed" from the doc site and deprecated.~ [DONE]

**This is NOT a breaking change.**

**Comment by interactivellama** [comment]
I think this is the path forward for InlineEdit. @kwilloughby @aweibel

**Comment by kwilloughby-sf** [comment]
@interactivellama, here are the specs for the "Edit Dialog" Popover we discussed. I've also included the markup I used for the Popover itself. Feel free to tweak accordingly if the structure could be better.

![image](https://user-images.githubusercontent.com/42620858/45171780-53fa6480-b1d1-11e8-9d21-38e7e917bbb6.png)

`<div class="slds-popover__body" id="dialog-body-id-1"><div class="slds-form slds-form_stacked slds-p-top_medium slds-p-right_small slds-p-bottom_xx-small slds-p-left_small"><div class="slds-form-element"><label class="slds-form-element__label" for="text-input-id-1">Input Label 1</label><div class="slds-form-element__control"><input id="text-input-id-1" required="" class="slds-input" type="text" value=""></div></div><div class="slds-form-element"><label class="slds-form-element__label" for="text-input-id-2">Input Label 2</label><div class="slds-form-element__control"><input id="text-input-id-2" required="" class="slds-input" type="text" value=""></div></div><div class="slds-p-top_xx-small" style="text-align: right;"><button class="slds-button slds-button_neutral">Cancel</button><button class="slds-button slds-button_brand" disabled="">Save</button></div></div></div>`

**Comment by interactivellama** [comment]
As we talked about on Tuesday:
```
import EditDialogPopover from ../popover/EditDialogPopover

<Input
  editDialogPopover={<EditDialogPopover
    position
    onCancel
    onSave
  >children</EditDialogPopover>}
  variant='edit-dialog' />
```

`EditDialogPopover` defaults to having a cancel and save button and special padding etc.

**Comment by interactivellama** [comment]
@shaundr Just contacted me and said that the Trailhead team was interested in this component.

**Comment by interactivellama** [comment]
This pattern is for headings and random text on the page.

* The edit pencil icon should be next to the words
* No line should be present 
* Visible `label` should be present in the example.
* There are not any line separations (such as footer) inside the popover. The ones in Keith's design are for spacing purposes only.

**Comment by interactivellama** [comment]
* This is not connected with an Input. Input should be removed from the pattern and moved to Popover folder. `component/popover/edit-dialog.jsx`
* Edit Dialog should it's own sub component and have a default child of an edit icon/button that can have it's assistive text changed.

```
<EditDialog 
  popover={<Popover body= />}
  heading="" // (and other props that exist in open PR)
 />

```
Use case:
![53668065-0ca8da00-3c30-11e9-92fe-8ef3a351bcfe](https://user-images.githubusercontent.com/1290832/55759708-577bf580-5a17-11e9-8c3f-e8d1c65b02b1.png)

**Comment by shaundr** [comment]
@interactivellama with which release do you plan to remove support for `<InlineEdit />`?

**Comment by interactivellama** [comment]
Removal is not on the roadmap at this time. The warning is primarily to say it's not an accessible SLDS pattern.
