### ISSUE TITLE
Progress Indicator Style/Color Updates

### ISSUE THREAD

**Issue by kwilloughby** [salesforce/design-system-react#1374]
The Progress Indicator needs to be updated to fix the following issues:

- The blue Tooltip should always use regular Tooltip text (i.e. no bold, no italic)
- The blue Tooltip should always be blue even if an error occurs on a step
- The error icon (red triangle) needs to be updated to the new error icon (red ban sign) - this might automatically change when we update to Summer ’18 (SLDS 2.6.0)

** Note: If an error occurs a second error icon should be placed to the left of the buttons (e.g. Cancel, Save) and the Error Popover should appear indicating there are errors. These additional items are NOT part of this component. This note was included for visibility purposes. **

**Comment by interactivellama** [comment]
<img width="389" alt="screen shot 2018-07-05 at 3 30 46 pm" src="https://user-images.githubusercontent.com/1290832/42346486-6a7d0612-8068-11e8-9128-7a19198780cb.png">
