### ISSUE TITLE
Side Navigation with sub items

### ISSUE THREAD

**Issue by vernak2539** [salesforce/design-system-react#1375]
Does the navigation component have support for sub items? Can it behave like a tree?

**Comment by interactivellama** [comment]
I don't believe either. I will double check with the SLDS team. DSR Navigation certainly can't. @futuremint just implemented some side navigation with multiple DSR `Tree` components I believe.

**Comment by interactivellama** [comment]
I found the answer. 

> You should use a tree. We use this pattern in Sales Cloud Setup, when the vertical navigation has hierarchy, we use the SLDS Tree https://lightningdesignsystem.com/components/trees/
