### ISSUE TITLE
Slider: Allow value to be set

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1398]
Currently Slider doesn't set the `value` of the input, and therefore cannot be a controlled component. This means it just doesn't work.

The following should work, but since the value attribute of `input` doesn't ever change `onChange` is never fired.

```
const DemoSlider = createReactClass({
	displayName: 'DemoSlider',

	getInitialState () {
		return {
			value: this.props.value,
		};
	},

	handleChange (event, { value }) {
		this.setState({ value: parseInt(value, 10) });
	},

	render () {
		return (
			<Slider
				{...this.props}
				value={this.state.value}
				onChange={this.handleChange}
			/>
		);
	},
});

const Example = createReactClass({
	displayName: 'SliderExample',

	render () {
		return (
			<section>
				<ol>
					<li className="slds-p-bottom--large">
						<h1 className="slds-text-title_caps slds-p-vertical--medium">
							1. Base Input with label
						</h1>
						<DemoSlider id="base-id" label="My Label" value={50} />
					</li>
				</ol>
			</section>
		);
	},
});

export default Example;

```

**Comment by DanFerro** [comment]
@interactivellama this should only be the case with the example correct? Example in this case is just using DemoSlider as a helper for state control.

**Comment by interactivellama** [comment]
The `value` prop is not being added to the `input` [Line 194](https://github.com/salesforce/design-system-react/blob/master/components/slider/index.jsx#L194), so the state never changes the input value. The label is being updated, so it got past my review. It doesn't look like the `onChange` event fires based on the input, since the input value is always the same. Did you want to want pick this issue up?

**Comment by DanFerro** [comment]
Ah, see it now. Will take.

**Comment by interactivellama** [comment]
Thanks! @DanFerro
