### ISSUE TITLE
RowActions (within DataTable) should support all properties of SLDSMenuDropdown

### ISSUE THREAD

**Issue by danperry-salesforce** [salesforce/design-system-react#1403]
Specifically I want to implement the menuPosition and length attributes from SLDSMenuDropdown but I will add all the attributes for completeness.
- I will work on this
- Its related to the following work item: W-4505052

**Comment by interactivellama** [comment]
Thank you for wanting to help out the library. I think this is a great idea!

I would like to minimize duplicate documentation if possible--that is listing all the same props in two different components--it's prone to become out of date. Would you be open to doing something like the [Filter/Popover](https://github.com/salesforce/design-system-react/blob/master/components/filter/index.jsx#L104) prop? It is similar to a Higher-Order Component in that it takes a Popover, grabs the props, and merges them with the default props provided by the parent.

This should:
* give you access to all the drop down props
* Allow autocomplete to work in IDEs for free
* limit the API surface area

**Comment by danperry-salesforce** [comment]
@interactivellama my plan was to do something similar ala: 
```javascript
	{
		/**
		 * `Dropdown` properties.
		 * This will not override equivalent properties on this component (ie. onAction or options)
		 * See `Dropdown`
		 */
		 dropdownProps: PropTypes.shape(Dropdown.propTypes)
	}
```
and merge them in from there.  This way we wouldn't need to construct a component.  Is that ok?

**Comment by danperry-salesforce** [comment]
Here is how I was merging them (still haven't tested):
```javascript
	// ### Render
	render () {
		// i18n
		let defaultDropdownProps = {
			align: 'right',
			buttonClassName: 'slds-button--icon-x-small',
			buttonVariant: 'icon',
			iconCategory: 'utility',
			iconName: 'down',
			iconSize: 'small',
			iconVariant: 'border-filled'
		};

		let firstLevelProps = {
			assistiveText: this.props.assistiveText,
			className: this.props.className,
			options: this.props.options,
			//hint needs to remain undefined or merge will overwrite 'hint' in props.dropdownProps
			hint: isUndefined(this.props.noHint) ? undefined : !this.props.noHint,
			id: this.props.id,
			onSelect: this.handleSelect,
		};

		let dropdownProps = merge({}, defaultDropdownProps, this.props.dropdownProps, firstLevelProps);

		return (
			/* eslint-disable jsx-a11y/no-static-element-interactions */
			<td
				className=""
				data-label="Actions"
				onClick={this.handleClick}
				style={{ width: '3.25rem' }}
			>
				{/* eslint-enable jsx-a11y/no-static-element-interactions */}
				<Dropdown {...dropdownProps} />
			</td>
		);
	}
```

**Comment by danperry-salesforce** [comment]
I changed my mine, I will keep this consistant :)
