### ISSUE TITLE
Navigation not working for dropdowns

### ISSUE THREAD

**Issue by MadhuVK** [salesforce/design-system-react#1433]
Global Nav Dropdowns / Standard Dropdowns don't seem navigating properly.

![ezgif-4-4e9ede2806](https://user-images.githubusercontent.com/1362193/41889196-15598e1e-78be-11e8-8c68-9461ec3e7d31.gif)

The screen is from the react-slds storybook for the GlobalNavigationBar. One of the dropdown items specifies a hyperlink to google.com, which the navbar does not seem to be respecting. 

The hyperlink also doesn't appear to be working for standard dropdowns.
I see this behavior on the react-slds website for [navbar](https://react.lightningdesignsystem.com/components/global-navigation-bar) and [dropdowns](https://react.lightningdesignsystem.com/components/dropdown-menus/) as well.

In contrast to this, the [SLDSNavigation](https://react.lightningdesignsystem.com/components/navigation/)  element does respect the hyperlink.

**Browsers Tested**:
Safari
Chrome

**Comment by interactivellama** [comment]
What behavior are you expecting?

**Comment by interactivellama** [comment]
Please check the source code, but I think it's just supposed to fire off an event with a data object payload that has the URL that then the app needs to trigger the location change on. I wouldn't want to presume to control your apps URL with a UI component.
