### ISSUE TITLE
Remove non-breaking text from popover examples

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1447]
![screen shot 2018-07-09 at 12 54 55 pm](https://user-images.githubusercontent.com/1290832/42470314-53e663be-8377-11e8-9667-be9006afdfb3.png)

Remove non-breaking text in the four storybook stories, now that popover's have a max width. Add a paragraph of dummy text. The lorum ipsum here is fine. https://www.lightningdesignsystem.com/components/tooltips/

http://design-system-react-components.herokuapp.com/?selectedKind=SLDSPopoverTooltip&selectedStory=Open&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by kwilloughby** [comment]
@interactivellama, Tooltips (i.e. blue background Popover) shouldn't have a close x.
