### ISSUE TITLE
Fix Info Icon Tooltip Position

### ISSUE THREAD

**Issue by kwilloughby** [salesforce/design-system-react#1448]
When a Tooltip and info icon are used together the point of the Tooltip should be centered over the info icon. The position of the point should always be centered regardless of which alignment type is being used. The align="top" (i.e. top/centered) position works properly but there may be situations when teams need to use another alignment type such as in a modal where the input label is short.

![image](https://user-images.githubusercontent.com/18220268/42517184-1f6c3c9c-842d-11e8-8c35-031857f89172.png)

![image](https://user-images.githubusercontent.com/18220268/42517112-faf91ba0-842c-11e8-8549-cfca12c13398.png)

https://react.lightningdesignsystem.com/components/tooltips/

**Comment by kwilloughby** [comment]
@interactivellama, here is the ticket we discussed yesterday regarding the info icon Tooltip.

**Comment by interactivellama** [comment]
The awesome Mr. @Vintik fixed this recently in #1404.

![screen shot 2018-08-03 at 2 03 19 pm](https://user-images.githubusercontent.com/1290832/43663246-fecf1890-9725-11e8-9922-977808d31a18.png)
