### ISSUE TITLE
Allow Avatar components to be passed as a prop to GlobalHeaderProfile

### ISSUE THREAD

**Issue by sudowork** [salesforce/design-system-react#1461]
Currently the `GlobalHeaderProfile` component only accepts strings (image URLs) for the `avatar` prop. It would be nice to be able to pass down an `Avatar` component instead to get fallback support for initials. It could potentially be nice to pass any React element in.

- I am not currently working on this issue, but I can if you would like.
- Minimal example:
```jsx
<GlobalHeader logoSrc="/images/logo.svg">
  <GlobalHeaderProfile
    avatar={<Avatar variant="user" label="Foo Bar" size="medium" />}
  />
</GlobalHeader>
```

**Comment by interactivellama** [comment]
I think this is a good proposal. Global header hasn't been worked on in a while and that was before the `Avatar` component existed. Please proceed.
