### ISSUE TITLE
AppLauncher export missing

### ISSUE THREAD

**Issue by neilmiddleton** [salesforce/design-system-react#1463]
Seems like a simple oversight, but I'm seeing this:

```
'@salesforce/design-system-react/' does not contain an export named 'AppLauncher'.
```

I'm importing it the same way as everything else, but something appears to be missing inside the module which allows this component to be usable.  This is me calling from within a create-react-app app using the following syntax:

```js
import {
    IconSettings,
    GlobalNavigationBar,
    GlobalNavigationBarRegion,
    GlobalNavigationBarLink,
    AppLauncher
} from '@salesforce/design-system-react/';
```

**Comment by interactivellama** [comment]
You are correct. Please add to `components/index.js`. This was originally an inner source project and 95% of consumers used the "advanced source code import" (see readme) and and not the CommonJS/CRA compatible way, and it's just not been added.
