### ISSUE TITLE
Accessibility issue on combobox

### ISSUE THREAD

**Issue by rsukale** [salesforce/design-system-react#1475]
We are using the [aXe extension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd) on Chrome to evaluate the accessibility. When using the `<Combobox id="search"  ... />`, we are seeing the following accessibility error being reported - `Invalid ARIA attribute value: aria-controls="search-listbox"`

I found that the aria-controls are being generated by the component [here](https://github.com/salesforce/design-system-react/blob/master/components/combobox/combobox.jsx#L348)

Please include in your issue:

* If you are a Salesforce employee? -  Yes. I will be creating an internal ticket.

**Comment by interactivellama** [comment]
First, awesome to hear you are running aXe in your App! 👍 💯 

If you run it with the listbox(menu open), it should fix the issue. aXe is kind of a static attributes checking tool. If you'd rather not, then you can remove that attributes from the input by default, and add it when the menu is open with a pull request.
