### ISSUE TITLE
Use single underscore for BEM modifier classes instead of double-hyphen

### ISSUE THREAD

**Issue by sudowork** [salesforce/design-system-react#1493]
As of the 2.3.1 release of [@salesforce-ux/design-system](https://github.com/salesforce-ux/design-system), it seems that the double-hyphen `--` syntax for CSS modifier classes has been deprecated in favor of a single underscore `_`.

From https://www.lightningdesignsystem.com/release-notes/:
> ## Release 2.3.1 - May 25, 2017
> ### Big Impact
> **BEM Naming Change**
> Initially we used the double dash style for BEM notation (--). Due to the fact that double dashes are problematic in an XML environment (which doesn't allow double dashes within comments), we have upgraded our syntax to use the single underscore style (_). This change is backward compatible for 18 months. But all components going forward are built with the single underscore BEM style.

Ironically, the markup on that page seems to still use the double-hyphen syntax.

If the single underscore is the recommended syntax going forward (and if the double-hyphen syntax will be removed in a few months), it would be great to switch the @salesforce/design-system-react components and the examples in the documentation to use the new syntax.

In our codebase, it has caused a mixed use of both syntaxes. I ended up writing an ESLint rule with a fixer to resolve the issue for us (which I'm happy to provide here as well if you think it will be useful).

**Comment by interactivellama** [comment]
Thanks for thinking of us! Please proceed. It would be appreciated.

`eslint` is part of the project's test task. Is it something that would work with `eslint --fix`? Would all the issues need to be fixed first before we could merge it?

**Comment by sudowork** [comment]
Yes, it is fixable with `eslint --fix`. I'll find some time to put up a PR. I could fix the class names as part of the PR, though I'm not sure how you'd want to best handle that given it could lead to some conflicts with outstanding PRs. Let me know what you think.

**Comment by interactivellama** [comment]
That's very thoughtful. All open PRs except for your Avatar one right now are internal employee contributions. Please go ahead and modify everything and update your other pull request--if this something you can do in the next few days. I will deal with and tweak open PRs with this change, etc. if needed.

**Comment by sudowork** [comment]
Going to work on this now. My plan is to create an eslint plugin within this repo and use it in the eslint config. `eslint` does have a CLI options for specifying a custom `--rulesdir`; however, that would mean all developers would need to invoke it with that flag (which seems like a bad developer experience).

Ideally, the ESLint plugin containing the custom rule would be published itself. However, I was thinking to just install the dev dependency from the local directory for the time being. I'll put up a PR, but mark it as DO NOT MERGE because I don't know if you would want to merge it with the local dependency.

**Comment by interactivellama** [comment]
This seems like a local plugin to me--although you might ask the SLDS team @brandonferrua @stefsull if they are interested in an eslint plugin NPM module for the changes to the BEM structure that we had to make because of Platform issues (I think). 

As far as eslint CLI arguments, no one should be running `eslint` by itself in this library. See https://github.com/salesforce/design-system-react/blob/master/package.json#L21 . We should just be able to tack it on to existing NPM scripts. Does that sound good to you?

**Comment by sudowork** [comment]
My only worry would be those who use ESLint in their IDEs would need to match the same settings.

**Comment by interactivellama** [comment]
@sudowork I'm open to NPM publishing packages to, if that's easiest.

See the Babel preset folder here. https://github.com/salesforce/design-system-react/tree/master/preset

I rename the `package.json` file and push that folder to NPM, so that's an option, too.

**Comment by sudowork** [comment]
I think the local package will work. I had some issues with prettier-eslint, but it should work with the additional `--eslint-path` argument in the npm script.

**Comment by interactivellama** [comment]
I plan to remove `prettier-eslint` in the next month or so and just go straight prettier AND eslint. I can remove it sooner than later if it makes it easier for you.

**Comment by interactivellama** [comment]
You can build on this if you want. https://github.com/salesforce/design-system-react/pull/1528
