### ISSUE TITLE
Better delineate event and markup tests

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1497]
Currently, due to their familiarity with Mocha (and the test file's presences within the component folder), contributors lean toward jQuery-like DOM searches within Mocha for markup tests.

* Mocha tests should be used as a **last resort** for anything that needs interactive browser testing or a real DOM (this is typically events such as press up, down, right up on the keyboard and see what happens).
* Rename files for better dev experience. Make source code the documentation. `combobox-events-only-tests.js` instead of `combobox-browser-tests.js`.
* Add headers to all Mocha tests that explicitly say to use Jest snapshot tests as the default and only Mocha as a "have to." 
* Update test readme with this approach.
* Move custom snapshot tests such as Combobox into story based Storyshots tests.
* Remove Mocha DOM query bad examples.

**Comment by futuremint** [comment]
I don't think we need to rename files, but maybe being more explicit in the testing readme would help...
