### ISSUE TITLE
Combobox - Focus out on dropdown doesn't reset the option value

### ISSUE THREAD

**Issue by dixiekee** [salesforce/design-system-react#1501]
Bug:
In the combobox, make a selection. Now click the combobox again, use arrow keys to navigate to another selection. Without applying it, click away so the menu closes. I would expect the change not to apply, but the input reflects the change. Furthermore, if you open the menu again, you'll see your previous selection checked, rather than what's now displayed in the input, which is inconsistent.

I have a fix ready for the bug.
I'm a Salesforce employee.
Original bug is logged in W-5175592.

**Comment by interactivellama** [comment]
Could you add a test in Mocha/browser tests in order to prevent regressions in the future.
