### ISSUE TITLE
FixedLayout DataTableColumn widths don't actually apply

### ISSUE THREAD

**Issue by Vintik** [salesforce/design-system-react#1525]
Repro:

Go to the documentation or storybooks and observe that the <th> never gets the width from the column. Only the <td> gets it. Not sure how this ever worked in any previous version.

From my observations the <td> doesn't actually need the width and the column width is mainly determined by the <th>

Most my application's fixed tables also just lost any sort auto-default sizing when upgrading 0.7.x -> 0.8.x so this may be something to watch out for.

**Comment by interactivellama** [comment]
It looks like I made that change back in May. I know there were some column header and CSS issues with getting the columns to work right. https://github.com/salesforce/design-system-react/pull/1385/files#diff-3cb7b26035bf69c334a280c711f1214dR188
