### ISSUE TITLE
v0.8.23 build error

### ISSUE THREAD

**Issue by allankane** [salesforce/design-system-react#1535]
https://unpkg.com/@salesforce/design-system-react@0.8.23/lib/components/global-navigation-bar/docs.json
The above file does not exist. Therefore I encountered an error when building my React app with the version of 0.8.23.

**Comment by interactivellama** [comment]
Fix made and will be released shortly. Thank you for speaking up!

**Comment by interactivellama** [comment]
Fixed in https://github.com/salesforce/design-system-react/releases/tag/v0.8.24
