### ISSUE TITLE
CustomDataTableCell has no access to children

### ISSUE THREAD

**Issue by Niondir** [salesforce/design-system-react#1547]
In `row.jsx` the table `Cell` is rendered with the value (`{this.props.item[column.props.property]}`) as children.

From the example this works fine if you like to render the property, but I would like to be able to have real customized cells that can keep their children.

In the following example I would like to be able to render the inner div inside my `CustomDataTableCell`

```
<slds.DataTableColumn label="CustomColumn">
    <CustomDataTableCell>
        <div>this can't be rendered inside CustomDataTableCell</div> 
   </CustomDataTableCell>
</slds.DataTableColumn>

```

**Comment by interactivellama** [comment]
Did you see the "advanced" example on the doc site? https://github.com/salesforce/design-system-react/blob/master/components/data-table/__examples__/advanced.jsx#L11-L12

Is `slds-truncate` or the extra `div` messing up your table or something like that?

**Comment by Niondir** [comment]
I know that, but then `children` is just the property from the item list, no the actual children of my `CustomDataTableCell` which is confusing. It would be more clear when the item property is stored in some separate property and leave the React children behavior default. 

Since thats a breaking change, at least having the real children available would be nice.

**Comment by interactivellama** [comment]
Are you saying you want something like a `cellContainer` prop that allows a custom `div`, too?

```
const CustomDataTableCell = ({ children, ...props }) => (
	<DataTableCell {...props} cellContainer={
                 <div
			className={classNames({
				'slds-truncate': props.fixedLayout,
			})}
			title={props.title || childText}
		>
		    {children}
		</div>}>
	</DataTableCell>
);
```

I believe the initial reason behind this was was to hard code the `truncate` class and `title` into the UX pattern, but I'm open to allowing it not to be there.
