### ISSUE TITLE
Invalid prop `type` of value `file`

### ISSUE THREAD

**Issue by michaelcavallaro03** [salesforce/design-system-react#1558]
After utilizing the Input component to upload files, I noticed that there was no 'file' input PropType in the Input Component's Document or within the input.jsx source file. 

As expected, the following console error is thrown: 
![screen shot 2018-09-16 at 11 42 22 pm](https://user-images.githubusercontent.com/27144805/45607550-644ce380-ba0a-11e8-800a-3b256d4f6b1f.png)

I will begin working on the pull request for this.

**Comment by interactivellama** [comment]
@michaelcavallaro03 Thanks you for the offer. Adding the type is a good additional, but file uploads should use https://lightningdesignsystem.com/components/file-selector/ if you'd like to contribute the base variant of that component instead. It is not currently in this library.
