### ISSUE TITLE
Toast role="status" instead of role="alert"

### ISSUE THREAD

**Issue by shaundr** [salesforce/design-system-react#1559]
Toast currently has the role attribute set to "alert", SLDS documentation specifies it as "status".

DSR Toast Snapshot:
https://github.com/salesforce/design-system-react/blob/master/components/toast/__tests__/__snapshots__/toast.snapshot-test.jsx.snap#L9

Toast documentation:
https://lightningdesignsystem.com/components/toast/#site-main-content

**Comment by interactivellama** [comment]
Yeah, it can updated. I've asked the SLDS team if we need to remove "the focus grab" also, on their GUS channel.

**Comment by interactivellama** [comment]
OK, SLDS says keep focus because of the links are present. Let's just align to role status as you said.
