### ISSUE TITLE
add  ref, data, className props  to radio input

### ISSUE THREAD

**Issue by seirykborys** [salesforce/design-system-react#1577]
what do you think about adding ( ref, data, className ) props  to radio input ?
if it's ok, i can do it.

**Comment by interactivellama** [comment]
@seirykborys Unless you know something I don't, I think the value is a `string` in the HTML spec and that `event.target.value` will always return a string, and I would lean to wanting to keep the value type the same across "input" and "output".

https://reactjs.org/docs/forms.html
https://www.w3.org/wiki/HTML/Elements/input/radio

What do you think?
