### ISSUE TITLE
DataTable with "stacked" (or "stackedHorizontal") is broken.

### ISSUE THREAD

**Issue by jgerigmeyer** [salesforce/design-system-react#1580]
Based on SLDS, a "stacked" data table on mobile should look something like:

![screenshot 2018-09-25 16 39 08](https://user-images.githubusercontent.com/552316/46041743-8c5ed580-c0e1-11e8-9014-12d59de931e0.jpg)

...and a "stackedHorizontal" data table should look similar to:

![screenshot 2018-09-25 16 39 43](https://user-images.githubusercontent.com/552316/46041772-a00a3c00-c0e1-11e8-9b0b-ad7d0162da4f.jpg)

Currently, however, the column headers are hidden entirely on mobile when the `stacked` option is used:

![screenshot 2018-09-25 16 41 27](https://user-images.githubusercontent.com/552316/46041877-ea8bb880-c0e1-11e8-99fd-c46f09598776.jpg)

And similarly for `stackedHorizontal` (once #1579 is merged):

![screenshot 2018-09-25 16 43 20](https://user-images.githubusercontent.com/552316/46041957-2cb4fa00-c0e2-11e8-8105-a097d9f0a2b7.jpg)

**Comment by dangmai** [comment]
I'm also running into this issue. Furthermore if you have `DataTableRowActions` you won't be able to see the options in a small viewport.

**Comment by jcro21** [comment]
This is still an issue, it's a simple fix - I've created a PR here https://github.com/salesforce/design-system-react/pull/2685, it'd be great to get it merged!
