### ISSUE TITLE
Missing Card without header

### ISSUE THREAD

**Issue by Niondir** [salesforce/design-system-react#1581]
On the `<Card>` component the Header is not optional. I often use Cards for tables below a `<PageHeader>` where the Card Header might be redundant in some cases (depending on the Page).

Would you consider to make the Card header optional or are there other ways to put a Border and Background around my table?

One workaround might be:
`slds-box  slds-theme_default` which would give the border and background, but adds too much padding and adding an additional `style={{"padding":0, "border-top":"0px"}}` feels wrong.

**Comment by jgerigmeyer** [comment]
I ran into this same issue -- my temporary workaround was just to add `.slds-card` to the contents (in my case a `DataTable`).

**Comment by interactivellama** [comment]
Yeah, that's what it would be. A `hasNoHeader` prop is fine if that would be helpful @Niondir to wrap the `children` prop.

**Comment by Niondir** [comment]
Any progress here? At least a workaround should be documented imho.

**Comment by pulkonet** [comment]
@interactivellama Can I work on this?
