### ISSUE TITLE
Input: Add styleInput prop 

### ISSUE THREAD

**Issue by seirykborys** [salesforce/design-system-react#1588]
What do you think about adding such props as  errorText and inputStyle from datePicker to input?
I have already created PR with this changes, and it would be nice if you approve it.

**Comment by interactivellama** [comment]
Datepicker takes an `<Input />` as `children`. I think that is what you are looking for. https://react.lightningdesignsystem.com/components/date-pickers/#prop-children

This allows any prop that is in `Input` to be passed in. I'm going to close, but feel free to re-open if you can't use `<Input errortext="test"/>`. https://react.lightningdesignsystem.com/components/inputs/#prop-errorText

Of even better, update the prop description to make it more clear for others!

**Comment by interactivellama** [comment]
Re-opening. There is no style prop for Input right now. Please update the pull request to only add `styleInput` to Input. Please add a DOM markup test to confirm it works. By that I mean, add an example to storybook called `Custom Style` in https://github.com/salesforce/design-system-react/blob/master/components/input/__docs__/storybook-stories.jsx#L45 and it will automatically create a DOM snapshot test for your story.

**Comment by seirykborys** [comment]
I have created new PR, thank's for the hints which helped me properly to do it.
