### ISSUE TITLE
Footer and header render in combobox

### ISSUE THREAD

**Issue by seirykborys** [salesforce/design-system-react#1600]
Component Lookup is deprecated and instead we have to use combobox. But I didn't find footer render in combobox. Can we add this functionality ?

**Comment by interactivellama** [comment]
Yeah, looks like the search header could be added. https://www.lightningdesignsystem.com/components/combobox/#Displaying-options-based-on-user-input-2

And it looks like you could do entity search here with two or three headers. https://www.lightningdesignsystem.com/guidelines/search/global/#instant-results

I don't have the footer + New Contact markup, but it looks like it's the same markup as the header.

![image](https://user-images.githubusercontent.com/1290832/46897326-27c0ac00-ce3f-11e8-91c9-9f85ca5f4120.png)

It looks like we need a new Combobox variant called `lookup` will add the the search header on by default, once typing starts.

We can add `optionsSearchEntity` as a prop that takes options just like normals `options` that way folks can have the `"searchTeam" in Entity` option added at the top.

As for the footer, I've not seen anything besides Add an item like "+ New Contact" there. I'm thinking that we add an `addItemOption` prop with an `labels.addItemOption` string with a default label of "New Entity".

What do you think?

**Comment by seirykborys** [comment]
It sounds great, and would be nice to add this features in next release. So are you going to do this or better I do this ?

**Comment by interactivellama** [comment]
I thought about it some more. Let's make `label` a function that gets `inputValue` from the component and returns a string to render. If consumers want to go crazy with some other  markup, they can use the `menuItem` render prop.

```
optionsSearchEntity: [{ id:'search-entity-1', icon: <Icon assistiveText={{ label: 'search' }} category="utility" name="search" /> , label: ({ inputValue }) => `${inputValue} in Entity` } ]

optionsAddItem: [{ id:'add-item-1', icon: <Icon assistiveText={{ label: 'add' }} category="utility" name="add" /> , label: 'New Entity' } ]
```

When working with scope, are you referring to [Grouped Comboboxes](https://www.lightningdesignsystem.com/components/combobox/#Grouped-Comboboxes-(Cross-entity-Polymorphic))? 

I propose adding a `variant: 'cross-entity'`. That has an `entityCombobox` render prop that by default is a read-only Combobox itself and you pass a Combobox into it with it's own `options` array. I think this should bypass any additional props.

@futuremint What do you think about this prop API for Grouped Comboboxes (Cross-entity / Polymorphic)?

**Comment by seirykborys** [comment]
Yes , when I am talking about **scope** I mean  Grouped Comboboxes

**Comment by seirykborys** [comment]
If we will merge **optionsSearchEntity** or **optionsAddItem** in **options** we will be able to select its as a value but in my vision it's has to be as a button.
So, may be better to set **optionsSearchEntity** or **optionsAddItem* values as object and render it above or below **menu** ?

**Comment by interactivellama** [comment]
I don't think you can have a button in a menu listbox from ARIA/Accessibility Tree stand point. A button would have a tab index and remove focus from the input.

Also from what I can tell from the Salesforce Platform keyboard interactions, you just press down arrow to seamlessly go from items in `optionsSearchEntity` to `options` to `optionsAddItem`, so it appears to be the same role="listbox".
