### ISSUE TITLE
Remove all caps text from the library

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1601]
Changes:

Component | New Styles | Current Styles | Change Log | Requires Markup Change
-- | -- | -- | -- | --
Badge | 12px/title-case/bold | 10px/caps | CSS: font-size, font-weight, removed uppercase | No
Breadcrumbs | 13px/title-case/bold | 13px/caps | HTML: Removed .slds-text-title_caps CSS: added font-weight: bold | Yes
Combobox | 14px/title-case/bold | 12px/caps | HTML: Removed .slds-text-title_caps, added .slds-listbox__option-header | Yes
Data Table | 13px/title-case/bold | 12px/caps | HTML: Removed .slds-text-title_caps CSS: added font-weight: bold to `thead th` | Yes
Dynamic Menu | 14px/title-case/bold | 12px/caps | HTML: Removed .slds-text-title_caps CSS: Added .slds-dynamic-menu__header | Yes
Global Header | 14px/title-case/bold | 12px/caps | HTML: Removed .slds-text-title_caps CSS: Added styles to .slds-dropdown__header | Yes
List Builder | 13px/title-case/bold | 12px/caps | Same as data table | Yes
Path | 14px/title-case/bold | 12px/caps | CSS: .slds-path__coach-title - removed uppercase, changed font-size and added font-weight: bold | No
Popovers (Panels) | 14px/title-case/bold | 12px/caps | HTML: Removed .slds-text-title_caps CSS: Added .slds-popover_panel__label | Yes
Splitview | 14px/title-case/bold | 12px/caps | HTML: Removed .slds-text-title_caps. CSS: Added text-title mixin and line height heading to .slds-split-view__list-header | Yes
Trees | 14px/title-case/bold | 12px/caps | HTML: Removed .slds-text-title_caps CSS: Added .slds-tree__group-header | Yes
Vertical Nav | 16px/title-case/bold | 12px/caps | HTML: Removed .slds-text-title_caps. CSS: Added text-title mixin to .slds-nav-vertical__title and added extra right padding to .slds-nav-vertical__action. | Yes

**Comment by tanhengyeow** [comment]
Hi @interactivellama 

I've made changes for those styles I could find. Here are my observations for the remaining.

Components not implemented in DSR yet:
1. Dynamic Menu
2. List Builder

Components with no traces of `.slds-text-title_caps` as of latest commit:
1. Global Header
2. Popovers (Panels)

**Comment by interactivellama** [comment]
The general looks correct. I'll put it on my backlog to review.

**Comment by interactivellama** [comment]
When making styles changes components, it's best to review what they look like on the SLDS website, and not just follow the task present in the issue. For instance, tree has an additional classname of `'slds-tree__group-header'` added to it now to make it bold.

In writing the issue, I did make the assumption what it would be checked against the SDLS website such as https://www.lightningdesignsystem.com/components/trees/

**Comment by tanhengyeow** [comment]
Noted! Seemed like you have already pushed some commits to fix this, will keep this in mind in the future 😄
