### ISSUE TITLE
Allow to style slds-split-view_container width

### ISSUE THREAD

**Issue by Niondir** [salesforce/design-system-react#1607]
I'm having a SplitView where the right side takes up to much space, I would like to fix the size of the MasterView.

Currently it's not possible to set the width or minWidth:
```
<div
	style={{
		maxWidth: this.state.isOpen ? this.props.masterWidth : '0',
	}}
	className={classNames(
		'slds-split-view_container',
		{ 'slds-is-open': this.state.isOpen },
		{ 'slds-is-closed': !this.state.isOpen }
	)}
>
```

**Comment by interactivellama** [comment]
Sounds good! We've already got a style tag in there anyway. 

Does a general `style` tag object that gets merged after `maxWidth` work for you? Maybe `styleMasterContainer`?

**Comment by Niondir** [comment]
I guess the merge tag would do the job.

**Comment by interactivellama** [comment]
Please pull request:
```
		/**
		 * Custom styles to be passed to the `slds-split-view_container` element.
		 */
		styleMasterContainer: PropTypes.object,
```
if you would like to see that.
