### ISSUE TITLE
Modal Component triggers children buttons

### ISSUE THREAD

**Issue by albertxhani** [salesforce/design-system-react#1617]
This is a bug on the <Modal> Component

When a modal has buttons for children, and on opening and closing the Modal all the Buttons will be triggered
but when clicking the buttons after the modal is opened nothing gets trigered

Consider this : 
`
<Modal isOpen={this.state.isOpen} dismissible={false} title="Modal">
     <Button id="test3" label="TEST5" variant="brand" onClick={alert("test button")} />
</Modal>
`

**Comment by interactivellama** [comment]
Did this get resolved? If it's a documentation clarity issue, please modify Prop description via their comments https://github.com/salesforce/design-system-react/blob/master/components/modal/index.jsx#L34 if that applicable.
