### ISSUE TITLE
Populating Combobox from State/Props does not filter out already selected options

### ISSUE THREAD

**Issue by michaelcavallaro03** [salesforce/design-system-react#1625]
Discovered this working on a SPA, 

When loading the selections from props or from a redux store, in my case, the already selected options appear as pills (as expected), however you should notice that the already option is still showing up on the search results. This is not expected and leads to another bug with adding multiple of the same option, removing one of these duplicates will remove both.

After digging deeper, I believe this feature could be implemented nicely in `components/combobox/filter.js`

I can begin working on a PR for this if there is value.

**Comment by interactivellama** [comment]
As to removing already selected options from the options list, I'd totally love to see that. If there is a bug in this line https://github.com/salesforce/design-system-react/blob/master/components/combobox/filter.js#L15-L16 please fix, duplicates of selected options should not be showing up on the `options` menu list when the filter is used correctly.

**Comment by michaelcavallaro03** [comment]
>  duplicates of selected options should not be showing up on the `options` menu list when the options are passed through `filter`. 

I think I phrased the issue poorly. When loading the page in a SPA from Redux store (props), the combobox displays the pills appropriately. However, those pills should not still show up in the options dropdown (unless there are duplicates in the inputted `options`). In this scenario, since there now exists a pill for the option AND the option still appears in the dropdown when you select that option a second pill appears. I believe that by just fixing the already selected options will auto correct this. 

I will begin working on this!
