### ISSUE TITLE
Input Icon misaligned when inlineHelpText set

### ISSUE THREAD

**Issue by mlilley** [salesforce/design-system-react#1631]
**Version:**

0.9.0

**Example:**

```
<SLDSInput
  id="field-label"
  label="Label"
  inlineHelpText={"Label Help Text"}
  iconRight={<InputIcon name="warning" category="utility" color="warning"/>}
  value={this.state.label}
  required
/>
```

**Results In:**

Misaligned icon - positioned at or off bottom edge of input.

> ![screen shot 2018-10-29 at 5 53 05 pm](https://user-images.githubusercontent.com/20426/47688621-88701880-dba3-11e8-86bb-9d39e46e0b9b.png)

The output html:

> ![screen shot 2018-10-29 at 5 55 14 pm](https://user-images.githubusercontent.com/20426/47688762-1815c700-dba4-11e8-82af-b24a4b6a1d90.png)

causes the icon to be positioned at 50% of the combined height of both the input and help text, instead of the input height alone.  The problem is exacerbated when the help text wraps to more than one line:

> ![screen shot 2018-10-29 at 5 46 39 pm](https://user-images.githubusercontent.com/20426/47688641-902fbd00-dba3-11e8-8085-fa4f4fc59053.png)

(I'm not working on a solution to this issue).

**Comment by interactivellama** [comment]
This looks like a bug in SLDS or at least a pattern that isn't currently supported. I couldn't get it to work with static SLDS HTML. The icon is positioned at 50% on the SLDS website https://lightningdesignsystem.com/components/input/

I would recommend filing a bug here: https://github.com/salesforce-ux/design-system/issues
