### ISSUE TITLE
Allow aria-* attributes on form elements

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1636]
Related to #1635. Allows `aria-*` attributes on all `input` form elements and increases flexibility of accessibility.

## Enable engineering use
See dataProps [architecture here](https://github.com/salesforce/design-system-react/pull/1585/files#diff-42d10394155c1e14e7d8faf1a52dfb97R112).
* ~Input~
* ~Button~
* Radio
* ~Checkbox~
* Colorpicker (input)
* Combobox
* Date Picker
* ~Text-area~
* Slider

Button has this working. I'm not sure why some of these are striked through.

## Highlight implied prop on doc site

Add to comment paragraph above class declaration:

> This component contains an `input` element. Any prop starting with `aria` will be added to `input` even though `aria-*` props are not listed below.

**Comment by interactivellama** [comment]
See #1706 for implementation.

**Comment by shleewhite** [comment]
@interactivellama I can work on this!

**Comment by interactivellama** [comment]
I honestly don't remember by striked those out. Please audit all components with `input` elements. There could be some newly added. Sorry, for the out of date issue.

**Comment by shleewhite** [comment]
@interactivellama HTML input or the DSR input?

**Comment by interactivellama** [comment]
HTML `<input/>`
