### ISSUE TITLE
Console message should talk about updating Jest tests when snapshots fail

### ISSUE THREAD

**Issue by kevinparkerson** [salesforce/design-system-react#1642]
I recently ran into an issue where snapshots were failing, and it wasn't super clear how to fix that problem. The docs have `npm run test:snapshot -- -u` listed as a single bullet point on an relatively large page of information so it's easy to miss. A warning message mentioning that command upon snapshot test failure could be very helpful, though the message should also make it clear that command should only be run if in fact changes have occurred to modify behavior in components where the snapshots change.

Additionally, if there are id conflicts in the snapshots, the warning could help point to how to correct that too. The docs mention every example needs to have a set id or the generated ids will cause snapshot conflicts, but that information can be easily missed.

**Comment by interactivellama** [comment]
`npm run test:snapshot:update` has been added. @kevinparkerson Feel free to re-open if you'd still like to add this feature.
