### ISSUE TITLE
Enabling multiple selection of Combobox before dropdown closes

### ISSUE THREAD

**Issue by Cavallando** [salesforce/design-system-react#1652]
###  Better Multiple Select Functionality

In our implementation of SLDS we have users that are often making a large number of selections from a large lists using the combobox component. From a UX perspective, it would be great to allow the user to make multiple selections (when enabled) before the Dropdown closes. 

I was thinking a key modifier could work for this scenario similar to how it works on a file directory. In the file directory example if the user is holding CTRL(Windows) or Command (Mac) they're able to make multiple selections. 

In this scenario, the user would do the similar operation. If this new prop is enabled, then upon release of the modifying key, the dropdown would close with the selected options.

If this is seen as useful, I would be happy to start working on it. However, I'm sure it requires further discussion.

**Comment by interactivellama** [comment]
I think there is an implicit close when clicked expected UX pattern when a dropdown is used. I'd be open to doing something "hacky" that you control the menu with the `isOpen` prop yourself through `onRequestOpen/onRequestClose` and ignore close requests when the user clicks inside the menu, but do close when clicked outside or `Esc` or `tab`. (which are the only other ways I know of to close the menu)

*Short version:* if you want to propose event props that allow you to do this if you currently can't--I'm open to it, but I'd prefer to not make it a suggested, common pattern such as `noCloseOnItemClick: true`. You should probably explore `isOpen` use with `onSelect`, you might be able to currently do this.

That said, a dropdown might not be the best component to use. Would a [Dueling Picklist](https://lightningdesignsystem.com/components/dueling-picklist/) work better? It doesn't have the auto complete, but it seems like your use case if mostly mouse and up/down arrow focused. It's not currently in the library, but someone is working on it internally over the next few months, if you want to use that when it becomes available. I do not have a date right now though.

**Comment by michaelcavallaro03** [comment]
I completely agree with the implicit UX pattern. Just an edge case that we saw as an improvement for our specific implementation. 

I do not believe PickList is the best option for our implementation, but worth exploring. 

You’re suggestion makes a lot of sense, I’ll take a look at it this weekend and update on what solution I can find. Thanks for your help!

**Comment by interactivellama** [comment]
@michaelcavallaro03 There's a [Dialog Combobox](https://www.lightningdesignsystem.com/components/combobox/#Combobox-with-a-Dialog) in the works 

https://design-system-react-co-pr-1735.herokuapp.com/?selectedKind=SLDSCombobox&selectedStory=Dialog&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
