### ISSUE TITLE
Panel needs more props

### ISSUE THREAD

**Issue by futuremint** [salesforce/design-system-react#1672]
I will flesh out this issue description later, but current the panel's props don't support all of the options for the actual Panel.

The example I need is "left side docked" for example: https://lightningdesignsystem.com/components/panels/#Left-side

However there are a few more.  I think just having a `className` prop to put on the root div of the component would be sufficient for now.

**Comment by tanhengyeow** [comment]
@futuremint Hi! Nice to meet you :) Are you currently working on adding more props for the `Panel` component? If not, I'm happy to go ahead and help to expose the other props :)

**Comment by tanhengyeow** [comment]
Working on it :)

**Comment by pulkonet** [comment]
I am willing to add the remaining props here. @tanhengyeow Are you still working on it? If not, please let me know.
