### ISSUE TITLE
Add fieldLevelHelpTooltip prop on combobox

### ISSUE THREAD

**Issue by davidlygagnon** [salesforce/design-system-react#1681]
Allow consumers of Combobox component the ability to add a Tooltip component (info icon in screenshot) next to the label.

Prop name proposition:

`fieldLevelHelpTooltip: PropTypes.node`

![screen shot 2018-12-07 at 3 15 48 pm](https://user-images.githubusercontent.com/1821787/49752155-610d7080-fc64-11e8-8851-915dd2e61b47.png)

Assigned to myself - I'll work on it.

**Comment by interactivellama** [comment]
Sounds good! Please proceed.
