### ISSUE TITLE
Row selection header not aligned

### ISSUE THREAD

**Issue by Niondir** [salesforce/design-system-react#1685]
Just noticed that the checkbox in the header row is not aligned with the table rows.

Looking at: https://www.lightningdesignsystem.com/components/data-tables/#site-main-content -> Responsive

The header checkbox is not wrapped in a `<div className="slds-th__action slds-th__action--form">` as it is in the react component `head.jsx`.

**Comment by interactivellama** [comment]
This appears to have been fixed now. https://react.lightningdesignsystem.com/components/data-table/

Please re-open if it isn't @Niondir
