### ISSUE TITLE
Add Select component

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1691]
Add Select component https://www.lightningdesignsystem.com/components/select/

Please include the following within the component comments:

Select element presents a menu of options. This component and its multiple selection variant should only be limited to usage on touch devices. Combobox Read-Only Single Select (Picklist) and Dueling Picklist should be used for non-touch devices.

**Comment by tanhengyeow** [comment]
Hi @interactivellama 

This seems interesting to work on. However, it seems to depend on this [issue](https://github.com/salesforce/design-system-react/issues/1667) to be resolved first. Can I still go ahead and propose the props for this component?

**Comment by tanhengyeow** [comment]
Am currently working on it :)

**Comment by interactivellama** [comment]
There is no dependency on `DuelingPicklist`. The mention of it was just a UX pattern for the comments.
