### ISSUE TITLE
PillContainer: Return null if options is empty

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1694]
Container box should be removed if PillContainer options.length is 0.

The following is the bug that should not occur
<img width="173" alt="screen shot 2018-11-29 at 11 24 27 pm" src="https://user-images.githubusercontent.com/1290832/50235303-2f3f8c80-037d-11e9-90fb-879476fdff6d.png">

**Comment by PUNITBATRA** [comment]
@interactivellama Hi I want to work on this issue.Please assign me this issue.

**Comment by thobhanifreddy** [comment]
can I fix this?
