### ISSUE TITLE
Expression: Props proposal

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1695]
Expression builders help users declaratively construct logical expressions. These expressions can be used when querying for a filtered set of records, creating rules to control when something executes, or any other conditional logic.

https://www.lightningdesignsystem.com/components/expression/

**Comment by fezheng397** [comment]
@interactivellama I'd love to work on this component, I should have a props proposition by tomorrow night.

**Comment by devgopesh** [comment]
I would like to work on this component.

**Comment by interactivellama** [comment]
Sorry, I've been triaging mostly pull requests this past week. This is a large component. One way to get started is to make sure we have all the subcomponents that are needed and making a list of those here and creating another issue and linking it here. 

The final output from an API standpoint is eventually like an SQL query such as `x AND y OR z`, but we can't define the syntax for that since we need to be open to a variety of backend technologies.

Filtering Panel is probably the closest component semantic-ly in that it forms a query.
