### ISSUE TITLE
Make Page Header variants name kabob case

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1702]
Page Header variants are currently `objectHome`, `recordHome`, `relatedList` and `base` and should be updated to `object-home`, `record-home`, `related-list` in a backwards compatible way. `checkProps` should be used to notify consumers of prop change.

**Comment by pradumangoyal** [comment]
Hi @interactivellama, Can I work and submit a PR on this issue?

**Comment by interactivellama** [comment]
Yes, please do.

**Comment by pradumangoyal** [comment]
@interactivellama, I have already opened a PR kindly review it.
