### ISSUE TITLE
DataTable Radio button with fixedLayout and fixedHeader is broken

### ISSUE THREAD

**Issue by gzhang86** [salesforce/design-system-react#1708]
With 0.9.3, when creating a single selected radio button DataTable with fixed header:
<DataTable
	fixedLayout
	fixedHeader
	items={...}
	selectRows='radio'
	onRowChange={...}
	selection={...}
>

We are hitting the following in DataTable. resizeFixedHeaders():
```
              var cellFixed = column.querySelector('.slds-cell-fixed');
              var linkFixed = cellFixed.firstChild;

              if (cellFixed) {
                cellFixed.style.left = "".concat(columnLeft - wrapperLeft, "px");
                **linkFixed**.style.width = "".concat(column.offsetWidth, "px");    // linkFixed is null
              }
```

**Comment by interactivellama** [comment]
if (cellFixed) {
    cellFixed.style.left = `${columnLeft - wrapperLeft}px`;
}

if (linkFixed) {
    linkFixed.style.width = `${column.offsetWidth}px`;
}
```

**Comment by davidlygagnon** [comment]
Thanks @interactivellama. I asked him to file this bug because it's preventing us from using > 0.9.2. Let me know if you need me to create the PR for this fix.

**Comment by interactivellama** [comment]
I made one. #1710 Please review.
