### ISSUE TITLE
Page Header: Update props

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1716]
This component some implicit API items in it's props (type checking :-( ), since this component is one of the older ones in the project and needs to align with the architecture of the rest of the project.

#1687 highlights some of the issues and does some needed markup changes.

* Deprecate `contentRight` and `navRight` completely (but keep backwards compatibility) 
* Better name them such as `onRenderActions` and `onRenderControls`
* Variant update #1702

**Comment by ganeshpatro321** [comment]
Hey @interactivellama , I would like to take up this issue, can you please tell me more about the changes needed.
Thank you

**Comment by interactivellama** [comment]
Thank you for asking. We are modifying the cars engine while it is driving. :-)

* Please allow the current API to exist without changes (internal code can be refactored if needed).
* Keep SLDS markup changes from #1687 (or start over). Here is where the current markup came from https://www.lightningdesignsystem.com/components/page-headers/
* Add render props `onRenderActions` and `onRenderControls` which basically do the same thing as `contentRight` and `navRight` but are just better names. These are proptype functions that you just pass a React node into https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#prefix-render-props-with-onrender Here is Combobox `menuItem` for instance, but I don't think these custom rendering passed in from consumers need any extra props from their parent. Please don't use `type !== 'string'` or the props spread `...navRight.props` that you currently see in `page-header/index.js`, but keep those for the existing props.
* Add a `checkProps` call deprecating `contentRight` and `navRight`, so a console warning fires when those are used. An example https://github.com/salesforce/design-system-react/blob/master/components/app-launcher/check-props.js#L27
* Remove `contentRight` and `navRight` from proptypes (which removes them from docs site eventually). You'll need eslint disable rules then.
* #1702 changes the variants names in the proptypes, but allows the old ones to work and should also fire a checkProps console warning deprecated the current values.

**Comment by pradumangoyal** [comment]
Hi @interactivellama, If no one is working on it currently, can I work on this? I have already submitted a PR pending for review on the issue #1702.

**Comment by pradumangoyal** [comment]
@interactivellama, I have pushed some changes on already existing PR on `pageHeader` props  #1832 which resolves this issue with #1702 too. Kindly review it and suggest any changes as required.

**Comment by interactivellama** [comment]
#1832 has been reviewed.

**Comment by interactivellama** [comment]
This should be fixed now.
