### ISSUE TITLE
Add additional stories to snapshot testing

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1733]
Add the following to DOM snapshots, image snapshots, and a11y testing:

* ProgressRing from '../components/progress-ring/__docs__/storybook-stories';
* RadioGroup from '../components/radio-group/__docs__/storybook-stories';
* RadioButtonGroup from '../components/radio-button-group/__docs__/storybook-stories';
* Search from '../components/input/__docs__/search/storybook-stories';
* Slider from '../components/slider/__docs__/storybook-stories';
* SplitView from '../components/split-view/__docs__/storybook-stories';
* Tabs from '../components/tabs/__docs__/storybook-stories';
* Textarea from '../components/textarea/__docs__/storybook-stories';
* Toast from '../components/toast/__docs__/storybook-stories';
* Tooltip from '../components/tooltip/__docs__/storybook-stories';

**Comment by pradumangoyal** [comment]
Hi @interactivellama, I am interested in working on this. Can you guide me through the specificities? If these are to be similar to other snapshots in these directories?

**Comment by devgopesh** [comment]
@pradumangoyal Sorry I didn't mention it but I have been working on it for some time now.I will make a pr related to this shortly.

**Comment by devgopesh** [comment]
@interactivellama I added the ProgressRing to DOM snapshot and make chanes in it which resolves the problem of DOC site examples which were showing an error earlier. Should I make pr for ProgressRing as I  think you can review it and then I can add other components?

**Comment by interactivellama** [comment]
That's sounds like a good plan @devgopesh.

**Comment by interactivellama** [comment]
Fixed by #1987 and #2097.
