### ISSUE TITLE
Add Combobox with Dialog

### ISSUE THREAD

**Issue by shleewhite** [salesforce/design-system-react#1736]
Adding a new variant to `<Combobox />`: combobox with dialog.
https://www.lightningdesignsystem.com/components/combobox/#Combobox-with-a-Dialog

There are some changes to existing props and new props:
```
const propTypes = {
	/**
	 * **Assistive text for accessibility**
	 * This object is merged with the default props object on every render.
	 * * `label`: This is used as a visually hidden label if, no `labels.label` is provided.
	 * * `optionSelectedInMenu`: Added before selected menu items in Read-only variants (Picklists). The default is `Current Selection:`.
	 * * `popoverHeading`: Used by popover variant, assistive text for the Popover heading.
	 * * `removeSingleSelectedOption`: Used by inline-listbox, single-select variant to remove the selected item (pill). This is a button with focus. The default is `Remove selected option`.
	 * * `removePill`: Used by multiple selection Comboboxes to remove a selected item (pill). Focus is on the pill. This is not a button. The default  is `, Press delete or backspace to remove`.
	 * * `selectedListboxLabel`: This is a label for the selected listbox. The grouping of pills for multiple selection Comboboxes. The default is `Selected Options:`.
	 * _Tested with snapshot testing._
	 */
	assistiveText: PropTypes.shape({
		label: PropTypes.string,
		optionSelectedInMenu: PropTypes.string,
		popoverHeading: PropTypes.string,
		removeSingleSelectedOption: PropTypes.string,
		removePill: PropTypes.string,
		selectedListboxLabel: PropTypes.string,
	}),
	/**
	 * Contents of popover. That is the contents of the Combobox's dialog.
	 */
	children: PropTypes.node,
	/**
	 * **Array of item objects in the dropdown menu.**
	 * Each object can contain:
	 * * `icon`: An `Icon` component. (not used in read-only variant)
	 * * `id`: A unique identifier string.
	 * * `label`: A primary string of text for a menu item or group separator.
	 * * `subTitle`: A secondary string of text added for clarity. (optional)
	 * * `type`: 'separator' is the only type currently used
	 * ```
	 * {
	 * 	id: '2',
	 * 	label: 'Salesforce.com, Inc.',
	 * 	subTitle: 'Account • San Francisco',
	 * 	type: 'account',
	 * },
	 * ```
	 * Note: At the moment, Combobox does not support two consecutive separators. _Tested with snapshot testing._
	 */
	options: PropTypes.arrayOf(
		PropTypes.PropTypes.shape({
			id: PropTypes.string.isRequired,
			icon: PropTypes.node,
			label: PropTypes.string,
			subTitle: PropTypes.string,
			type: PropTypes.string,
		})
	),
	/**
	 * Specifies if the combobox is a popover variant.
	 */
	popover: PropTypes.bool,
	/**
	 * Changes styles of the input. Currently `entity` is not supported. _Tested with snapshot testing._
	 */
	variant: PropTypes.oneOf(['base', 'inline-listbox', 'popover', 'readonly']),
}
```

**Comment by shleewhite** [comment]
Totally understand, I used `children` so I could put a hidden label at the top of the body. The dialog needs an `aria-label` or `aria-labelledby` instead of a header. Is there another way I could add the label in?

**Comment by interactivellama** [comment]
Would a Combobox variant of Popover work? You can clone the Popover passed in and have the combobox choose the variant by default. I may not be being very specific though. 

Something like https://github.com/salesforce/design-system-react/blob/master/components/tooltip/private/field-level-help-tooltip.jsx#L31

**Comment by interactivellama** [comment]
@shleewhite I noticed today that the width of popover should match the width of the input.

![Screen Shot 2019-03-13 at 4 37 05 PM](https://user-images.githubusercontent.com/1290832/54319155-440f7300-45ae-11e9-93b0-63bbf110d113.png)

**Comment by shleewhite** [comment]
@interactivellama Sorry for the delayed response! I thought that adding this class `slds-popover_full-width` fixed that. I think I updated the SLDS version on my local branch and the styles worked.

**Comment by interactivellama** [comment]
@shleewhite This is what I'm seeing here: https://design-system-react-co-pr-1735.herokuapp.com/?selectedKind=SLDSCombobox&selectedStory=Snapshot%20Dialog%20Open&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

![Screen Shot 2019-03-18 at 2 40 21 PM](https://user-images.githubusercontent.com/1290832/54562052-c7084300-498b-11e9-9a90-791f42b15322.png)

**Comment by interactivellama** [comment]
Would updating to SLDS to 2.8+ fix this? I'll take a look.

**Comment by shleewhite** [comment]
I think updating to 2.8+ will fix it.
