### ISSUE TITLE
[Button component] variant is ignored when iconVariant is present

### ISSUE THREAD

**Issue by qyiming** [salesforce/design-system-react#1737]
In SLDS button component, 'variant' is not applied if 'iconVariant' is present.

https://react.lightningdesignsystem.com/components/buttons/

For example - 

when `variant` is 'brand' and `iconVariant` is 'border', the search button does not have the brand color, it is

![screen shot 2019-02-06 at 5 43 19 pm](https://user-images.githubusercontent.com/4957585/52385897-81756380-2a38-11e9-8caa-1abbd50c0dbb.png)

whereas I expect it to be have the blue brand, similar to the following

![screen shot 2019-02-06 at 5 47 29 pm](https://user-images.githubusercontent.com/4957585/52385909-8d612580-2a38-11e9-8485-835fbb75ba38.png)

**Comment by interactivellama** [comment]
Please modify the code with your proposal and post a screenshot of what `variant=brand` and `iconVariant=border` look like together. I think it should be fine, but I'll want to see it. Thanks!

**Comment by pradumangoyal** [comment]
If anyone is not working on it, Can I take it up?

**Comment by pradumangoyal** [comment]
Hi @interactivellama , actually `iconVariant` is not ignored. The `brand` option is not present for `iconVariant`. The desired output(Icon button with brand color at background) can be obtained by setting `iconVariant` to `brand`.

![image](https://user-images.githubusercontent.com/34851451/54085133-39f83500-4360-11e9-9441-bbf9cf86e417.png)

The SLDS also have brand in the icon type as shown in the screenshot.

![image](https://user-images.githubusercontent.com/34851451/54085135-411f4300-4360-11e9-8fd2-670d531489ae.png)
