### ISSUE TITLE
Using Dialog with overflowBoundaryElement position can result in broken icons.

### ISSUE THREAD

**Issue by sudowork** [salesforce/design-system-react#1744]
The current implementation of `overflowingBoundaryElement` `Dialog`s recreates IconSettings with only the `iconAssets` prop inherited from the current context. This results in broken icons if any `IconSettings` are set using other props.

I can work on a fix for this.

**Comment by interactivellama** [comment]
Thanks for finding this! Please proceed.

**Comment by sudowork** [comment]
Fixed in #1745
