### ISSUE TITLE
Add Walkthough Popover

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1751]
Walkthrough variant on https://www.lightningdesignsystem.com/components/popovers/

![screen shot 2019-02-15 at 1 31 17 pm](https://user-images.githubusercontent.com/1290832/52882773-fe35cb00-3125-11e9-8d25-e492926a1a22.png)

**Comment by nathanwdavis** [comment]
The primary deficiency in the current version of the React component is that it seems to affect the layout of the elements it wraps (it's `children`). Additionally, I get warnings that the children components must be an SLDSButton or other clickable. In the case of a walkthrough it is not some clickable that opens the popover, but rather it is controlled by an FTUX state.

I would imagine that it could be helpful to have a `variant` prop with "walkthrough" as one of the options. When it is walkthrough, it should allow for walkthrough type behavior.

**Comment by interactivellama** [comment]
@nathanwdavis My 5 min estimate is to suggest the child still be an interactive item (Button, etc.) that would still receive focus on closure of the Popover and that you also add a positioning element (DOM ref callback or DOM query) that would get sent to Popover/Dialog for positioning and be used by Popper.JS to position the Walkthrough where ever you want on the page.

@futuremint

**Comment by kevinparkerson** [comment]
New PropTypes proposal:
```
/**
 * Used with `walkthrough` variant to provide action buttons (ex: "Next" / "Skip" / etc) for a walkthrough popover footer. Accepts either a single node or array of nodes for multiple buttons.
 */
footerActions: PropTypes.oneOfType([PropTypes.node, PropTypes.arrayOf(PropTypes.node)]),
/**
 * Used with `walkthrough` variant to provide the step text (ex: "Step 1 of 4") for a walkthrough popover footer.
 */
stepText: PropTypes.string,
/**
 * Causes the popover to attach itself next to the provided element when open. If not provided the popover will use the triggering element as the attachment target instead.
 */
target: PropTypes.node,
/**
 * Controls the variant of popover to be displayed, which have different styling and complimentary features
 */
variant: PropTypes.oneOf(['walkthrough', 'walkthrough-action'])

/* NOTE: there are already other variants in the works; this is just showing the ones that I will add for this task */
```

**Comment by interactivellama** [comment]
I'm wondering if we are going to need some kind of weird offset or exposing some of the Popper.JS API, we can always cross that river when we need to and for right now assume folks only want to center/top/bottom align items.

**Comment by kevinparkerson** [comment]
Offset will likely be needed at some point, but I agree we should keep it simple for now and only add that on request later.

**Comment by interactivellama** [comment]
I've updated target to `onRequestTargetElement`. The underlying function is a callback and the initial code a reviewed didn't handle refs for buttons that rendered after the popover.
