### ISSUE TITLE
Dropdown: Hover in accessible with keyboard

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1761]
This may be obvious, but the `openOn: hover` prop makes the dropdown keyboard inaccessible. http://design-system-react-components.herokuapp.com/?selectedKind=SLDSMenuDropdown&selectedStory=Hover&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by tanhengyeow** [comment]
Hi @interactivellama

Have been working on some `menu-dropdown` issues lately and would be interested to work on this next :) Just to check that we are on the same page, work for this is to make sure that when `this.props.openOn === 'hover'`, the `Dropdown` component is still keyboard accessible, am I right?

Do you have anything in mind that you want me to try out?

**Comment by interactivellama** [comment]
Yes, that is correct. Pressing enter on the trigger should still open the menu and esc should still close.

It is OK to assume that the user is not using the mouse AND the keyboard. That is if the user opens with the mouse, closing with the mouse is fine OR if they user opens with the keyboard you can force them to close with the keyboard and not the mouse. 

The success criteria is the dropdown functions like it normally does enter/esc/up+down on menu/ etc and has the added functionality of opening when the button is hovered on and closes when hovered off.
