### ISSUE TITLE
Update Input Example with Error Icon to New Error Icon (Circle with /)

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#1770]
The error icon shown in the example below is incorrect. It should be the red circle with a / through it.

![image](https://user-images.githubusercontent.com/42620858/53527471-0d693100-3ab5-11e9-8013-200a7a57345e.png)

This screenshot is from https://react.lightningdesignsystem.com/components/inputs/. An example of the proper error icon can be found at https://latest-220.lightningdesignsystem.com/components/input/.

**Comment by thobhanifreddy** [comment]
This looks like a quick fix. Can I do this?

**Comment by interactivellama** [comment]
Yes.
