### ISSUE TITLE
Support for icons & labels in Progress Indicator

### ISSUE THREAD

**Issue by aswinshenoy** [salesforce/design-system-react#1771]
The current progress indicator component does not allow to customize the icon in each step. The user needs to hover the indicator to understand what the step is about.  

![image](https://user-images.githubusercontent.com/21276922/53543205-dee86600-3b47-11e9-83cb-aff7ea270f59.png)

**Proposed Implementation**
In the```steps``` property of the component, I propose we should add an optional support for icon and text, which will allow the progress indicator to be displayed like the following -
![image](https://user-images.githubusercontent.com/21276922/53542757-f161a000-3b45-11e9-95f1-f1daade887d3.png)

```
The step property should be taking 2 extra parameters - icon, showText
 [{
   id: <PropTypes.number> or <PropTypes.string>, has to be unique
   label: <PropTypes.string>, representing the tooltip content
   assistiveText: <PropTypes.string>, The default is `[Step props.index + 1]: [status]`. Status is if the step has been completed or in an error state.
   icon: <PropTypes.string>, name of LDS icon
   showText: <PropTypes.bool>, whether to show or hide label in the progress Indicator
 }],
```

**Comment by interactivellama** [comment]
This library is an implementation of https://github.com/salesforce-ux/design-system . You want to make UX pattern suggestion there.

**Comment by interactivellama** [comment]
This page may be helpful too for contextual usage such as for a modal footer. https://lightningdesignsystem.com/components/progress-indicator/
