### ISSUE TITLE
Move Storyshot Snapshots to individual files

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1775]
Update DOM snapshots to use single files. Our current file is 63000+ lines
```
import initStoryshots, {
	imageSnapshot,
	multiSnapshotWithOptions,
} from '@storybook/addon-storyshots';

initStoryshots({
	configPath: '.storybook-based-tests',
	storyNameRegex: new RegExp(`^((?!.*?(${skipStoryshotTest})).)*$`, 'g'),
	suite: 'DOM snapshots',
	integrityOptions: { cwd: __dirname }, // start searching from the current directory
	test: multiSnapshotWithOptions({}),
});

```

**Comment by zamhaq** [comment]
@interactivellama please assign the issue to me.

**Comment by interactivellama** [comment]
I can't assign it to you unless you are in the Salesforce org. You can take over my pull request and I can close mine if you'd like.

**Comment by interactivellama** [comment]
@zamhaq I haven't heard from you in a while. I'm going to take this one back. I think it will help with pull request conflicts
