### ISSUE TITLE
`package-lock.json` is out of sync

### ISSUE THREAD

**Issue by pradumangoyal** [salesforce/design-system-react#1808]
On freshly installing the npm packages, the `package-lock.json` get out of sync and deviated from git history.

![image](https://user-images.githubusercontent.com/34851451/53912527-20649e00-407f-11e9-86c9-d505183c491f.png)

**Comment by interactivellama** [comment]
I did a fresh install and did not get this issue. Please share how to duplicate.

![Screen Shot 2019-03-13 at 1 21 44 AM](https://user-images.githubusercontent.com/1290832/54260407-69f53300-452e-11e9-92a0-a8bf9cd3fda9.png)

Could it be a windows only issue?

**Comment by pradumangoyal** [comment]
Hey @interactivellama, I think the file is synced again in the [commit](https://github.com/salesforce/design-system-react/commit/5de632294c1eefa676b029c2f2fcbf78c9b88774#diff-32607347f8126e6534ebc7ebaec4853d) that was added after the opening of this issue. So, I am closing this issue.

**Comment by interactivellama** [comment]
Great! Thanks for following up.
