### ISSUE TITLE
Condition 'props.hasSpinner' is always true at line 307 components/input/private/inner-input.jsx

### ISSUE THREAD

**Issue by ashwaniYDV** [salesforce/design-system-react#1815]
{props.hasSpinner ? (
				<div className="slds-input__icon-group slds-input__icon-group_right">
					{props.hasSpinner && (
						<Spinner......

**Comment by thobhanifreddy** [comment]
Can you please add the line 307 link here? It will be easier to locate it that way. Just click on line number and it will create a link. Also if possible can you be more descriptive explaining why it's a bug.

**Comment by pradumangoyal** [comment]
I think it's not a bug, it's just double checking the `props.hasSpinner` bool which is not needed.

https://github.com/salesforce/design-system-react/pull/1816/commits/fee763f552a5d11aa962b3333bdbf18d9013071e#diff-c6e3dd62aa113aeceae5ee6af3765792L307

**Comment by ashwaniYDV** [comment]
@pradumangoyal I've got this issue in the link for good first issue, so i thought i could do it. But I'm convinced from you that it's just a double check.

**Comment by interactivellama** [comment]
Yeah, we can remove this. I'm guessing the original coder was thinking about having spinner and iconRight present at the same time and just worked on the render from the child to the parent.
