### ISSUE TITLE
Clicking on the scrollbar of a combobox closes the menu when embedded inside a modal

### ISSUE THREAD

**Issue by Prophetess** [salesforce/design-system-react#1818]
To reproduce this issue, render a Combobox inside a Modal and have a long list of items in the Combobox so that it scrolls.  Use the mouse to select the thumb of the scrollbar and notice the Combobox menu closes before the user can scroll.

**Comment by interactivellama** [comment]
This may be an issue with how react-onclickoutside works. One option to consider is having modal set a context that gets accessed by the react-onclickoutside HOC (see `combobox/index.js`) and allows the Combobox to know it's inside a Modal.

Do you know if this is an issue in `Dropdown`, too?

**Comment by Prophetess** [comment]
@interactivellama I don't believe it has to do with onclickoutside because the blur is the cause of the menu closing.  I haven't checked the behavior of Dropdown.  I created https://github.com/salesforce/design-system-react/pull/1819 that potentially fixes the issue.

**Comment by interactivellama** [comment]
Got it. I misunderstood.
