### ISSUE TITLE
Combobox issue

### ISSUE THREAD

**Issue by asifkabani** [salesforce/design-system-react#1822]
Hi I am implementing the Combobox component and added the property for singleInputDisabled but it does not disable the input.

**Comment by interactivellama** [comment]
It should only disabled the read only variant and and inline listbox. Is that missing from the docs?

**Comment by asifkabani** [comment]
Yes variant is set to readonly

**Comment by interactivellama** [comment]
https://react.lightningdesignsystem.com/components/comboboxes/#examples

It's working for me.

<img width="1070" alt="Screen Shot 2019-03-13 at 10 58 38 PM" src="https://user-images.githubusercontent.com/1290832/54332398-9b7c0600-45e3-11e9-8d0a-c9570c6d733a.png">

<img width="569" alt="Screen Shot 2019-03-13 at 10 58 45 PM" src="https://user-images.githubusercontent.com/1290832/54332399-a0d95080-45e3-11e9-9991-c07d4283bace.png">

Please provide how to duplicate and re-open. Thanks!

**Comment by interactivellama** [comment]
Is it not working for multiple select read only?
