### ISSUE TITLE
GSoC 2019 Communication

### ISSUE THREAD

**Issue by sharaththegeek** [salesforce/design-system-react#1834]
Not an Issue but I am not able to reach out anyplace else.
I am Sharath, student from India, interested in this project under Salesforce for GSoC. I would like to work on the topic- "Development of new Lightning Design System components".

Trying to connect with @futuremint and @interactivellama on Twitter to find out a communication forum where we can exchange ideas further. Looking to hear back soon.

**Comment by rmeena840** [comment]
@sharaththegeek I am also GSoC aspirant. I am trying my best to get in touch with a mentor and I have also not found the communication forum for the same.

**Comment by futuremint** [comment]
Please open issues in our GSoC repo per the README that we've created for Salesforce -> https://github.com/salesforce/gsoc

Thanks.
