### ISSUE TITLE
Content overlap with Background-color on homepage

### ISSUE THREAD

**Issue by kunalvishnoi** [salesforce/design-system-react#1839]
**Problem:** 
The main hero section content overlaps with background colour in mobile view
**Screenshot:**

![Screenshot_2019-03-12-23-10-38-477_com android chrome](https://user-images.githubusercontent.com/24695316/54222963-7f616180-451c-11e9-8b4a-e0a40e71865f.png)

**Normal Behaviour**
The text should only be in blue portion as background colour and font colour is same i.e white

**Conclusion**
I would like to fix the issue allow me to make a PR for the same.

**Comment by interactivellama** [comment]
@kunalvishnoi The documentation website is unfortunately not open source, so there's not an easy way to allow you to fix it. I'll make a note of it. Thank you!
