### ISSUE TITLE
Button Overlap in Alert Example in the Storybook

### ISSUE THREAD

**Issue by sharaththegeek** [salesforce/design-system-react#1840]
For SLDSAlert -> Close Alert in the Storybook, the "Toggle Alert" Button is overlapped when the alert appears. This makes it look clumsy and intrusive as the same button also serves the function of dismissing the alert. 

While this is not a performance issue or not something that would affect practical usage while using the Lightning Design System, I believe that since this is a design project, it is necessary to reflect our core commitment of clean user interfaces, no matter how insignificant the location is. :) 

<img width="1436" alt="Screenshot 2019-03-13 at 8 14 46 PM" src="https://user-images.githubusercontent.com/33923577/54287959-a8d9c600-45cc-11e9-8f33-116318ac3390.png">

**Comment by sharaththegeek** [comment]
Need some help with #1841 
Can someone help me identify why Travis CI failed. I am not able to figure it out.

**Comment by abhinavsagar** [comment]
@sharaththegeek You are overwriting `dev:true` at multiple places that's why travis CI is not able to recognize it.

**Comment by sharaththegeek** [comment]
@abhinavsagar I removed the package-lock.json file from the fork and replaced it with the clean default. It still fails. 

I have no idea why dev:true was overwritten in the first place. Any opinions on how it occurred?
