### ISSUE TITLE
ButtonStateful Design Decisions

### ISSUE THREAD

**Issue by sharaththegeek** [salesforce/design-system-react#1842]
In the ButtonStateful Components (under SDLSButtonStateful->Doc Site Icon Text Button), I found a button with a surrounding dark blue background. It changes to 'Member' when clicked. 

Firstly, the dark blue background surrounding the button seems to be deviating away from giving the component a 'modern' feel.
<img width="127" alt="Screenshot 2019-03-13 at 9 15 06 PM" src="https://user-images.githubusercontent.com/33923577/54293265-a5970800-45d5-11e9-8e36-f0cdfad40bb3.png">

I think it definitely needs some rework.

Secondly, after clicking 'Join', when the 'Member' appears, the text seems unreadable because of similar text and background color. A different combination of colors would make it more viewable.

<img width="150" alt="Screenshot 2019-03-13 at 9 15 20 PM" src="https://user-images.githubusercontent.com/33923577/54293349-cfe8c580-45d5-11e9-9659-1ee7fb54539e.png">

@interactivellama @futuremint Please suggest some background color/text color alternatives. I just want to know if there is some restriction in the choice of colors that I need to stick to, in order to adhere to the Salesforce theme. I will work on it once we conclude on an opinion.

**Comment by interactivellama** [comment]
I think they current style complies with the specifications from https://www.lightningdesignsystem.com/components/buttons/#Selected-with-Hover-State which has a transparent button background when selected.

One option is that we could change the color of the example to be a medium gray such as `#ededed`

**Comment by sharaththegeek** [comment]
Yes, medium gray looks good. 
Will work on it and let you know. :)
