### ISSUE TITLE
Unable to install it on windows

### ISSUE THREAD

**Issue by abhinavsagar** [salesforce/design-system-react#1851]
I am on windows 10 64 .
After doing `npm install`, I am getting the following error `npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Win 10\Desktop\github\design-system-react\node_modules\@salesforce-ux\design-system' -> 'C:\Users\Win 10\Desktop\github\design-system-react\node_modules\@salesforce-ux\.design-system.DELETE'`.

**Comment by interactivellama** [comment]
This may be an issue with SLDS. Have you filed an issue over at https://github.com/salesforce-ux/design-system ?
