### ISSUE TITLE
Dismissable SLDSAlert doesnot close

### ISSUE THREAD

**Issue by nik72619c** [salesforce/design-system-react#1864]
Type of issue: Bug

## How to duplicate a bug?
1. Inside the SLDSAlert Section visit Dismissable Alert 
2. Try to close the alert box

**Comment by interactivellama** [comment]
You can hook up the example to remove the Alert if you want. The website is not public, but all the examples can be found here https://github.com/salesforce/design-system-react/blob/master/components/alert/__docs__/site-stories.js#L11

**Comment by nik72619c** [comment]
So shall I work on it to add the functionality or remove the component then?

**Comment by interactivellama** [comment]
By "remove", I mean "not render". Closing the alert when mean not rendering the alert. Does that make sense?

**Comment by nik72619c** [comment]
Yup
