### ISSUE TITLE
Add inverse variant to `Avatar`

### ISSUE THREAD

**Issue by pradumangoyal** [salesforce/design-system-react#1869]
@interactivellama, inverse `variant` is not present at the present stage. I am adding this according to https://lightningdesignsystem.com/components/avatar/?modifiers=inversed&variant=initials. Basically, I am proceeding by adding a bool prop `inverse` in the avatar whose value will add className `slds-avatar__initials_inverse` according to it. Please guide if there are any further things you have planned on it.

**Comment by interactivellama** [comment]
This looks good. I will review.
