### ISSUE TITLE
Remove All Caps Tree Heading

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#1871]
SLDS has removed the ALL CAPS Tree heading to support localization. The h4 "slds-text-title_caps" class has been replaced with "slds-tree__group-header".

Image below from https://www.lightningdesignsystem.com/components/trees/.

![image](https://user-images.githubusercontent.com/42620858/55102681-581e9e80-509d-11e9-9c54-0b59dd1141a8.png)

**Comment by interactivellama** [comment]
This has been fixed by @tanhengyeow 

Unreleased Tree component example
http://design-system-react-components.herokuapp.com/?selectedKind=SLDSTree&selectedStory=Base&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
