### ISSUE TITLE
CSS not available for className `slds-button_text-destructive` and some other classes

### ISSUE THREAD

**Issue by pradumangoyal** [salesforce/design-system-react#1874]
![className_missing](https://user-images.githubusercontent.com/34851451/55111255-03603f80-5100-11e9-9dfe-51e51bd1dd9f.png)

@interactivellama I encountered this issue when I was trying to add `text-destructive` variant in the `Button` element as seen in the screenshot the required className is not present in the CSS file. I have seen this problem at some other places too which I will report shortly.

**Comment by pradumangoyal** [comment]
`slds-tabs_large` & `slds-tabs_medium` are also not present, due to which `Tabs` size modifiers are unable to function.

![tabs-large-missing](https://user-images.githubusercontent.com/34851451/55124925-07a35180-512e-11e9-9087-42bdcb5747ee.png)
_missing slds-tabs_large_

![tabs-medium-missing](https://user-images.githubusercontent.com/34851451/55124932-0bcf6f00-512e-11e9-9b6c-f234a9d960d6.png)
_missing slds-tabs_medium_

**Comment by pradumangoyal** [comment]
`slds-table_header-hidden` is also not present.

![header-hidden-absent](https://user-images.githubusercontent.com/34851451/55127522-6c62aa00-5136-11e9-9dad-5c8d9b76a163.png)

**Comment by interactivellama** [comment]
@pradumangoyal What version of SLDS are you using? I see `slds-tabs_medium` in 2.8.3.
