### ISSUE TITLE
Add `CheckboxButton` component

### ISSUE THREAD

**Issue by pradumangoyal** [salesforce/design-system-react#1877]
Implement `CheckboxButton` component according to https://lightningdesignsystem.com/components/checkbox-button/

**Comment by pradumangoyal** [comment]
I am working on this and will soon update with the props proposal.

**Comment by interactivellama** [comment]
Is there anything you need from me for the props proposal?

I believe that it would be very close to the checkbox props, but feel free to make it a much smaller subset.
