### ISSUE TITLE
GlobalNavigationBar Base: overlapping list items

### ISSUE THREAD

**Issue by jcjuett** [salesforce/design-system-react#1878]
Bug at this link: https://design-system-react-co-pr-1767.herokuapp.com/?selectedKind=SLDSGlobalNavigationBar&selectedStory=Base&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

HTML: `<li class="slds-context-bar__item slds-is-active"><a href="javascript:void(0);" class="slds-context-bar__label-action"><span class="slds-truncate">Menu Item</span></a></li><li class="slds-context-bar__item"><a href="javascript:void(0);" class="slds-context-bar__label-action"><span class="slds-truncate">Menu Item</span></a></li>`

Success Criteria: Delete fourth and fifth list items to remove visual overlap . On laptop screen the first three items should bump left with no visual overlap from sixth item (Button)

**Comment by devgopesh** [comment]
@jcjuett I have removed the fourth and fifth list item and it looks as
![Screenshot from 2019-03-30 16-15-11](https://user-images.githubusercontent.com/25543114/55275094-05481f80-5307-11e9-825d-336129f421a6.png)

Is it correct?Should I make a pr regarding this or is there something more that need to be understand?

**Comment by interactivellama** [comment]
No, that's all. I have one thing to add though. None of the nav items are selected now. Could you make home or the third item called Menu Item selected. so we have a visual for what is selected.

@devgopesh Thanks for the quick pick up!
