### ISSUE TITLE
Add Files Component

### ISSUE THREAD

**Issue by aswinshenoy** [salesforce/design-system-react#1879]
Implement the Files component according to spec: https://www.lightningdesignsystem.com/components/files/

I am currently working on the same and will post an initial prop proposal soon.

**Comment by aswinshenoy** [comment]
Here is my initial prop proposal for the component, what do you think?

### File
| Name | Type | Description |
|---|---|---|
| ClassName | array/object/string | Additional Class Names |
| placeholder | string | URL to placeholder image. |
| title | string | Title for the file |
| description | string | Description for the link attachment |
| externalIcon | string | URL to external icon |
| type | string ENUM {"image", "pdf" } | File format |
| onClick | string/node | Action/URL to be opened on click |
| downloadURL | string | URL to download file. |
| isLoading | boolean | Whether the file is loading. Defaults false. |

Here are some basic examples using these specs -

```jsx
<div>
<File
    title="Image Title"
    type="image"
    onClick="{...}"
>
<File
    placeholder="..."
    onClick="{...}"
>
<File
    title="Proposal.pdf"
    type="pdf"
    placeholder="..."
    onClick="{...}"
    downloadURL="..."
>
<File
    placeholder="..."
    onClick="{...}"
    downloadURL="..."
>
<File
    title="Proposal.pdf"
    type="pdf"
    onClick="{...}"
   externalIcon="..."
>
<File
    placeholder="..."
    title="Image Title"
    type="image"
    onClick="{...}"
    isLoading
>
<File
    title="Maui By Air The Best Way Around The Island"
    description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt"
    onClick="{...}"
>
</div>
```
Currently doesn't have support for handling multiple files in groups.

**Comment by interactivellama** [comment]
I still need to look at this closer, but my initial thoughts are:

* `externalIcon` and `type` should probably take an `Icon` component. Path should be dealt with there. `icon={<Icon name="audio" />}` should work I think.
* Looking at the spec. it looks like you need a Dropdown menu passed in. Maybe `actionsDropdown`?
* `onClick` should be a function callback

**Comment by interactivellama** [comment]
I will try to get also you additional feedback on Files tomorrow.
