### ISSUE TITLE
Add Setup Assistant Component

### ISSUE THREAD

**Issue by aswinshenoy** [salesforce/design-system-react#1884]
Implement the Setup Assistant component according to spec: https://www.lightningdesignsystem.com/components/setup-assistant/

I am currently working on the same and will post an initial prop proposal soon.

**Comment by interactivellama** [comment]
@aswinshenoy Like Progress Bar and Scoped Notifications--we have an internal need for Setup Assistant and would like get it reviewed and released next week. This internal conversation occurred in the last week. 

I don't want to place a heavy burden on you while you are finishing up semester exams, etc.--please feel completely  open to declining any more work on Setup Assistant if it is not convenient. My apologies for the roadmap change.

How would you like to proceed?

**Comment by interactivellama** [comment]
### Setup Assistant props proposal (draft)

Feedback is welcome!

```
progressBar: <ProgressBar>, // adds header when present
steps: [
  {
  	heading: string, node,
  	description: string, node,
	isExpandable: bool, 
	progressIndicator: <ProgressIndicator variant: setup-assistant (implied/assumed),
		steps: [{
		   id: string // has to be unique due to ids
		   label: string, node // representing the Step label
		   assistiveText: object // same as standard ProgressIndicator
		   setupAssistantEstimatedTime: text, node // NEW! only used in variant: setup-assistant
		   onRenderSetupAssistantAction: button, base button, toggle checkbox, etc. // NEW! only used in variant: setup-assistant
		 }],
		}
 } },
	scopedNotification=<ScopedNotification>
  	isOpen: bool
  }
}
isCard: bool
```

Should be added in #1952
* setupAssistantEstimatedTime: text, node // only used in variant: setup-assistant
* onRenderSetupAssistantAction: button, base button, toggle checkbox, etc.

Maybe add later:
* progressRing: progressRing (optional for complete control, progress indicator should be primary API for steps, but a progress ring prop in steps array might be use for overrides like errors)

**Comment by aswinshenoy** [comment]
@interactivellama I have sent a PR with the work I had done so far, it isn't really ready for a PR but I just pushed it. It supports the base variant, and step progress variant. I have gone through your prop-proposal and will add the missing props and make necessary changes asap.
It's very unfortunate that I have my semester exams starting next week, and so I would be able to put 100% for it :(

**Comment by kevinparkerson** [comment]
@aswinshenoy thank you for what you've submitted! We have a need to get this out soon so I will be finishing up the remaining work for now. Good luck with your exams!!!

**Comment by kevinparkerson** [comment]
example of configuration via a SetupAssistantStep component:
```
<SetupAssistant>
	<SetupAssistantStep
		description="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
		estimatedTime="10 mins"
		heading="Create Profiles for Your Users"
		isExpandable
		isOpen
		progress={64}
		progressIndicator={(
			<ProgressIndicator
				completedSteps={this.state.stepTwoCompletedSubSteps}
				orientation="vertical"
				steps={this.getSubSteps()}
				selectedStep={this.state.stepTwoSelectedSubStep}
				variant="setup-assistant"
			/>
		)}
		scopedNotification={(
			<ScopedNotification theme="light">
				<p>
					It looks as if duplicates exist for this lead.{' '}
					<a href="javascript:void(0);">View Duplicates.</a>
				</p>
			</ScopedNotification>
		)}
	/>
</SetupAssistant>
```

**Comment by kevinparkerson** [comment]
PropTypes for SetupAssistantStep component:
```
const propTypes = {
	/**
	 * Accepts a node to display the step's available action(s). Typically a Button, Button of variant "link," or Checkbox of variant "toggle"
	 */
	action: PropTypes.node,
	/**
	 * Assistive text passed in from the parent setup assistant
	 */
	assistiveText: PropTypes.object,
	/**
	 * CSS class names to be added to the container element. `array`, `object`, or `string` are accepted.
	 */
	className: PropTypes.oneOfType([
		PropTypes.array,
		PropTypes.object,
		PropTypes.string,
	]),
	/**
	 * Detailed description of the step
	 */
	description: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
	/**
	 * Estimated time for completing the step
	 */
	estimatedTime: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
	/**
	 * Heading for the step
	 */
	heading: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
	/**
	 * HTML id for component.
	 */
	id: PropTypes.string,
	/**
	 * Index of the step within the step array
	 */
	index: PropTypes.number,
	/**
	 * Dictates whether the step can be expanded / collapsed
	 */
	isExpandable: PropTypes.bool,
	/**
	 * If `isExpandable` is true, this prop can be used to control the expanded state. If not provided state will be used instead
	 */
	isOpen: PropTypes.bool,
	/**
	 * Function that is called to render step content. If not provided progressIndicator and scopedNotification will be used instead
	 */
	onRenderContent: PropTypes.func,
	/**
	 * Function to handle requests to expand / collapse the step
	 */
	onToggleIsOpen: PropTypes.func,
	/**
	 * Percentage of step completed. No progress indicator will be shown for the step unless this is provided
	 */
	progress: PropTypes.number,
	/**
	 * Accepts a ProgressIndicator component for use in showing sub-steps
	 */
	progressIndicator: PropTypes.node,
	/**
	 * Accepts a ScopedNotification component to display issues or warnings
	 */
	scopedNotification: PropTypes.node,
	/**
	 * Display number for the step. Only appears if progress indicator is enabled
	 */
	stepNumber: PropTypes.number,
};
```

**Comment by interactivellama** [comment]
We also need the scoped notification option above the `ProgressIndicator`.

**Comment by interactivellama** [comment]
@kevinparkerson I wonder if we could use Context to have the `ProgressIndicator` update the ProgressRing to the appropriate number of steps? That would eliminate the need for `progress` prop.

What do you think about that? @garygong

**Comment by kevinparkerson** [comment]
> We also need the scoped notification option above the `ProgressIndicator`.

Weren't we taking care of that via `onRenderContent`?

**Comment by kevinparkerson** [comment]
@interactivellama @garygong the `progress` prop is also what controls visibility of the Progress Ring per step. If the value is undefined, no Progress Ring is rendered. This is to support the base use case of Setup Assistant:

https://www.lightningdesignsystem.com/components/setup-assistant/#Base

If we remove `progress`, we'll need another boolean prop at either the SetupAssistantStep or SetupAssistant level to control whether those rings are visible for the other variants.

I honestly don't think we should manage the progress value ourselves given the fluidity of what can be shown within the step (`onRenderContent` allows for virtually anything the developer wants).
