### ISSUE TITLE
No example for toast closing after a duration under notifications

### ISSUE THREAD

**Issue by pulkonet** [salesforce/design-system-react#1889]
Toasts are alerts that are particularly shown to the user for a limited time. But in the docs under `SLDSNotification`, there is no such example. An example can be added which opens the Toast for, say, 5 seconds and then closes.

I am working on this issue.

**Comment by interactivellama** [comment]
For other folks, the non-deprecated toast can be found at https://react.lightningdesignsystem.com/components/toasts/
and
http://design-system-react-components.herokuapp.com/?selectedKind=SLDSToast&selectedStory=Info&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
