### ISSUE TITLE
Lookup: section items are also being selected onClick

### ISSUE THREAD

**Issue by pulkonet** [salesforce/design-system-react#1900]
Filtered items of type `section` should not be focusable ( ideally ) The functionality is well handled in on key presses and the `section` type filter items don't get focussed. But with the mouse, it is possible to focus on `section` type filter items and even select those.

**Comment by pulkonet** [comment]
It would be a bit more tricky to completely disable the `section` type filter elements, so just making those unselectable would be an improvement. 

I am working on this issue and will submit a PR soon. I would try to disable the element altogether without violating the browser guidelines, though an initial read up tells me it would be tricky.

**Comment by interactivellama** [comment]
@pulkonet Lookup is a deprecated component and is only present in storybook for legacy. As such, no changes will be made to it.

Lookup is not present on the https://react.lightningdesignsystem.com/ . Would there be a better way to tell contributors that it is deprecated?

**Comment by interactivellama** [comment]
The Lookup component is the Combobox: Autocomplete variant. SLDS changes its names from time to time unfortunately.

**Comment by pulkonet** [comment]
@interactivellama I think it would be great if we can add a banner/alert to deprecated components in the storybook. That will warn the contributors in the first place. Or we can have a red mark next to the components name if it is deprecated.  Anyway, it's always fun to fiddle around with the legacy code as well.

**Comment by interactivellama** [comment]
@pulkonet Sounds like a good way to add clarity to the project for contributors. I've created #1921
