### ISSUE TITLE
Add Publishers component from SLDS

### ISSUE THREAD

**Issue by pulkonet** [salesforce/design-system-react#1910]
Add the `Publishers` component from SLDS according to the spec:
https://lightningdesignsystem.com/components/publishers/

I will submit a props proposal soon.

**Comment by pulkonet** [comment]
I shall get this merged

**Comment by pulkonet** [comment]
I shall get this merged

**Comment by garygong** [comment]
@pulkonet Is it ok if we do the `vertical-navigation` component next, instead?  If so, I'll replace this issue with `vertical-navigation` for this eval period.

**Comment by pulkonet** [comment]
Yes, it is completely fine with me.

**Comment by garygong** [comment]
For `vertical-navigation`, it looks like we have the base variant, but we need to modify the props to support the examples listed here:

https://lightningdesignsystem.com/components/vertical-navigation/#Examples

And also, we need to add the Radio Group variant.  Do you want to come up with the props proposal for this? Thanks!

**Comment by pulkonet** [comment]
I will open an issue for it, and add a props proposal. I shall start working on this once I post a working PR for TrialBar though.

**Comment by interactivellama** [comment]
Moving to GSoC Evaluation period two.
