### ISSUE TITLE
SLDSButton:Small Icon Hint inverse: button needs discernible text

### ISSUE THREAD

**Issue by jcjuett** [salesforce/design-system-react#1915]
Bug at this link: http://design-system-react-components.herokuapp.com/?selectedKind=SLDSButton&selectedStory=Small%20Icon%20Hint%20inverse&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Reproduce error: `<button class="slds-button slds-button_icon-border-inverse slds-button_icon-small" type="button"><svg aria-hidden="true" class="slds-button__icon slds-button__icon_inverse-hint"><use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#down"></use></svg></button>`

Success criteria: add `<span class="slds-assistive-text">Dropdown Icon inverse</span>` between final <svg> and </button>
Should read:
`<button class="slds-button slds-button_icon-border-inverse slds-button_icon-small" type="button"><svg aria-hidden="true" class="slds-button__icon slds-button__icon_inverse-hint"><use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#down"></use></svg><span class="slds-assistive-text">Dropdown Icon inverse</span></button>`

**Comment by pulkonet** [comment]
@jcjuett I think this issue is fixed by #1896

**Comment by interactivellama** [comment]
@pulkonet Thanks for the follow up! Yep it's fixed. Two issues fixed. 💯  Closing.
