### ISSUE TITLE
Add visual deprecation heading to deprecated components

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1921]
In response to #1900, this is a suggestion to add deprecation headings to deprecated, so that everyone knows not to touch them.

```
<h3 class="slds-text-heading_medium slds-m-vertical_medium">Deprecated component</h3>
<h4 class="slds-text-heading_small slds-m-vertical_medium">No fit and finish bug fixes will be accepted for this component.</h3>
```

This is my suggestion, but feel free to make the text red or add an icon, etc.

**Comment by pulkonet** [comment]
I will try different ways and post screenshots here, then we can go ahead with either of those.

**Comment by interactivellama** [comment]
Please use both. One for attention getting and one for information clarification

**Comment by pulkonet** [comment]
<img width="1792" alt="Screenshot 2019-04-18 at 10 38 19 PM" src="https://user-images.githubusercontent.com/24983958/56378447-b701ae80-622a-11e9-9bd4-379044390831.png">

The notification is intended for the same exact task, can we use this?

**Comment by interactivellama** [comment]
Notification is a deprecated component. It's use would kind of be ironic. 😄 

`Alert` sounds good though. Is that what you are using?
https://react.lightningdesignsystem.com/components/alerts/

**Comment by pulkonet** [comment]
Yes yes, it is an alert. If it looks good and informative I can push the code.

**Comment by interactivellama** [comment]
Please uses a period instead of a semi colon.

Visual is approved.

**Comment by pulkonet** [comment]
Sure, will do that. Will send a PR soon.
