### ISSUE TITLE
Components Checklist: Exhaustive checklist of components to be added to align DSR with SLDS

### ISSUE THREAD

**Issue by pulkonet** [salesforce/design-system-react#1933]
This is a checklist that can be continually updated to help contributors know the remaining components in SLDS which are yet to be added in DSR. This will also be a reference point for any issues opened / initial pull requests submitted to add the component.

isAdded to DSR | Name | Priority | Issue | PR |
| ------ | ------ | ------ | ------ | ------ |
| <ul><li>- [ ] </li></ul> | Activity Timeline | Medium | #1857 | #1858 |
| <ul><li>- [ ] </li></ul> | App Launcher | High | #1648 | #1767 |
| <ul><li>- [ ] </li></ul> | Avatar Group | High | | |
| <ul><li>- [ ] </li></ul> | Badges | High | | #1805 |
| <ul><li>- [ ] </li></ul> | Builder Header | High | #1850 | |
| <ul><li>- [ ] </li></ul> | Button Groups (list variant) | Medium | | |
| <ul><li>- [ ] </li></ul> | Button Groups (row variant) | High | |
| <ul><li>- [ ] </li></ul> | Cards (Einstein variant) | High | | |
| <ul><li>- [ ] </li></ul> | Cards (wrapper variant) | Medium | | |
| <ul><li>- [ ] </li></ul> | Chat | Low | #1872 | |
| <ul><li>- [ ] </li></ul> | Checkbox Button | Medium | | |
| <ul><li>- [ ] </li></ul> | Combobox (grouped variant) | High | | |
| <ul><li>- [ ] </li></ul> | Combobox (cross-entity / object-switcher variant) | High | #1600 | #1638 |
| <ul><li>- [ ] </li></ul> | Data Table (hidden header variant) | Medium | | |
| <ul><li>- [ ] </li></ul> | Data Table (inline-edit variant) | High | | |
| <ul><li>- [ ] </li></ul> | Data Table (responsive variant) | Medium | | |
| <ul><li>- [ ] </li></ul> | Datepicker (range variant) | High | | |
| <ul><li>- [ ] </li></ul> | Datetime Picker | High | | |
| <ul><li>- [ ] </li></ul> | Docked Composer | Medium | | |
| <ul><li>- [ ] </li></ul> | Docked Form Footer | High | | |
| <ul><li>- [ ] </li></ul> | Docked Utility Bar | Medium | | |
| <ul><li>- [ ] </li></ul> | Dropdown Menu (action-overflow variant) | High | | |
| <ul><li>- [ ] </li></ul> | Dropdown Menu (submenu variant) | Medium | | |
| <ul><li>- [ ] </li></ul> | Drop Zone | High | | |
| <ul><li>- [ ] </li></ul> | Dueling Picklist | High | | #1667 | #1712  |
| <ul><li>- [x] </li></ul> | Dynamic Icons | High | #1359 | #1780 |
| <ul><li>- [ ] </li></ul> | Dynamic Menu | High | | |
| <ul><li>- [ ] </li></ul> | Expandable Section | High | #1361 | |
| <ul><li>- [ ] </li></ul> | Expression | High | #1695 | |
| <ul><li>- [ ] </li></ul> | Feeds | Low | #1882 | |
| <ul><li>- [ ] </li></ul> | File Selector | High | #1880 | |
| <ul><li>- [ ] </li></ul> | Files | High | #1879 | #1929 |
| <ul><li>- [ ] </li></ul> | Form Element | High | | |
| <ul><li>- [ ] </li></ul> | Global Navigation (tab bar variant) | Medium | | |
| <ul><li>- [ ] </li></ul> | List Builder | High | | |
| <ul><li>- [ ] </li></ul> | Map | High | | |
| <ul><li>- [ ] </li></ul> | Page Header (record home vertical variant) | High | | |
| <ul><li>- [ ] </li></ul> | Page Header (related list variant) | High | | |
| <ul><li>- [ ] </li></ul> | Panel | High | | |
| <ul><li>- [ ] </li></ul> | Path | Medium | | |
| <ul><li>- [ ] </li></ul> | Popover (feature variant) | High | | |
| <ul><li>- [ ] </li></ul> | Popover (panel variant) | High | | |
| <ul><li>- [x] </li></ul> | Progress Bar | High | #1365 | #1773  |
| <ul><li>- [ ] </li></ul> | Progress Bar (vertical variant) | High | | |
| <ul><li>- [ ] </li></ul> | Progress Indicator (vertical variant) | High | | |
| <ul><li>- [ ] </li></ul> | Prompt | | | |
| <ul><li>- [ ] </li></ul> | Publishers | Medium | #1910 | #1913 |
| <ul><li>- [ ] </li></ul> | Rich Text Editor | High | #1881 | |
| <ul><li>- [ ] </li></ul> | Scoped Notifications | High | #1738 | #1785 |
| <ul><li>- [ ] </li></ul> | Scoped Tabs | High | | |
| <ul><li>- [ ] </li></ul> | Select | Low | #1691 | #1791 |
| <ul><li>- [ ] </li></ul> | Setup Assistant | High | #1884 | |
| <ul><li>- [ ] </li></ul> | Summary Detail | High | | |
| <ul><li>- [ ] </li></ul> | Tiles | High | #1363 | #1787 |
| <ul><li>- [ ] </li></ul> | Tree Grid | Medium | #1836 | |
| <ul><li>- [ ] </li></ul> | Trial Bar | Medium | #2006 | |
| <ul><li>- [ ] </li></ul> | Vertical Tabs | High | | |
| <ul><li>- [ ] </li></ul> | Visual Picker | High | #1693 | #1786 |
| <ul><li>- [ ] </li></ul> | Welcome Mat | High | | #1876 |

**Comment by pulkonet** [comment]
@interactivellama @kevinparkerson @futuremint  it would be great if you can add the priorities, whenever you have time.

**Comment by interactivellama** [comment]
Last week, I was focused on code reviews and getting v0.10 out the door. This week I will be turning to a longer term vision and doing [Salesforce] release planning and determining priorities of the next few months. Thank you for creating this. It is helpful to me.

Most likely I will be prioritizing issues at this location https://github.com/salesforce/design-system-react/milestone/22 or creating another milestone with a July deadline on it for second quarter.

**Comment by kevinparkerson** [comment]
@pulkonet this is extremely helpful, thank you!

**Comment by interactivellama** [comment]
I removed Picklist, because it's a Combobox variant.
