### ISSUE TITLE
Add outline brand button to button examples on doc website

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1943]
Please add `outline-brand` variant option to documentation examples for website

<img width="477" alt="Screen Shot 2019-04-23 at 10 57 34 AM" src="https://user-images.githubusercontent.com/1290832/56601003-44d8f300-65b7-11e9-83c3-95a0d2213493.png">

It should be placed in this file https://github.com/salesforce/design-system-react/blob/master/components/button/__examples__/brand-disabled-destructive-inverse.jsx#L25 

Order doesn't really matter.

**Comment by pulkonet** [comment]
@interactivellama I will add this too.
