### ISSUE TITLE
Progress Indicator: Add vertical orientation example to doc site

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1944]
orientation="vertical"

![Screen Shot 2019-04-23 at 11 31 11 AM](https://user-images.githubusercontent.com/1290832/56602758-70f67300-65bb-11e9-88e1-6550838d5e07.png)

![Screen Shot 2019-04-23 at 11 31 14 AM](https://user-images.githubusercontent.com/1290832/56602767-7358cd00-65bb-11e9-830d-1f8a115d694d.png)

New example file would be best. Add existing storybook story to this array at https://github.com/salesforce/design-system-react/blob/master/components/progress-indicator/__docs__/site-stories.js#L1

**Comment by pulkonet** [comment]
I am on it. @interactivellama

**Comment by interactivellama** [comment]
@pulkonet My designer is saying that the italics and bold text should be removed, too.
