### ISSUE TITLE
Vertical Progress Indicator: Support Setup Assistant

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1952]
This needs some more clarity and more detail to meet definition of ready, but I'm thinking a `setup-assistant` variant be added to progress indicator that allows `actions` on right side and add the gray line divider, etc. This would then be used as a sub component of Setup Assistant. Since this would only be used in Setup Assistant at this point, I'd propose that it just be a simple `onRenderActions` render prop.

https://www.lightningdesignsystem.com/components/setup-assistant/#Hub-with-Expandable-Steps
and 
https://github.com/salesforce/design-system-react/issues/1884
for more information

**Comment by pulkonet** [comment]
@interactivellama I will send in a draft PR tonight and we can discuss more then.

**Comment by interactivellama** [comment]
@pulkonet We have an internal need for this and would like get it released next week. Do you still want to work on this?

**Comment by interactivellama** [comment]
Props proposal (draft)

Add to `steps` array as optional 
```
setupAssistantEstimatedTime: text, node // NEW! only used in variant: setup-assistant
onRenderSetupAssistantAction: button, base button, toggle checkbox, etc. // NEW! only used in variant: setup-assistant
```

**Comment by pulkonet** [comment]
@interactivellama Can you tell me do we need to add `setupAssistantEstimatedTime` in the design?

**Comment by pulkonet** [comment]
<img width="1416" alt="Screenshot 2019-05-03 at 5 38 33 AM" src="https://user-images.githubusercontent.com/24983958/57114197-bb1ee780-6d65-11e9-97a4-912020aed57e.png">

I have added the buttons/checkboxes shown in the image above. Let me know your thoughts.

**Comment by interactivellama** [comment]
`setupAssistantEstimatedTime` Would be added after the `onRenderSetupAssistantAction `. It would render text into the gray text `<p class="slds-text-align_right slds-text-color_weak slds-p-top_medium">4 mins</p>`

![Screen Shot 2019-05-03 at 10 15 12 AM](https://user-images.githubusercontent.com/1290832/57150760-5d51c600-6d8c-11e9-8f31-1a2f177e1e33.png)
