### ISSUE TITLE
Modal: dismissOnClickOutside cannot be set to false to override disableClose

### ISSUE THREAD

**Issue by mattlysf** [salesforce/design-system-react#1954]
The Modal component determines if it should dismiss itself on outside clicks via this ternary expression:
 
``` javascript
		const dismissOnClickOutside = this.props.dismissOnClickOutside
			? this.props.dismissOnClickOutside
			: !this.props.disableClose;
```

When setting `dismissOnClickOutside` to false, it is equivalent to `false ? false : true` and will not evaluate to the value of `this.props.dismissOnClickOutside`. 

I'll send a PR over on Monday.

**Comment by interactivellama** [comment]
Great find. Thanks!

**Comment by mattlysf** [comment]
So for whatever reason, your bot tagged my personal github account for the CLA, not this one I use for work and will be contributing under. I've gone through the CLA for this account.
