### ISSUE TITLE
Illustration: Add all Illustrations from SLDS 2.8

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1956]
Add all SVGs to library
https://www.lightningdesignsystem.com/components/illustration/

**Comment by pulkonet** [comment]
I will take this up.

**Comment by kevinparkerson** [comment]
Having an issue with SLDS classes reaching our imported SVG file shadow-DOM. We're trying to avoid including all SVG markup directly within the library, so trying to figure out a workaround. See:
https://tympanus.net/codrops/2015/07/16/styling-svg-use-content-css/

**Comment by kevinparkerson** [comment]
Also see https://github.com/svg/svgo/issues/296 as a potential solution.

**Comment by interactivellama** [comment]
@kevinparkerson Since this has become more complex than we originally thought. For this sprint, I'd like to propose moving Illustration back into prototype and adding comments around incompatibility with SLDS's updated SVG markup. That way, consumers know it's an issue and we can warn them before they use try to use it and it doesn't work.

What do you think?
