### ISSUE TITLE
Carousel Design Updates

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#1959]
- [x] Use the slds-button_outline-neutral button instead of the slds-button_outline-brand button. It would be nice if this was configurable though to use other button colors.
- [x] Make the padding on the left and right side of each item 6px instead of 8px. This will make the total gap between items 12px.
- [x] Increase the left/right button size so it is slds-button_icon-small (24px by 24px) instead of slds-button_icon-x-small (20px by 20px).
- [x] Vertically center the left/right button so there is a consistent amount of space at the top and bottom of the button. Currently, the buttons are a little low (only take the item height into account...the dots don't count).
- [x] Change the button icon to the chevronleft/chevronright icons instead of the left/right icons. This will ensure that if by some off chance autoplay is used with the left/right buttons it won't look so similar to the play button.
- [x] Make sure the left/right buttons are always 20px from the left/right side of the first and last item. Currently, that gap can get rather large (i.e. 1 item examples).
- [x] Make sure the pause/play button align with the left edge of the first item. See the SLDS website as an example (https://lightningdesignsystem.com/components/carousel/#Panel-2-active). Currently, the pause/play button is too far to the left.
- [x] When autoplay is used it would be nice if it autoplay stopped automatically if the user clicks on a blue dot.
- [ ] It would be nice if when multiple items are displayed the height of the items were all consistent when the overall width causes some lines of text to be longer than others.

**Comment by kwilloughby-sf** [comment]
@interactivellama, here are the changes we talked about yesterday. Let me know if any of these are unclear.

**Comment by interactivellama** [comment]
@kevinparkerson This is @kwilloughby-sf 's design audit of our current multiple-item carousel. Please add into the existing Carousel issues if it does not jeopardize pull requesting by next Wednesday. Easy issues should be prioritized first.

**Comment by interactivellama** [comment]
@kwilloughby-sf We have declined to do the following item at this time. Please create an additional issue so that we can backlog it, but I don't see it happening soon. In the mean time, I would recommend that the number of slides per panel decrease when the layout no longer works.

> It would be nice if when multiple items are displayed the height of the items were all consistent when the overall width causes some lines of text to be longer than others.
