### ISSUE TITLE
Errors occur after clicking Dropdown 

### ISSUE THREAD

**Issue by jericbas** [salesforce/design-system-react#1966]
This error is showing after opening the dropdown.

```
aura_proddebug.js:14341 Uncaught (in promise) TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.
    at Proxy.SecureFunction$$1 (aura_proddebug.js:14341)
    at f (popper.js:265)
    at N (popper.js:738)
    at eval (popper.js:920)
    at e.value (popper.js:2511)
    at eval (popper.js:46)

```

**Comment by interactivellama** [comment]
@jericbas I think you have the wrong library. [Aura Components](https://github.com/forcedotcom/aura) are a different repository. This library uses the [React view library](https://github.com/forcedotcom/aura).

**Comment by jericbas** [comment]
I tried to check this code

https://github.com/salesforce/design-system-react/blob/050bfc98fb0282cf390833a37e3b651080c9c743/components/utilities/dialog/index.jsx#L212-L221

When I notice the `position` props of the condition, I set the `menuPosition="relative"` and it solves my problem.

**Comment by interactivellama** [comment]
This might be the same issue with Popper and LockerService as this issue https://github.com/salesforce/design-system-react/issues/1806
