### ISSUE TITLE
CSS bundle is massive and can not be easily trimmed

### ISSUE THREAD

**Issue by BenF-Lumedic** [salesforce/design-system-react#1969]
**Please include in your issue:**

Using any lightning components currently requires including the entire CSS bundle, which comes in, minified, at 532KB. This is potentially a huge amount of unnecessary weight in projects that are only using a small subset of the componentry.

Due to the dynamic assignment of some styles (icons & button variants to name a few) the CSS can not be effectively pruned (with, say, [purgecss-webpack-plugin](https://github.com/FullHuman/purgecss-webpack-plugin)), even after the project has been built, so there is no way to get rid of unused code.

Since this is, I think, specifically related to the React structure I'm posting here instead of in the main repo as suggested: 

> This project uses SLDS markup, but you should submit HTML/CSS issues to https://github.com/salesforce-ux/design-system.

**Comment by interactivellama** [comment]
I'm going to estimate that our primary consumers of this project have 1.5-2MB bundles of JS/image/CSS, but that's just a guess. Gzip'd the CSS should be less than 100KB. There are SASS source files, but I don't know how easy they are to build from. Have you tried that?

How many KBs are you trying to optimize your CSS delivery down to? How many components are you wanting to use your application's first hydrate? What speed of initial load are you trying to reach?

What path do you suggest? Are you wanting the CSS more modular?

**Comment by BenF-Lumedic** [comment]
Thanks for the quick response! Your first point is a good one, that this optimization may not be very useful to consumers of this project especially after Gzipping, so this thought may be out of scope.

I did manage to build the CSS from the SCSS source, the only issue was the `$static-font-path` in `_config.scss` which I had to change from `'../fonts/webfonts'` to `'../assets/fonts/webfonts'`. I'll play around with the SCSS to see if I can optimize the bundle. If I come up with anything useful I'll make a note here.

Ideally I would only want the styles for the global theme, layout, and components I'm using. My application specifically is a gated portal, so there won't be much on the home page at all, only a handful of components for navigation and authentication. I expect we could get away with <50kb css before gzipping. On the other hand, we're also primarily targeting desktop environments with (likely) good connections, so this may not even be an issue for my case specifically.

As far as my own 2¢, I do like the more modular design. Mostly I've worked with [Material-UI](https://material-ui.com/css-in-js/basics/) which is using the [css-in-js approach](https://cssinjs.org/?v=v10.0.0-alpha.16).

To me the MUI organization makes a lot of sense, as each component is self contained in terms of both style, function, and display. Components can still [access variables from the theme](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Button/Button.js), and CSS from heavily styled components won't be present unless those components are used.

**Comment by interactivellama** [comment]
I once saw Dan Abramov write web components solve organizational problems or something to that effect. I imagine CSS in JS is similar in a large company. 😄 

To be honest, I don't have much influence over how SLDS is packaged. It's primarily packaged up for use in building applications _on the Salesforce Platform_. That said, with web components or custom elements in the future there could be a more modular approach to take then. I'm going to close this issue, but if you'd like to pull request a readme in the docs folder on your solution, I'd love to see it and will merge it.
