### ISSUE TITLE
[UNSUPPORTED PROTOTYPE] RTL Support

### ISSUE THREAD

**Issue by minevskiy** [salesforce/design-system-react#1970]
RTL stands for right-to-left. Only a few languages use RTL text direction, but over a billion people use them.
Browsers support RTL direction via [dir](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) attribute and [direction](https://developer.mozilla.org/en-US/docs/Web/CSS/direction) CSS property.

While DOM layout direction is automatically flipped by the browser, directional styles are not. For example, `margin-left` should usually be converted to `margin-right` and vice versa. Also, icons which have directional meaning, such as arrows, have to be flipped.

There are ways to compile an RTL version of SLDS styles. An RTL SLDS icon sprite will also be available. When DSR uses RTL SLDS styles and icons, several issues have been identified:

1. Icon should use RTL SLDS icon sprite
2. `align` prop of Dialog, Menu, and ComboBox has to be flipped
3. Left/right keyboard navigation has to be flipped because DOM layout is flipped

Note that the above list may be incomplete, but is the MVP.

**High-level impl proposal**
Introduce new components to support RTL:
* a global Settings component (similar to IconSettings) which will contain setRTL() and isRTL() methods. 
* a private Higher Order Component (HOC) for each RTL component. The HOC will be used to wrap the SLDS React component. The HOC will check `Setting.isRTL()` and flip directional props accordingly on the wrapped component. 
    * consumers will use the HOC in place of regular components.
    * composed DSR components which use other DSR components internally will have to use HOCs in place of regular components.
    * hard-coded alignments have to be converted to props
* keyboard navigation handlers have to check `Setting.isRTL()`

**Scope**
The initial scope will include the following components:
- Icon (use RTL sprite)
- ComboBox (flip alignment)
- MenuDropdown (flip alignment)
- DatePicker (keyboard navigation)
- ColorPicker (keyboard navigation)

**Comment by interactivellama** [comment]
I'm think I'm better understanding our conversation earlier. They already have `onClickOutside`, so we we could add another HOC.

Exploring the react-with-direction makes me wonder if we need to add wrapping span or div around components with a `dir` attribute on it. Do you know if that is needed? I'd guess that flips the built in  tags like `<p>`. I think we could just put it on the outer div of the "normal component," too.

As far as nested components go (such as Icon in a Combobox menu item), you are right--we'll want to use something like `LanguageDirection(<Icon>)`

The more I'm thinking about icon and all the "low level" places it is used--it makes me want to simplify the code and just export all icon ass in their default export as `LanguageDirection(<Icon>)`.

I'm looking at https://github.com/airbnb/react-with-direction This also might be closer to what you originally proposed to me when were talking in San Francisco. 

@minevskiy Could you provide some code samples to clarify?

I believe the React 16.3 Context now has publish/subscribe observables built into it, `react-with-direction` is using the old syntax.

```
import { DIRECTIONS } from 'components/utilities/private/direction-settings';
<DirectionSettings direction={DIRECTIONS.RTL}>
    <Combobox />
</DirectionProvider>
```

```
import LanguageDirection, { DIRECTIONS } from 'components/utilities/private/direction';

function MailForwardsLabel({ direction }) {
  return (
    <div dir="right">
      Mail Forward
      {direction === DIRECTIONS.LTR && <img src="arrow-right.png" />}
      {direction === DIRECTIONS.RTL && <img src="arrow-left.png" />}
    </div>
  );
}
ForwardsLabel.propTypes = {
// not publicly listed, but HOC passes in `direction="right"` prop
};

export default LanguageDirection(ForwardsLabel);
```

Would you prefer to just wrap the the default exports of those components?

**Comment by minevskiy** [comment]
We don't need to add `dir='rtl'` attribute - it will be added by consumers. 
It's typically on the `<html>` node, but we do need a way to override the direction for certain branches of the React tree. Essentially, some components will not support RTL and will always render in LTR. This is achieved by hard-coding `dir='ltr'` on roots of such branches.

Having a single `LanguageDirection` HOC is what I was proposing in our conversation earlier. It is more manageable than having an HOC per component (which would flip component-specific props) at the expense of the component being aware of language direction. However, components which need to flip keyboard navigation will have to be aware of direction anyway.
I agree that code will be simpler if we just exported the wrapped version. 

_components/utilities/private/direction/direction-settings.jsx_
```
export const DirectionSettings = React.createContext('ltr');
```

_Consumer code_
```
// ComboBox is wrapped with LanguageDirection 
import { ComboBox } from 'components/combobox';
import DirectionSettings from 'components/utilities/private/direction/direction-settings';

<DirectionSettings.Provider value={document.querySelector('html').dir}>
	// use document direction
	<Combobox />

	<DirectionSettings.Provider value="ltr">
		// hard-coded to ltr
		<Combobox />
	</DirectionSettings.Provider>

</DirectionSettings.Provider>
```

_components/utilities/private/direction/language-direction.jsx_
```
export default function LanguageDirectionHOC(WrappedComponent) {
	const componentName = WrappedComponent.displayName || WrappedComponent.name || 'Component';
	return class LanguageDirection extends Component {
		static displayName = `LanguageDirection(${componentName})`;
		static contextType = DirectionSettings;

		render() {
			let { props } = this.props;
			props.direction = this.context;
			return createElement(WrappedComponent, props);
		}
	};
}
```

_combobox/index.jsx_
```
import onClickOutside from 'react-onclickoutside';
import LanguageDirection from 'components/utilities/private/direction/language-direction';
import Combobox from './combobox';

export default LanguageDirection(onClickOutside(Combobox, {
	excludeScrollbar: true,
}));
```

_combobox/combobox.jsx_
```
import { DIRECTIONS } from 'components/utilities/private/direction/direction-settings';

getDialog({ menuRenderer }) {
	const align = this.props.direction === DIRECTIONS.RTL ? "bottom right" : "bottom left";
	return (
		<Dialog
			align={align}
			...
		>
			{menuRenderer}
		</Dialog>
	);
```

**Comment by interactivellama** [comment]
I agree this is the right approach. Thank you for being patient with me to come around. 🙏  I'll take a closer look at the detailed API tonight.

**Comment by interactivellama** [comment]
API is approved.

Let's be sure to documents in comments in the source about the expected `html dir='rtl'` so folks know how it's needed. We can probably have some Storybook examples with a `div dir='rtl'` wrapper, too.

**Comment by davidlygagnon** [comment]
@interactivellama I chatted with @minevskiy and I'll pick this up.

**Comment by interactivellama** [comment]
Sounds good.

![giphy](https://user-images.githubusercontent.com/1290832/57424748-f3934b00-71d5-11e9-9867-863923e8c216.gif)

**Comment by davidlygagnon** [comment]
Chatted with @interactivellama about the use of `/private` folder. The idea is that we don't want to make RTL a publicly supported feature. What we'll do is to prefix the component with `UNSAFE_`, similar to what React does with legacy life cycles methods instead of being in a /private folder. That should avoid confusion about the consumption of features from the /private folder in client code.

**Comment by interactivellama** [comment]
@davidlygagnon Thank you for suggesting another way to caution consumers.
