### ISSUE TITLE
PageHeader: Support Breadcrumb above heading

### ISSUE THREAD

**Issue by jgerigmeyer** [salesforce/design-system-react#1972]
This is somewhat related to #1583, but wasn't fully addressed by #1586.

When a PageHeader with `variant="object-home"` also has a `trail`, the media object is vertically misaligned with the text:

![Screenshot 2019-05-07 10 03 48](https://user-images.githubusercontent.com/552316/57307734-1842d200-70b3-11e9-9a76-8459762c619f.png)

There isn't an exact example on the SLDS page (https://www.lightningdesignsystem.com/components/page-headers/), but given the examples I would expect the icon to be vertically centered with the text (and maybe less space in between the `trail` and `title`).

**Comment by interactivellama** [comment]
We have plans for this. @kwilloughby for issue visibility. I think this aligns with your request.

Our setup pages need to support a Breadcrumb above a heading. I think the current plan to have a "setup" variant that has a prop that accepts a breadcrumb component.

I don't have an exact timeline for the fix, but our consumer would like this within the next few weeks.

**Comment by interactivellama** [comment]
User Story update. "Record Type: Opportunities" should be able to be changed to a BreadCrumb component in all but Base variant. 

Prop proposal: 
```
titleBreadcrumb=<BreadCrumb
		assistiveText={{ label: 'Two item breadcrumb' }}
		trail={[
			<a id="parent-entity" href="javascript:void(0);">
			Parent Entity
		</a>,
		<a href="javascript:void(0);">Parent Record Name</a>,
	]}
/>
```

![Screen Shot 2019-05-14 at 1 43 00 PM](https://user-images.githubusercontent.com/1290832/57727249-3af25f00-764e-11e9-8bce-52a01d9176d0.png)

**Comment by interactivellama** [comment]
Add Setup example

```
		<Icon
			assistiveText={{
				label: 'Account',
			}}
			category="standard"
			name="home"
			style={{
				backgroundColor: '#ea7600',
				fill: '#ffffff',
			}}
			title="This is a title"
		/>
```

Example should like the following, except Setup is a link made through `BreadCrumb` component. Icon should be orange in example. See above code.

![image](https://user-images.githubusercontent.com/1290832/57728347-f74d2480-7650-11e9-8c9f-0e3d0fba6aca.png)

**Comment by interactivellama** [comment]
This should be fixed now.
