### ISSUE TITLE
DataTable allow multiply cols of the same property

### ISSUE THREAD

**Issue by Niondir** [salesforce/design-system-react#1978]
Currently you can a warning that keys are not unique when having multiple `DataTableColumn` with the same `property` attribute. But that might happens when you do some custom rendering.

A simple fix would be to update in `head.jsx` the `id` and `key` attribute of the `HeaderCell` from:

```
id={`${this.props.id}-${column.props.property}`}
key={`${this.props.id}-${column.props.property}`}
```

to:

```
id={`${this.props.id}-${column.props.property}-${column.props.id}`}
key={`${this.props.id}-${column.props.property}-${column.props.id}`}
```

Now you can add a simple `id` attribute to your `DataTableColumn` to fix the warning.

**Comment by jsabety** [comment]
I have this exact same issue and not quite sure how to implement your suggestion....   where is head.jsx and HeaderCell?

**Comment by Niondir** [comment]
It's quiet a while ago. I just forked all the code and modified the table to my needs in many places. Not sure what changed since then, sorry.

You might find the snippet when checking out a revision from around 10 May 2019

**Comment by jsabety** [comment]
Ah ok thanks for the reply... not sure I want to go that route... will continue to see if there is any way to take care of it in my app but so far I can't find a way and the errors are driving me bonkers!
