### ISSUE TITLE
Icon: Add background theme colors

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1980]
Props proposal:
`backgroundThemeColor="marketing"`

would do the following, but without the `style` tag:

```
		<Icon
			assistiveText={{
				label: 'Account',
			}}
			category="standard"
			name="home"
			style={{
				backgroundColor: '#ea7600'
			}}
			title="This is a title"
		/>
```

Add all cloud themes:
* Global Setup #2A739E - (all clouds)
* Service Cloud
R127 G36 B67 Web 7f2443
C37 M96 Y45 K27 Pantone 216C
* Industry Cloud
R76 G34 B72 Web 4c2248
C65 M95 Y9 K40 Pantone 519C
* Sales Cloud
R0 G133 B125 Web 00857d
C96 M0 Y47 K19 Pantone 7717C
* Commerce Cloud
R65 G105 B61 Web 41693d
C71 M8 Y90 K50 Pantone 7743C
* Community Cloud
R231 G165 B54 Web ffc20e
C0 M33 Y92 K2 Pantone 2007C
* Marketing Cloud
R234 G118 B0 Web ea7600
C4 M65 Y100 K5 Pantone 716C
* Quip
R207 G69 B29 Web cf451d
C0 M81 Y100 K0 Pantone 173C

**Comment by pulkonet** [comment]
I will take this

**Comment by interactivellama** [comment]
@kevinparkerson Could you groom this spec a little more?

**Comment by kevinparkerson** [comment]
@pulkonet here is what we'd like for you to do with this issue:

- Create a new folder beneath `design-system-react/utilities/` called "product-tokens"
- Add a file to the `product-tokens` folder called "icon-backgrounds.js"
- Export a single object from `icon-backgrounds.js` with keys being tied to cloud names (ex: "marketing-cloud") and values being tied to rgba color strings. Use `design-system-react/utilities/design-tokens/dist/components.common.js` as an example
- Add a `productTheme` property to the Icon component. Acceptable values should be "global-setup", "service-cloud", "industry-cloud", "sales-cloud", "commerce-cloud", "community-cloud", "marketing-cloud", and "quip"
- Have the Icon component import the `icon-backgrounds.js` object to apply styles based on `productTheme` value (you should only need to apply `backgroundColor` currently as `fill` is handled by the `inverse` Icon prop)
- Create an example that shows all `productTheme` Icon variants
- Make sure to add a note to the `productTheme` property comment that mentions it is only compatible with an Icon `category` property value of "standard"
