### ISSUE TITLE
PageHeader component : Adding iconPath to allow passing a custom icon.

### ISSUE THREAD

**Issue by davidlygagnon** [salesforce/design-system-react#1984]
As a consumer of `PageHeader` component, I'd like to pass in a custom icon similar to the way it's done for `Button` component.

Prop proposition (same as other components):

```
/**
 * Path to the icon. This will override any global icon settings.
 */
iconPath: PropTypes.string,
```

I'll work on this PR.

Please include in your issue:

* If you are working on the problem. Issues may be closed within 30 days if no one is assigned. Maintainers work on this project 20-30 hours per week and have their own prioritized backlog.
* How to duplicate a bug. Line numbers or code to paste into the documentation site examples is helpful.
* If you are a Salesforce employee. You should also create a duplicate work item in your internal ticket system and link to this issue.
* If you plan to work on a new component. Please propose props after reviewing at newly written components and `docs/codebase-overview.md`.

For Salesforce platform questions, please visit https://success.salesforce.com, https://partners.salesforce.com, or https://salesforce.stackexchange.com

This project uses SLDS markup, but you should submit HTML/CSS issues to https://github.com/salesforce-ux/design-system.

**Comment by interactivellama** [comment]
Please pass in `Icon: <Icon/>` prop instead and deprecate iconName/iconCategory.

**Comment by interactivellama** [comment]
This should be fixed now.
