### ISSUE TITLE
Add vertical progress bar

### ISSUE THREAD

**Issue by pulkonet** [salesforce/design-system-react#1999]
Add vertical progress bar according to https://lightningdesignsystem.com/components/progress-bar/#Vertical

**Comment by pulkonet** [comment]
I will take this up

**Comment by garygong** [comment]
What do you think about this for the prop:
```
variant: base | vertical
```

**Comment by pulkonet** [comment]
I can add an initial PR for the same.

**Comment by garygong** [comment]
Looks like there is already `progress-indicator` with `orientation: 'horizontal' | 'vertical'`.  Let's just use that to be consistent.
