### ISSUE TITLE
Add Trial Bar Component

### ISSUE THREAD

**Issue by pulkonet** [salesforce/design-system-react#2006]
Add Trial Bar Component according to specs https://lightningdesignsystem.com/components/trial-bar/

I am working on this and will send a prop proposal soon.

**Comment by pulkonet** [comment]
Here is my initial props proposal:

Name | Type | Description |
| ------ | ------ | ------ |
||||
||||

**Comment by pulkonet** [comment]
@garygong @davidlygagnon Please see if the props are plausible, I will raise a PR for the same tomorrow morning.

**Comment by interactivellama** [comment]
@garygong We may want this API to look something more like `BuilderHeader`. https://react.lightningdesignsystem.com/components/builder-header/

**Comment by garygong** [comment]
If we were to have the API be more like `BuilderHeader`, here's what it would look like.  I actually like this.  What do you think?

### TrialBar
Name | Type | Description
| ----- | ----- | ----- |
| onRenderActions | function | Renders the actions section of the trial bar. |
| children | Element[] | `<TrialBarButton />` and `<TrialBarDropdown />` |
| className | string | CSS classes to be added to the component. |
| style | string | Customs styles to be applied to the component. |

### TrialBarButton
_Same props as `Button`._

### TrialBarDropdown
_Same props as `Dropdown`._

### Example

Here's a sample using the example from the SLDS page.  
```
<TrialBar
  onRenderActions={() => (
    <span class="slds-box slds-box_xx-small slds-theme_default">30</span>
    <span class="slds-m-horizontal_x-small">Days left in trial</span>
    <a href="javascript:void(0);" class="slds-button slds-button_success">Subscribe Now</a>
  )}
>
  <TrialBarButton label="Take the salesforce tour" />
  <TrialBarDropdown
    assistiveText={{ icon: 'Dropdown' }}
    id="dropdown"
    label="Choose your tour"
    options={[
      { label: 'Conquer Your Cases', value: 'item1'},
      { label: 'Automate For Speed', value: 'item2'},
      { label: 'Share Your Knowledge', value: 'item3'},
      { label: 'Finish it up in a Flash', value: 'item4'},
      { type: 'divider' },
      { label: 'Import Contacts and Accounts', value: 'item5', leftIcon: { name: 'utility', category: 'upload' } }
    ]}
    value={['item1']}
  />
</TrialBar>
```

**Comment by interactivellama** [comment]
Looks good to me. 

Two comments
* I think we have a success variant Button, but the text isn't looking right--It's still blue. That might need to be fixed. It looks like it's actually a link though. Should we have a link/button mix of props for Button or maybe a Link component? Feel free to proceed though. This can be added in the future.
* We may want the time left strings in a labels object, so folks don't need to format it.

Our current success button:
<img width="169" alt="Screen Shot 2019-06-05 at 8 53 40 PM" src="https://user-images.githubusercontent.com/1290832/59003649-106e6e80-87d4-11e9-8a88-3fe6bd104930.png">

**Comment by garygong** [comment]
Good point.  I updated the example above to use time left.  I left the success link (button??) in a render function so that consumers can have that additional flexibility.

By "link/button mix of props" do you mean that we'd have something like a `<Button link />` prop that would cause `<a>` to be used instead of `<button>`?  This seems to be consistent with how the [SLDS Button page](https://lightningdesignsystem.com/components/buttons/) has samples for links, too.

**Comment by interactivellama** [comment]
Yes. Something like that. We’d deprecate link variant I think so that the link prop could be any of the button variants.

**Comment by interactivellama** [comment]
@aswinshenoy might be interested in picking up the button/link issue. The user story still needs to be groomed /spec decides, but props could be proposed. @aswinshenoy would you be interested in working on the missing button options for the first evaluation period?

**Comment by davidlygagnon** [comment]
@interactivellama Did we file an issue for the button/link? I noticed that when testing the trial bar component.

**Comment by interactivellama** [comment]
No, I haven't created an issue. I was waiting for someone to propose an API for it.

**Comment by davidlygagnon** [comment]
Ok - I'll create the issue and TBD for props proposal so that we don't forget.

**Comment by davidlygagnon** [comment]
Here's the new issue: https://github.com/salesforce/design-system-react/issues/2090
