### ISSUE TITLE
Setup Assistant With Steps: Incorrect Formatting

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#2008]
Please see the image below. This impacts all variants **except** Base. 

The title, text, buttons/links are too high. It appears all the variants with steps are missing two divs. At first, we thought it was just missing a class but I am fairly sure it's missing two divs that Base does not have.

![comparison](https://user-images.githubusercontent.com/42620858/58834360-37387380-8621-11e9-8cd2-e5e4bd8b2af1.png)

**Comment by interactivellama** [comment]
@PaulaIoana
