### ISSUE TITLE
Radio Group: Update labels from props after instance construction

### ISSUE THREAD

**Issue by davidakerr** [salesforce/design-system-react#2009]
I'm trying to update the error state on my Radio Group form item.  I can't figure out how to do it programatically.  If I set it explicitly as having an error it shows fine. If I add the error at runtime it does not update.

I think maybe having an error prop would be better?

Here's my problem on codesandbox:
https://codesandbox.io/embed/wonderful-raman-5lc9w

**Comment by interactivellama** [comment]
The `labels` object merge is happening in the constructor which only constructs at instance creation. The object merge needs to be moved into the render function. Then, the object will get updated on each new render.

https://github.com/salesforce/design-system-react/blame/70ce97e04db403572eb04a7d3604ae331f63d9fe/components/radio-group/index.jsx#L73
