### ISSUE TITLE
Required changes to setup-assistant component

### ISSUE THREAD

**Issue by PaulaIoana** [salesforce/design-system-react#2012]
In order to match MC Setup design specs for the Setup Assistant Page, the following are needed
- in step.jsx the ProgressRing component should receive the flowDirection = 'fill' prop with the colour blue.
Expected:
![Screen Shot 2019-06-05 at 17 53 53](https://user-images.githubusercontent.com/26438120/58966439-fa07e900-87ba-11e9-856e-713e99f2d9d2.png)

- the expand/collapse arrow, ProgressRing and the step's heading needs to aligned
Current Implementation
![Screen Shot 2019-06-05 at 17 48 11](https://user-images.githubusercontent.com/26438120/58966052-46065e00-87ba-11e9-83f9-61ffc0102127.png)

Expected:
![Screen Shot 2019-06-05 at 17 51 22](https://user-images.githubusercontent.com/26438120/58966243-9b426f80-87ba-11e9-907b-a54cd75b4d4c.png)

**Comment by interactivellama** [comment]
Both these are missing features that should exist.

* Issue created for item one. See #2013
* Transferring Item two to existing item #2008

Closing this issue.
