### ISSUE TITLE
Accordion Component does not collapse

### ISSUE THREAD

**Issue by nik72619c** [salesforce/design-system-react#2026]
Problem Statement:- 
The accordion component should close on a second click.

* Yes, I am working on this issue
* How to duplicate:-
 run the storybook through npm start -> try opening and closing the accordion component
* No, I am not a salesforce employee
* No, I do not plan to work on a new component

**Comment by nik72619c** [comment]
Please guide me out with this, whether I should work on it or not.

**Comment by interactivellama** [comment]
The accordion is “controlled”—that is you the consumer decide what is open and closed. If you'd like to add an example in the Storybook examples that demonstrates the ability to close, e would be open to that addition.

**Comment by interactivellama** [comment]
### Follow up addition
Please use the `expanded` prop to control panels. I'm going to close this, but feel free to re-open with questions about adding an example that allows the closing of panels.

**Comment by nik72619c** [comment]
okay ,thanks for the guidance!
