### ISSUE TITLE
Icon Button: Missing background color

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#2027]
Some of the icon buttons have transparent backgrounds. I noticed this in page header the other day, but it looks like Button stateful has it, too.

<img width="328" alt="Screen Shot 2019-06-10 at 10 45 46 AM" src="https://user-images.githubusercontent.com/1290832/59211403-fda9c000-8b6c-11e9-8cc4-412d3cbf4649.png">

Anyone is free to pick this up.

http://design-system-react-components.herokuapp.com/?selectedKind=SLDSButtonStateful&selectedStory=Icon&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by pulkonet** [comment]
This is happening because the icons are using the class `slds-button_icon-border` instead of `slds-button_icon-border-filled` which would fill the icon buttons with a white background and make it consistent.

@interactivellama thoughts?

**Comment by pulkonet** [comment]
Previous
<img width="414" alt="Screenshot 2019-06-13 at 10 27 48 AM" src="https://user-images.githubusercontent.com/24983958/59404873-ef0a1580-8dc5-11e9-9473-19bfe67974bc.png">

After Change
<img width="414" alt="Screenshot 2019-06-13 at 9 55 58 AM" src="https://user-images.githubusercontent.com/24983958/59404883-fc270480-8dc5-11e9-81e3-8b2187b74dfb.png">
