### ISSUE TITLE
Validate documentation site consumption of library in tests

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#2066]
User story:
* Problem: Contributor does not list component in `package.json`. Contributes are seeing `docs.json`.
  * Mimic components-doc.json's `build:docs` behavior and build site consumable doc at test and npm script
* Problem: Contributors miss adding entry in site stories array
  * move example links to docs.json and centralize doc relationship there
  * Test if they exists
* Make website URL slugs singular and add plurals to re-direct table. See `routes.js` in site repo: `<Redirect from="breadcrumbs" to="breadcrumbs/" />`
* Problem: Variables work in Storybook, but are `undefined` in site examples since the site examples only have access to `components/index.js` exports 
  * Scan docs.json examples and compare to what's in index.js. I'm unsure about this one. 

Possible issues:
* Currently site-stories import raw Node/CommonJS imports: `require('raw-loader!@salesforce/design-system-react/components/slider/__examples__/base.jsx'),`

New `docs.json`
```
{
	"component": "setup-assistant",
	"status": "prototype",
	"display-name": "Setup Assistant",
	"SLDS-component-path": "/components/setup-assistant",
	"dependencies": [
		{
			"component": "step"
		}
	],
	"url-slug": "setup-assistant",
	"site-stories": [
		{
			"name": "Base",
			"file-path": "__examples__/base.jsx"
		}
	]
}
```

**Comment by kevinparkerson** [comment]
Discussed finalized solutions for these problems:
- Renname all docs.json files to component.json
- Remove components from package.json
- Remove components/site-stories.js & storybook-stories.js files
- Site stories and storybook stories will instead be listed in individual component.json files
- Have a "priority" key that prioritizes certain components over others when running tests that can be changed from false to true to aid development
- Make website URL slugs singular and add plurals to re-direct table. See routes.js in site repo: <Redirect from="breadcrumbs" to="breadcrumbs/" />
- Automatically add components to components/index.js. Will need additional keys for this in component.json

**Comment by interactivellama** [comment]
How to pull in all stories based on file name into Storybook
https://github.com/storybookjs/storybook/issues/3847#event-1767083868

**Comment by interactivellama** [comment]
Removing `storybook-stories.js` is not a priority. I think the best way to approach for this is that config for a component needs to happen in one file, no matter how complicated that file is. If the config is one file then contributors will look at other components and figure out the config, therefore the source is self-documenting.
