### ISSUE TITLE
Carousel: Align with SLDS design

### ISSUE THREAD

**Issue by obalbinat** [salesforce/design-system-react#2078]
In order to match MC Setup design specs for the Carousel component, the following are needed: 

- Carousel navigation buttons should be medium size (updated from slds-button_icon-small to slds-button_icon-medium)
Expected
![Screen Shot 2019-06-19 at 2 55 50 PM](https://user-images.githubusercontent.com/51956523/59763549-7f52c980-92a2-11e9-9038-fe1ae2633aa5.png)

- Carousel Indicators should be separated by 8px, that mean each indicators should have 4px vertical padding
Expected
![Screen Shot 2019-06-19 at 2 56 53 PM](https://user-images.githubusercontent.com/51956523/59763569-8b3e8b80-92a2-11e9-8659-cfbb8b36195f.png)

- When there is no carousel navigation buttons (previous/next), the panel width size should be same size as the parent's (remove inline style, margin-left and margin-right)
![Screen Shot 2019-06-19 at 2 49 14 PM](https://user-images.githubusercontent.com/51956523/59763218-c8eee480-92a1-11e9-8816-feae7b6f32fd.png)

**Comment by interactivellama** [comment]
Approved. Please create a pull request! Thank you!

**Comment by interactivellama** [comment]
@kwilloughby-sf MC Setup team has asked to increase the size of the left/right buttons in Carousel from small to medium. See example below (left is small, right is medium):
<img width="911" alt="Screen Shot 2019-06-19 at 12 25 08 PM" src="https://user-images.githubusercontent.com/1290832/59790597-88856b80-928d-11e9-866e-84da14f4674e.png">


Did you recently request the small button size? If so, please talk to Stephanie about this change and the rationale behind it.

**Comment by kwilloughby-sf** [comment]
@obalbinat & @interactivellama 

I spoke with Stephanie B. and we agreed small is okay for #1. That size button is the same size as the Carousels we've seen elsewhere in Salesforce. Please do not change the size.

Good catch on #2. Looks like we just need to remove the inline style on the <li>.

**Comment by interactivellama** [comment]
Adding @PaulaIoana due to changes in scope / user story acceptance criteria
