### ISSUE TITLE
Upgrade library to SLDS 2.9.x

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#2080]
Peer and dev dependency is out of date. The latest 2.x version of SLDS is 2.9.3

**Comment by interactivellama** [comment]
#2082 needs to be fixed first.

**Comment by qyiming** [comment]
Make sure to remove design-system-react/assets/icons/standard-sprite/svg/symbols-rtl.svg once SLDS is upgrade to 2.9.x in DSR
