### ISSUE TITLE
Progress Bar: Add label render prop

### ISSUE THREAD

**Issue by obalbinat** [salesforce/design-system-react#2106]
In order to match MC Setup design specs for the Setup Assistant Page, the following are needed:

-I should be able to change the size of the progress-bar text. The text is displayed in a large font and in a bold black color, but the expected results are a text with a small font and with a gray color.

Expected result:
![Screen Shot 2019-06-24 at 17 28 10](https://user-images.githubusercontent.com/51956523/60027221-b9a6d700-96a5-11e9-8648-9d51f8ccec7c.png)
 Actual result:
![Screen Shot 2019-06-24 at 17 31 27](https://user-images.githubusercontent.com/51956523/60027423-1c986e00-96a6-11e9-9bd2-c373f31647db.png)

For the expected result:

- there should be added/changed following classes: slds-color__text_gray-8    slds-text-body_small    slds-p-bottom_xx-small 

- removed or changed the <strong> tag.

P.S.
The progress-bar component should have both variants, actual one and the expected one.

**Comment by interactivellama** [comment]
@obalbinat  A non-bold visual label on the right is not currently a part of SLDS.
https://www.lightningdesignsystem.com/components/progress-bar/
https://react.lightningdesignsystem.com/components/progress-bars/

I’d be open to something like a `onRenderDescription` prop on Progress Bar, I think. Let me look into it a little more. That would pass in the 90 as a parameter and  give you control of the whole top section possibily.

Let me think about it today and scope out a render prop for you.

**Comment by interactivellama** [comment]
@obalbinat 

@kwilloughby-sf is telling me that there are accessibility concerns when the label is not bold. He will talk to the designer and see if the design can be updated. If the design is updated, I will close this issue.

**Comment by kwilloughby-sf** [comment]
For additional clarity, bold isn't the issue. Gray 8 only has a contrast ratio of 3.02:1 which falls below the 4.5:1 AA ratio. I have reached out to JoAnne J. (accessibility) and Stephanie B. (design) to discuss. I will report back.

**Comment by kwilloughby-sf** [comment]
@obalbinat @interactivellama 

Please close this ticket. I spoke with Stephanie B. and we agreed to leave the DSR component as-is (no changes). 

Also, smaller text must meet the 4.5:1 WCAG AA contrast ratio to be accessible (slds-color__text_gray-8 does not). For reference, larger text needs to be meet the 3:1 WCAG AA contrast ratio to be accessible. Here is a handy tool https://webaim.org/resources/contrastchecker/.

@jcjuett

**Comment by interactivellama** [comment]
@obalbinat @PaulaIoana Closing this issue. Design will be updated to conform to current SLDS spec.
