### ISSUE TITLE
Dialog: Failed prop type: Invalid prop `direction` of value `[object Object]` supplied to `SLDSDialog`, expected one of ["ltr","rtl"].

### ISSUE THREAD

**Issue by gla5001** [salesforce/design-system-react#2108]
After upgrading to 0.10.5, getting the following with Dropdowns using DropdownTrigger

```
Warning: Failed prop type: Invalid prop `direction` of value `[object Object]` supplied to `SLDSDialog`, expected one of ["ltr","rtl"].
    in SLDSDialog (created by LanguageDirection(SLDSDialog))
    in LanguageDirection(SLDSDialog) (created by SLDSMenuDropdown)
    in div (created by SLDSMenuDropdownTrigger)
    in SLDSMenuDropdownTrigger (created by SLDSMenuDropdown)
    in SLDSMenuDropdown (created by OnClickOutside(SLDSMenuDropdown))
```

**Comment by gla5001** [comment]
also happens with the color pickers

**Comment by interactivellama** [comment]
Thank you @gla5001 I’m seeing it on all components that use `Dialog` sub component. https://travis-ci.org/salesforce/design-system-react/builds/549833816#L7003

@davidlygagnon Do you have a suggestion?

**Comment by gla5001** [comment]
It might just need a default value specified.

**Comment by davidlygagnon** [comment]
I'll take a look - I think @gla5001 is right - probably not initialized correctly when consumed by components other than combobox.

**Comment by davidlygagnon** [comment]
Just a quick progress update on this: 

This is what I'm seeing when running `datepicker.snapshot-test.js`. The context has been set to `{}` which is odd because when we create the context, we initialize it to `ltr`. I also wasn't able to see the prop-type warning running any component using dialog in story-books.

<img width="1130" alt="Screen Shot 2019-06-26 at 7 37 50 AM" src="https://user-images.githubusercontent.com/1821787/60189152-54f29600-97e5-11e9-8921-aeb8453ac3af.png">

`dialog/index.jsx` has a default prop set for direction so my initial though of not being initialized correctly is wrong.

Still looking into it. 

@gla5001 Do you have a specific snippet of code that can repro the issue? Or is it simply consuming an `SLDSMenuDropdown` ?

**Comment by gla5001** [comment]
@davidlygagnon im seeing it with all my dropdown, popovers, and color pickers. Anything that uses the `SLDSDialog`. Here is something that is showing the error. Its worth noting, that you only get it when the dropdown/popover/color picker is opened the first time

```javascript
import {
  Button,
  Dropdown,
  DropdownTrigger
} from '@salesforce/design-system-react';

<Dropdown
    tabIndex="-1"
    align="right"
    onSelect={item => {
        // do something
    }}
    options={[
         { label: 'label1', value: 'value1' },
         { label: 'label2', value: 'value2' }
    ]}
    width="xx-small"
>
   <DropdownTrigger>
         <Button iconCategory="utility" iconName="down" iconPosition="right" label="Dropdown" />
    </DropdownTrigger>
</Dropdown>
```

hope this helps

**Comment by interactivellama** [comment]
@davidlygagnon TravisCI and `npm test` has this console warning in it, so you might try the Mocha or Jest tests as a use case.

**Comment by kevinparkerson** [comment]
@davidlygagnon I noticed this the other day myself... take a look at `design-system-react/components/utilities/UNSAFE_direction/private/language-direction.jsx`. One thing that works is to alter how `props.direction` is set:

```
import React, { Component } from 'react';

// eslint-disable-next-line camelcase
import UNSAFE_DirectionSettings from '..';

const LanguageDirectionHOC = (WrappedComponent) => {
	const componentName =
		WrappedComponent.displayName || WrappedComponent.name || 'Component';
	return class LanguageDirection extends Component {
		static displayName = `LanguageDirection(${componentName})`;

		// eslint-disable-next-line camelcase
		static contextType = UNSAFE_DirectionSettings;

		render() {
			const props = { ...this.props };
			props.direction = (typeof this.context !== 'string') ? 'ltr' : this.context;
			return React.createElement(WrappedComponent, props);
		}
	};
};

export default LanguageDirectionHOC;
```

When I was looking into it, I noticed the value of `this.context` is either an empty object or a string. Looking at `design-system-react/components/utilities/UNSAFE_direction/index.jsx`, it sets `const UNSAFE_DirectionSettings = React.createContext('ltr');` with a default of 'ltr' so could that be a feasible fix? Either way hope that helps illuminate the problem spot some.

**Comment by davidlygagnon** [comment]
Thanks - yes there seems to be a clash with the oldContext API. I think that's why it gets initialized to an empty object. I think I have a fix - will do a little more testing before creating the PR.
