### ISSUE TITLE
Module not found after upgrading Webpack from 4.33.0 to 4.35.0

### ISSUE THREAD

**Issue by amoskane** [salesforce/design-system-react#2116]
Hi, Getting an error that 

node_modules/@salesforce/design-system-react/module/components/trial-bar
can't resolve '../../../components/menu-dropdown/button-trigger'
and 
can't resolve '../../../components/button'

after bumping Webpack from 4.33.0 to 4.35.0.

Probably because both button/index.jsx and button-trigger/index.jsx are jsx files instead of js files?

**Comment by interactivellama** [comment]
Please see #2113. Use 0.10.7 and we hope it doesn’t happen again with #2115
