### ISSUE TITLE
Setup Assistant component is not rendering properly in IE 11 browser

### ISSUE THREAD

**Issue by obalbinat** [salesforce/design-system-react#2149]
The layout for ProgressRing is broken on Internet Explorer 11 for the case when the progress is bigger than 0% and smaller than 100%.

![Capture](https://user-images.githubusercontent.com/51956523/60587801-0709ff00-9d9e-11e9-9f1a-96ae6d977837.png)

**Comment by interactivellama** [comment]
@obalbinat Please explore poly-filling full SVG support within you application with SVG for Everybody per guidance found here. https://github.com/salesforce/design-system-react/blob/master/docs/browser-compatibility.md#internet-explorer-11-support

This library doesn’t directly support IE11, but is open to changes needed in order for you to support IE11.

**Comment by interactivellama** [comment]
Fixes #2149.

@obalbinat Please open a new issue for the missing icons you’d like to.
