### ISSUE TITLE
Remove Extra " From All Welcome Mats

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#2171]
Remove the " after the word "processes"

![image](https://user-images.githubusercontent.com/42620858/61235436-8931e600-a703-11e9-9704-a0a0bbe7092f.png)

Applies to all Welcome Mats.

**Comment by interactivellama** [comment]
@ashwaniYDV Could you fix this typo?

**Comment by ashwaniYDV** [comment]
@interactivellama Yes sure.

**Comment by interactivellama** [comment]
Oh sorry. I meant to message Aswin Shenoy. Thank you for picking it up though.
