### ISSUE TITLE
Add Missing Class to Info Only Welcome Mat to Decrease Title Text Size

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#2177]
The title text for the **DSR Info Only Welcome Mat** should be 32px to align with SLDS (https://www.lightningdesignsystem.com/components/welcome-mat/#Info-only).

Adding **slds-welcome-mat_info-only** to `<div class="slds-welcome-mat">` will make the title text 32px instead of 42px.

![image](https://user-images.githubusercontent.com/42620858/61307041-97433d80-a7bb-11e9-853a-a08a17554b6c.png)

**Comment by interactivellama** [comment]
@kwilloughby-sf has red-lined/design audited the Welcome Mat. @aswinshenoy Please add this class based on the `info-only` variant.

**Comment by aswinshenoy** [comment]
Sure :) I will send PR by tonight.
