### ISSUE TITLE
Update All Welcome Mats to Use Same Icons as SLDS

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#2178]
Please use the same icons as SLDS (https://www.lightningdesignsystem.com/components/welcome-mat/#About-Welcome-Mat) for all the DSR Welcome Mat examples.

We don't want to encourage using the same icon twice. Number 3 & 4 below need to be updated.

From top to bottom the icons should be in this order:
1. animal_and_nature
2. call
3. upload
4. magicwand
5. knowledge_base

**Comment by interactivellama** [comment]
@aswinshenoy Please update the icons when convenient.

@kevinparkerson and I missed this is in the pull request review. @kwilloughby-sf red-lined/design audited the Welcome Mat. Thanks @kwilloughby-sf

**Comment by aswinshenoy** [comment]
@kwilloughby-sf sorry about that one, I should have been a bit more careful. I will send a PR by tonight to patch up :) Thank you so much, I will make sure I don't repeat those :/

**Comment by kwilloughby-sf** [comment]
No worries @aswinshenoy. Thank you for updating the icons!
