### ISSUE TITLE
Incomplete IconSettings context is passed to Portals

### ISSUE THREAD

**Issue by minevskiy** [salesforce/design-system-react#2182]
Only `iconPath` is passed to Portals. 
The remaining props of `IconSettings` are not passed down:  onRequestIconPath, actionSprite, customSprite, doctypeSprite, standardSprite, utilitySprite.

https://github.com/salesforce/design-system-react/blob/master/components/utilities/dialog/index.jsx#L530-L532

**Comment by interactivellama** [comment]
Related to #1752
