### ISSUE TITLE
Files: File not found for CSS file

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#2186]
http://design-system-react-components.herokuapp.com/?selectedKind=SLDSFiles&selectedStory=Loading&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

http://design-system-react-components.herokuapp.com/assets/styles/override.css

![Screen Shot 2019-07-18 at 4 40 53 PM](https://user-images.githubusercontent.com/1290832/61496870-d1a70900-a97a-11e9-96d9-a5997c0c741c.png)

**Comment by keshavg2** [comment]
Hi @interactivellama I want to work upon this issue.
