### ISSUE TITLE
Progress Ring: Completed ring has a gray border on IE11

### ISSUE THREAD

**Issue by obalbinat** [salesforce/design-system-react#2197]
When the progress ring is completed, its progress will be displayed grey instead of its specific color.
Example on IE11:
<img width="178" alt="Screen Shot 2019-07-25 at 4 52 19 PM" src="https://user-images.githubusercontent.com/51956523/61880384-7a1a1780-aefd-11e9-8fca-0506354a01ae.png">

Expected result:
![Screen Shot 2019-07-25 at 5 02 22 PM](https://user-images.githubusercontent.com/51956523/61880692-0593a880-aefe-11e9-9816-2aaa827d01cd.png)

**Comment by interactivellama** [comment]
@obalbinat Does the same issue occur on the SLDS site in IE11? https://www.lightningdesignsystem.com/components/progress-ring/

If it doesn't, I can ask them about how they are fixing it.

**Comment by obalbinat** [comment]
@interactivellama Yes, this issue is reproducing in Lighting Design System too.
