### ISSUE TITLE
Docked Composer: Add component

### ISSUE THREAD

**Issue by pulkonet** [salesforce/design-system-react#2199]
Component Spec: https://lightningdesignsystem.com/components/docked-composer/

**Comment by interactivellama** [comment]
@garygong Are you all using the SLDS Docked Composer or are you all needing a generic "docked assistant"/"docked utility modal"

I have a team interested in a generic lower right of the screen, minimize-able modal, but the content is not anything like the Docked Composer and I wanted to check to see if we wanted to "gut the contents" and just use an `onRender` prop in the examples for the composer aspect of it.

@pulkonet What do you think?

**Comment by interactivellama** [comment]
In the concrete, this would be something like renaming to `DockedPopover` and `composer` could be a variant if needed. I haven't got that far into the details.

**Comment by garygong** [comment]
Yes, I agree.  After looking at the [spec](https://lightningdesignsystem.com/components/docked-composer/) again, it looks like the component is already described in terms of a shell, with the consumer providing the contents.

**Comment by pulkonet** [comment]
@interactivellama I was following the specs from SLDS and found it to be a shell just as Gary mentioned above. I have raised a draft PR and I am adding the props proposal in a while.
