### ISSUE TITLE
Setup Assistant: Add Standard/Custom Icon Support via onRenderProgress

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#2201]
Add the ability to use a Standard/Custom SLDS Icon instead of the Progress Ring to all variants of the DSR Setup Assistant. Either all icons or all Progress Rings must be used (no mixing/matching).

- Place the icon in the same location as the Progress Ring in the markup
- If appropriate, use the same markup as icons in Cards:
`<div class="slds-media__figure"><span class="slds-icon_container slds-icon-standard-user" title="user"><svg class="slds-icon slds-icon_small" aria-hidden="true"><use xlink:href="/assets/icons/standard-sprite/svg/symbols.svg#user"></use></svg><span class="slds-assistive-text">user</span></span></div>`
- Add **position: relative; top: 1px;** to the `<span>` containing the SVG (without this the icon won't be vertically positioned properly...these two items are applied to the Progress Ring currently)
- Add **top-margin: 4px;** to the `<span>` containing the SVG (use the **_$spacing-xx-small_** Design Token)

Final output should look like this...
![example](https://user-images.githubusercontent.com/42620858/62140601-481c0300-b2b9-11e9-848b-9ca5634cff82.png)

I will provide info on which icons to use for the subsequent icons (4) on 7/30 or 7/31.

**Comment by kwilloughby-sf** [comment]
@kevinparkerson, here is the issue we discussed yesterday. I will let you know which icons to use for the other 4 items either today or tomorrow but this should at least get you started.

**Comment by interactivellama** [comment]
@kwilloughby-sf When do you want this by?

**Comment by interactivellama** [comment]
When we move forward with this, I would recommend something like:

`onRenderProgress` and if want to check the render prop's child's `displayName` for all `SLDSProgressRing` or `SLDSIcon` in a checkProp we could do that there.

@kevinparkerson What do you think of that approach?

**Comment by kevinparkerson** [comment]
@interactivellama I was planning to just add an `icon` prop since according to the design you can't combine `SLDSProgressRing` with the `SLDSIcon`. `onRenderProgress` could be more future-proof but also might complicate and confuse the purpose of the current `progress` prop:
```
{this.props.progress !== undefined ? (
	<div className="slds-media__figure">
		<ProgressRing
			hasIcon
			icon={
				this.props.progress === 100 ? null : this.props.stepNumber
			}
			flowDirection="fill"
			size="large"
			theme={progressRingTheme}
			value={this.props.progress}
		/>
	</div>
) : null}
```

**Comment by interactivellama** [comment]
I think it would be good to provide a way to allow the consumer to control and pass in their own `ProgressIndicator`. I remember discussing that possibility a few months ago with the original component creation.

**Comment by kevinparkerson** [comment]
@interactivellama just to be clear, you meant `ProgressRing` correct? `ProgressIndicator` is also involved with Setup Assistant but is currently provided and controlled by the developer:

<img width="509" alt="Screen Shot 2019-08-02 at 10 23 27 AM" src="https://user-images.githubusercontent.com/991513/62380829-b2c67c00-b50f-11e9-898d-dcbb0ad03220.png">

**Comment by interactivellama** [comment]
Maybe `<Step onRenderFigure />` (figure from Media Object's figure) would be a better name since the icon isn't really about "progress."

**Comment by interactivellama** [comment]
Oh, I think we can keep `progress` and just pass it in to the onRender callback as parameter. That way both props can be used at the same time.

**Comment by kevinparkerson** [comment]
@interactivellama I agree, `onRenderFigure` sounds better for the purpose. I'll progress back as a parameter too though they should already have it on their end...

**Comment by kevinparkerson** [comment]
@kwilloughby-sf those style values seem to only apply if the step is expandable. Additionally, the non-expandable version seems to need a negative top setting to be centered vertically correctly. I'm going to alter those a bit and try and make it look as close to the image you've provided as possible

**Comment by kwilloughby-sf** [comment]
@kevinparkerson, that's odd. I applied the same specs above to the "With Step Progress" variant and it centered properly

**Comment by kwilloughby-sf** [comment]
Also, sorry for not getting you the other icons yet. Been really busy but I will try to do that soon.

**Comment by kevinparkerson** [comment]
@kwilloughby-sf no worries! Yeah I'm not sure about the styles either, but hopefully what I've put together works across browsers / systems
