### ISSUE TITLE
IE11: clicking on Lookup menu scrollbar dismisses the menu.

### ISSUE THREAD

**Issue by minevskiy** [salesforce/design-system-react#222]
To repro in demo app:
1. In IE11, open Lookup page in demo app
2. Open the menu of the second lookup ("Account")
3. Click on menu scrollbar to scroll down
4. Observe that menu is dismissed.

The same issue used to also happen in Chrome and Firefox, but was fixed.

![image](https://cloud.githubusercontent.com/assets/14121307/13718496/6268d3ca-e79f-11e5-8de8-b91306830f49.png)

**Comment by interactivellama** [comment]
Closing all Lookup and Picklist issues. Please re-create for combobox if issue still exists.

**Comment by interactivellama** [comment]
Maybe some area detection on mouse down would fix this if there are still issues. https://stackoverflow.com/posts/33799265/revisions
