### ISSUE TITLE
DataTable: Update indeterminate checkbox click order

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#2224]
Update the indeterminate checkbox click order pattern so that clicking an indeterminate checkbox de-selected all checkboxes in the checkbox grouping.

**Comment by apshada** [comment]
@interactivellama any  pattern update for this issue?

**Comment by interactivellama** [comment]
We are keeping this as is due to https://github.com/salesforce/design-system-react/issues/2228
