### ISSUE TITLE
Add Map Component

### ISSUE THREAD

**Issue by aswinshenoy** [salesforce/design-system-react#2229]
Implement Map component as in SLDS - https://www.lightningdesignsystem.com/components/map/

**Comment by interactivellama** [comment]
From https://design-system-react-co-pr-2230.herokuapp.com/?path=/story/sldsmap--inside-modal-w-multiple-locations

![Screen Shot 2019-08-14 at 10 38 31 PM](https://user-images.githubusercontent.com/1290832/63073063-43279800-bee4-11e9-939b-985584bd3ace.png)
![Screen Shot 2019-08-14 at 10 38 25 PM](https://user-images.githubusercontent.com/1290832/63073064-43279800-bee4-11e9-8572-d42ab6b2971d.png)
![Screen Shot 2019-08-14 at 10 38 12 PM](https://user-images.githubusercontent.com/1290832/63073106-6e11ec00-bee4-11e9-90b4-85f47f664b25.png)
