### ISSUE TITLE
Add Summary Detail Component

### ISSUE THREAD

**Issue by aswinshenoy** [salesforce/design-system-react#2231]
Implement Summary Detail Component as in SLDS - https://www.lightningdesignsystem.com/components/summary-detail/

**Comment by interactivellama** [comment]
![Screen Shot 2019-08-14 at 11 13 12 PM](https://user-images.githubusercontent.com/1290832/63074144-29d51a80-bee9-11e9-8940-e1463863ac22.png)

**Comment by jgerigmeyer** [comment]
Right now the `Accordion` component requires `summary`, which makes it difficult to have complex titles that ideally would be outside the click target (that is, outside the accordion button). I can workaround it by using `summary=""` and `panelContentActions={myComplexTitleComponent}`... but it seems like this new Summary Detail Component would be The Right Way -- correct?

**Comment by interactivellama** [comment]
@jgerigmeyer Yes, I think so. @aswinshenoy is no longer a GSoC intern, so I do not have an ETA on this component.

**Comment by aswinshenoy** [comment]
I will try to work on the changes requested, and possibly get this one done within few days. Really sorry for being away.
