### ISSUE TITLE
Add SLDS Checkbox Button

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#2241]
Please add the SLDS Checkbox Button component. See https://www.lightningdesignsystem.com/components/checkbox-button

Stephanie B. is requesting this for the January 2020 release.

**Comment by kwilloughby-sf** [comment]
@interactivellama & @kevinparkerson. Stephanie requested this today. I am trying to get an exact date for when it would need to be in DSR and which dev team will be leveraging it.

**Comment by kwilloughby-sf** [comment]
The Setup team will be leveraging this.

**Comment by interactivellama** [comment]
Setup Team does not need this anymore.
