### ISSUE TITLE
Radio: Enter key does not select on doc site

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#2275]
This appears to be an issue with a single radio since RadioGroup appears to work with the Enter key https://react.lightningdesignsystem.com/components/radio-groups/

**Comment by abhisheknaiidu** [comment]
@interactivellama  want to work on this. But could you plz explain it in much more concise way ?

**Comment by interactivellama** [comment]
Hi @abhisheknaiidu. This shouldn't be considered a bug, since radios should not be used outside a group. I'm going to close this issue.
