### ISSUE TITLE
Datepicker: Unable to enter date manually 

### ISSUE THREAD

**Issue by selenka** [salesforce/design-system-react#2285]
When I click on Date input, I'm not able to enter date manually. Datepicker opens and forces me to select date. 

It reproduces on this example https://react.lightningdesignsystem.com/components/date-pickers/

**Comment by apshada** [comment]
i would like to work on this!

**Comment by interactivellama** [comment]
@apshada Great! Here is the user story.

User should be able to type a date when mouse clicking into input without calendar grabbing focus.

### Pattern update:
- [ ] `.focus` of calendar should not occur on focus of `input`
- [ ] Calendar should open on click of input, but NOT open when tabbing into input
- [ ] Typing in input should close calendar
- [ ] `onBlur` of input and input's Calendar icon should close calendar (I think Combobox has re-use).
- [ ] onClick/enter on the input's calendar icon should open and `.focus()` on calendar (currently doing this)
- [ ] Calendar date selection should close calendar (currently doing this)

You can see this pattern here under Date Input:
https://developer.salesforce.com/docs/component-library/bundle/lightning-input/example

Adding @jcjuett for verification of the accessibility of the pattern proposal.

**Comment by apshada** [comment]
if date picker takes text input then it willl solve this bug
![Screenshot from 2019-09-18 19-28-33 (1)](https://user-images.githubusercontent.com/49001649/65156263-6649e800-da4c-11e9-85d2-d5febbb5575d.png)

**Comment by apshada** [comment]
@jcjuett please verify the pull request for proposal

**Comment by interactivellama** [comment]
@apshada Your PR is missing that the calendar should still open on click, but not grab focus. Please review the pattern update bullet points.

**Comment by BenjaminWFox** [comment]
@interactivellama I added a commit to address this since the previous PR was closed. Please let me know if it needs any revisions.

**Comment by brahimkraiem** [comment]
Hello, anyone has resolved this feature ?
