### ISSUE TITLE
Salesforce Density (Comfy/Compact)

### ISSUE THREAD

**Issue by nlem** [salesforce/design-system-react#2288]
Apologies if this is documented somewhere obvious, but I cannot work out how to select comfy or compact display densities.
My react app always displays similar to the "comfy" layout.

The functionality is described in the link below, but is barely mentioned in the lightning design system docs.
https://developer.salesforce.com/blogs/2018/08/new-density-settings-for-the-lightning-experience-ui-in-winter-19.html

Thanks

**Comment by interactivellama** [comment]
Modifying density is not on our roadmap at this time. The current maintainers' analysis is that density is a primarily a concern of "DataTable heavy layouts" and the primary products we align with do not create as many of these types of layouts and the designers aligned with those products did not seem interested in adding this feature.

As far as architecture goes, I would recommend doing it with a `DensitySettings` component that uses context similar to how `IconSettings` works.
