### ISSUE TITLE
No Margin Between Buttons in docs

### ISSUE THREAD

**Issue by ashu8912** [salesforce/design-system-react#2338]
![Screenshot 2019-09-30 at 3 29 06 PM](https://user-images.githubusercontent.com/30126128/65869188-9328c400-e397-11e9-939e-a02124ca57de.png)
A Little margin from right and left would look good

**Comment by interactivellama** [comment]
Sounds good. Go ahead and add margins in the button examples. The examples are in this folder https://github.com/salesforce/design-system-react/blob/master/components/button/__examples__/brand-disabled-destructive-inverse.jsx#L1

**Comment by ashu8912** [comment]
ok sending in a pr for this

**Comment by amreshk005** [comment]
@ashu8912 are you working on this? if not can I Work on it?
