### ISSUE TITLE
Use Husky and lint staged to lint every commit

### ISSUE THREAD

**Issue by aloksingh3112** [salesforce/design-system-react#2353]
The lint-staged is in the dependencies but is not being used.
I think we should add husky to lint all the commits automatically

**Comment by interactivellama** [comment]
@kevinparkerson What do you think? I prefer auto-lint commits, but I don't do many commits to save temporarily.

**Comment by interactivellama** [comment]
@aloksingh3112 Please proceed.

Here is how the codebase was previously with commit linting. It just used `precomit-hook` module, but husky looks like it's more frequently updated now.
https://github.com/interactivellama/design-system-react-OLD/blob/16e56fadb40281ebb825929960bf71ccb521bdd8/package.json

**Comment by aloksingh3112** [comment]
![image](https://user-images.githubusercontent.com/27079355/66501995-18238400-eae2-11e9-8dad-8db7a9be56a4.png)
whenever I run lint: fix script in husky I run into this error.

**Comment by interactivellama** [comment]
Can you set it up to just lint the git staged files?

The other option is to update `tile.jsx`. The solution is move `generateId` to the the constructor.

Here is the same code in Accordion. https://github.com/salesforce/design-system-react/blob/master/components/accordion/index.jsx#L52 and here is older PR addressing the same issues. See https://github.com/salesforce/design-system-react/pull/2245/files

**Comment by aloksingh3112** [comment]
I am getting this error on every  component except accordion
![image](https://user-images.githubusercontent.com/27079355/66505329-c8948680-eae8-11e9-84c4-ec1bfd73fc6c.png)

**Comment by interactivellama** [comment]
If this is a blocker, please fix them or update the code to `UNSAFE_componentWillMount()` and create a new issue and title it "Remove use of UNSAFE_componentWillMount".

**Comment by garygong** [comment]
I see the message `Husky requires Node 10` too.  I'll update the project o use Node 10, and then come back to merge this PR.  Thanks!
