### ISSUE TITLE
Combobox Dialog Not Working & Wrong Color Triangle

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#2354]
I'm unable to check any of the checkboxes and the triangle is too light (looks disabled).

http://design-system-react-components.herokuapp.com/?path=/story/sldscombobox--dialog

**Comment by nik72619c** [comment]
i'd like to work on this one

**Comment by interactivellama** [comment]
@nik72619c Sounds good. Looks like an issue with `options` being `undefined`. Once `optionsSearchEntity` and `optionsAddItem` got added. Probably just needs to be guarded from being `undefined`.

**Comment by nik72619c** [comment]
I opened the app at localhost:9001, but I didnt find dialog mentioned in the list, under SLDScombobox

**Comment by interactivellama** [comment]
![Screen Shot 2019-10-04 at 2 26 43 PM](https://user-images.githubusercontent.com/1290832/66237687-f5910580-e6b2-11e9-8c50-41ee279fb2c1.png)

**Comment by nik72619c** [comment]
Had an outdated fork, thanks !

**Comment by nik72619c** [comment]
#2357 @interactivellama @kwilloughby-sf
