### ISSUE TITLE
Support highlighting Combobox Metatext based on input value

### ISSUE THREAD

**Issue by kwilloughby-sf** [salesforce/design-system-react#2356]
Support searching the metatext (i.e. second line) if supplied. Matching characters should be bolded just like the primary text. To see an example create a new "Task" in Sales and search the "Name" field.

**Comment by interactivellama** [comment]
This should be called `highlightSubTitle` this is the meta text of the entity typically. I'm unsure of use of "highlight" though.

**Comment by interactivellama** [comment]
@kwilloughby-sf Did this feature get removed from the design?

**Comment by kwilloughby-sf** [comment]
@interactivellama, Meko's team decided not to use the Combobox in their design so this isn't urgent.
