### ISSUE TITLE
Getting checked items list in a multi-select checkbox dropdown

### ISSUE THREAD

**Issue by pianeer** [salesforce/design-system-react#2378]
I'm trying to use the [DSR Dropdown Menu](https://react.lightningdesignsystem.com/components/menu-dropdowns/) and have some code like this
```html
<SLDSMenuDropdown
  onSelect={this._onSelected}
  options={this.getOptions(this.state.xyz)}
  checkmark
  multiple
  value={this.state.currValue}
  width="x-small"
  className="builder-dropdown"
>
    <SLDSDropdownTrigger>
       <SLDSButton .../>
   </SLDSDropdownTrigger>
</SLDSMenuDropdown>
```

So the `checkbox` and `multiselect` props do work as intended. However I'm not sure how I should go about obtaining the final state of the dropdown in terms of all items that were checked. The `onSelect` callback seems to only gives me the current item that was checked/unchecked. The docs also didn't seem to specify how to go about obtaining the checked values list. Any pointers would be highly appreciated?

Thanks!

**Comment by interactivellama** [comment]
I think it's a bug. https://github.com/salesforce/design-system-react/blob/master/components/menu-dropdown/menu-dropdown.jsx#L732

It look internal state is updated, but that the `onSelect` still needs to pass out an array and the prop description should be updated to tell folks what they are getting in their callback paremeters https://github.com/salesforce/design-system-react/blob/master/components/menu-dropdown/menu-dropdown.jsx#L316

Could you work on this bug?

**Comment by pianeer** [comment]
Sounds good @interactivellama. Will try sending out a PR early next week!
