### ISSUE TITLE
Tooltip text is not correctly populated for page header detail blocks

### ISSUE THREAD

**Issue by ocrownffdc** [salesforce/design-system-react#2392]
This issue can be replicated using the code for the page header on the lightning design system for react [pages](https://react.lightningdesignsystem.com/components/page-headers/).

The issue is replicated by the first PageHeader in the list, whereby the tooltip on the first item displays with the text "Tooltip" rather than as anything useful.

It looks like the intention is that this tooltip should display the full text of the truncated content, so in the example code 'Description that demonstrates truncation with content. Description that demonstrates truncation with content.'
It doesn't do this, because of a bug with the detail-block component's implementation of the tooltip. The content props from the details block is passed into the Tooltip component on line 88 of [detail-block.jsx](https://github.com/salesforce/design-system-react/blob/master/components/page-header/private/detail-block.jsx) as the props "title", however looking at the implementation of the tooltip component the props title is never used, instead the content should be passed in as the props content, so line 88 would become `<Tooltip align="top" content={content} triggerStyle={{ display: 'inline' }}>`.

The workaround to avoid this is to simply wrap the strings that are being passed into the detail blocks in another .jsx element (e.g. a div), which prevents the detail block form working out whether it's content is being truncated as it can no longer simply work out its length, and hence stops the tooltip being displayed at all.

I'm not actively working on this issue, although it should be a fairly quick fix as described above.

A cut down version of the code to replicate this issue is as follows:

```
import React from 'react';

import PageHeader from '@salesforce/design-system-react/components/page-header';

class Example extends React.Component {
	static displayName = 'RecordHomePageHeaderExample';

	render() {
		const details = [
			{
				label: 'Field 1',
				content:
					'Description that demonstrates truncation with content. Description that demonstrates truncation with content.',
				truncate: true,
			},
		];

		return (
			<PageHeader
					details={details}
					variant="record-home"
				/>
		);
	}
}

ReactDOM.render(<Example />, mountNode);
```

**Comment by siddharth30jan** [comment]
Are you working on this issue? Else I would like to work on this one.
