### ISSUE TITLE
Alternative to prototype component console warnings?

### ISSUE THREAD

**Issue by jimmydief** [salesforce/design-system-react#2395]
We often find ourselves making use of components while they are still in prototype mode. We also enforce a lack of console errors and warnings in our tests to prevent unexpected regressions that don't cause a test to actually fail.

The current strategy of always logging a console warning when a prototype component is used feels very heavy-weight and results in engineers needing to explicitly whitelist these warnings in tests that make use of a prototype component. A couple other solutions seem reasonable:

1. Warn in the appropriate documentation, not in the code.
2. Change the exported variable names of prototype components to be `unstable_SLDSPrototypeComponent` instead of `SLDSPrototypeComponent`. This will make it obvious that there is some risk to developers while avoiding workarounds in tests.

I'm not currently working on this.

**Comment by interactivellama** [comment]
@jimmydief Thank you for the feedback. This should fix your problem. https://github.com/salesforce/design-system-react/pull/2373

This went out in https://github.com/salesforce/design-system-react/releases/tag/v0.10.13

Please follow up if you have additional issues once you are on 0.10.13.
