### ISSUE TITLE
Incorrect changelog note in v0.10.16

### ISSUE THREAD

**Issue by BenjaminWFox** [salesforce/design-system-react#2419]
Excited to see that the Datepicker changes have been released! 

I'm not sure if a) this is a big deal, or b) if this is an auto-generated thing that can be changed, but  it may confuse anyone looking through the notes. The [change-log note](https://github.com/salesforce/design-system-react/releases/tag/v0.10.16) regarding the datepicker update is incorrect, referring to my original implementation idea which was tossed out [after feedback](https://github.com/salesforce/design-system-react/pull/2391#issuecomment-554604200) from @interactivellama. Rather than adding a prop, the default behavior of the component was changed to allow manual input.

Instead of:

`Datepicker: Add canInputMaintainFocus prop`

It is now something like:

`Datepicker: Default behavior updated to allow manual input`

**Comment by interactivellama** [comment]
Thank you!
