### ISSUE TITLE
Lightning Design System react website custom theming. 

### ISSUE THREAD

**Issue by kamalkantappirio** [salesforce/design-system-react#2421]
I follow the article for an integrated lightning Design System in the react app and i am successfully able to do this in my project.

But I want to apply my custom theme(color, fonts, images) in my react project but I am not able to find any approach/document using the lightning Design System.

Could you please let me know if is there any way or documents available for this.

**Comment by interactivellama** [comment]
I think the best approach would be to build the SLDS CSS from the sass files and fork the sass files and design tokens.

**Comment by kamalkantappirio** [comment]
@interactivellama I couldn't find any documentation for use of design tokens in react.

**Comment by interactivellama** [comment]
There isn't. You'd want to build a custom version of SLDS--probably in SASS.
