### ISSUE TITLE
Tooltip's are coinciding

### ISSUE THREAD

**Issue by abhisheknaiidu** [salesforce/design-system-react#2436]
When scrolling down, tooltip's are coinciding under SLDSMenuDropdown prop.

![sales](https://user-images.githubusercontent.com/55599878/72065332-fd8cc100-3303-11ea-9619-f92bc8f0066b.png)

**Comment by sehgalvibhor** [comment]
Also, in general, Tooltips are overlapping.

**Comment by interactivellama** [comment]
@sehgalvibhor That screen is for dev purposes. The UX pattern at Salesforce is that only one tooltip should be visible at a time.

**Comment by sehgalvibhor** [comment]
@interactivellama : Got it, thanks!

**Comment by abhisheknaiidu** [comment]
@interactivellama  Just like the second tooptip changes its direction, when scrolling down.. the first tooltip also should change its direction in order to avoid overlapping.
