### ISSUE TITLE
DataTable: Allow Checkbox column customization

### ISSUE THREAD

**Issue by kuhmuh** [salesforce/design-system-react#2444]
It would be nice if the DataTable provides the same means of customization as other components in design system react project for the checkbox column.
Unfortunately the checkbox column has hard-coded width and other styles, especially if you have a DataTable with a few columns and fixed headers the checkbox column is much wider than needed.
Is it possible to add some means of customizations to the checkbox column?

**Comment by interactivellama** [comment]
The DataTable should map to UX patterns found here https://www.lightningdesignsystem.com/components/data-tables/

**Comment by kuhmuh** [comment]
This maybe true for non fixed header tables in vanilla HTML/CSS. But my problem is the react component  `DataTable`. Columns are styled directly and given as children to the HOC `DataTable`. But in case of the checkbox column the client has no means to change it. In opposite to the most other react components of your design system, there are no "extension points" for this column.
