### ISSUE TITLE
AccordionPanel crashes when no `refs` prop

### ISSUE THREAD

**Issue by burtek** [salesforce/design-system-react#2450]
If `<AccordionPanel>` gets no `refs` prop, it throws 

```
Uncaught TypeError: Cannot read property 'summaryButton' of undefined
    at SLDSAccordionPanel
```

due to this line:
https://github.com/salesforce/design-system-react/blob/a4092d9013792edea5b64e079fa99c177972ff02/components/accordion/panel.jsx#L83

According to [docs](https://react.lightningdesignsystem.com/components/accordions/#sub-components), `refs` is not required though.

Workaround: add `refs={{}}` to props, but it's pretty irritating.

**Comment by sumukhah** [comment]
working on the issue,
thank you

**Comment by sumukhah** [comment]
this issue will not occur if you have used `<AcordianPanel />` as a child of `<Acordion />`
But it would be nice to fix this  So that one can use AcordianPanel without Acordion.

**Comment by burtek** [comment]
@sumukhah I used `<AccordionPanel />` as child of `<Accordion />` and it crashed.

**Comment by burtek** [comment]
ping (un-stale)
