### ISSUE TITLE
Tooltip/Popover: Arrow does not adjust for element scrolling

### ISSUE THREAD

**Issue by TheHans255** [salesforce/design-system-react#2473]
Our project is using the `<Tooltip />` component to wrap large components (such as DataTableCells), and one issue that happens is that if the component is scrolled far enough to the right, the tooltip arrow appears to be pointing to the element to the left.

![Screenshot from 2020-02-21 17-03-21](https://user-images.githubusercontent.com/15896573/75083223-774fc700-54cc-11ea-9e73-bc5841a11cd8.png)

I believe that Tooltip needs to be using the `arrow` modifier on the Popper.js component to fix this.

**Comment by TheHans255** [comment]
I created a branch to work on this issue: https://github.com/TheHans255/design-system-react/tree/popover-arrow.

However, I've run into a problem: it does not appear as if a custom placeable nubbin exists within the Lightning Design System. Instead, we have twelve classnames that each place a nubbin in a canned position on the tree as a `::before` pseudo-element. It appears then that having the arrow be custom placeable is out of scope for this project. Is this correct?

**Comment by TheHans255** [comment]
Actually, looking at this again, I can see that `hasAnchoredNubbin` on the Tooltip component does create a distinct nubbin element. We could probably get this smart nubbin positioning by moving the `hasAnchoredNubbin` implementation into Dialog and allowing Popper.js to position it.

**Comment by TheHans255** [comment]
Due to outside circumstances, I will not be able to finish working on this feature. I did some investigation (with work in progress on this branch) and found that repositioning the nubbin created by `hasAnchoredNubbin` will actually be far harder than I imagined it being, since the way Popper.js manipulates the CSS properties of the arrow does not properly reflect how the tooltip and nubbin elements are laid out in the HTML. Our project will likely be resolving the issue we're facing some other way.

**Comment by interactivellama** [comment]
Would there be a way to not allow `hasAnchoredNubbin` in this instance?

**Comment by TheHans255** [comment]
Actually, `hasAnchoredNubbin` is the only situation in which you could have this positioning feature, because the nubbins created by the styles are locked to one of the twelve fixed locations and cannot adjust to a position between them.
