### ISSUE TITLE
Expose rows and cols for TextArea

### ISSUE THREAD

**Issue by leifg** [salesforce/design-system-react#2486]
It would be great to get access to at least the `rows` attribute of the underlying `textarea` input. It would be quite helpful when populating text to have the whole text visible.

```
const value = "Very Long Text that spans multiple paragraphs"
<Textarea value={value} rows={calculateRows(value)} >
```

**Comment by dcefram** [comment]
Or an alternative is to simply expose a `style` property similar to the `Input` component (https://react.lightningdesignsystem.com/components/inputs/#prop-styleInput). That way, we can set the width/height of the textarea based on some calculations done in JS.

I could write down a PR for this if this makes sense?
