### ISSUE TITLE
Add ability to specify a custom class for a DataTable row

### ISSUE THREAD

**Issue by garygong** [salesforce/design-system-react#2491]
I'd like to add the ability add a custom class for DataTable rows.

One possible API that I can think of is to add `className` to each `items` entry.  For example:
```
items: [
  {
    id: '896a6a60',
    accountName: 'Acme',
    classNameRow: 'row1'
  },
  {
    id: '44da9dcd',
    accountName: 'Acme',
    classNameRow: 'row2'
  },
  {
    id: 'f988a721',
    accountName: 'salesforce.com',
    classNameRow: 'row2'
  }
]
```
Would result in:
```
<tbody>
  <tr class="row1">...</tr>
  <tr class="row2">...</tr>
  <tr class="row3">...</tr>
</tbody>
```
What do you think?

**Comment by interactivellama** [comment]
`className` seems straightforward to me. I'd recommend something like `classNameRow` in order to be more explicit and allow other classNames in the future.

**Comment by garygong** [comment]
> `className` seems straightforward to me. I'd recommend something like `classNameRow` in order to be more explicit and allow other classNames in the future.

Edited the example above based on this suggestion.
