### ISSUE TITLE
JavaScript URLs in Tab component don't play nicely with strict CSP

### ISSUE THREAD

**Issue by jimmydief** [salesforce/design-system-react#2493]
The tab component uses an `<a>` element to wrap the tab contents but prevents default navigation behavior through the use of `href="javascript:void(0);"`. This doesn't play nicely with CSP policies without the `unsafe-inline` directive which prevent the script from executing but also add a warning in the console.

https://github.com/salesforce/design-system-react/blob/ecb085436ad81b2f04ad54efc7ab4f47c1b4c0c1/components/tabs/private/tab.jsx#L148

The [SLDS blueprints for the tab component](https://www.lightningdesignsystem.com/components/tabs/) seem to suggest the Javascript URL approach as well so I'm not sure whether this issue really belongs there.

A potential solution would be to prevent the default behavior of click/keydown events where they're handled within the parent tabs component.

https://github.com/salesforce/design-system-react/blob/ecb085436ad81b2f04ad54efc7ab4f47c1b4c0c1/components/tabs/index.jsx#L252-L298

Happy to contribute if there's an agreeable fix.

It looks like there are some [more examples of this](https://github.com/salesforce/design-system-react/search?q=eslint-disable-line+no-script-url&unscoped_q=eslint-disable-line+no-script-url). #2463 seems likely related.

**Comment by garygong** [comment]
I wonder if we can just use a `<button>` instead of `<a>`, or maybe a `<span>` with a `tabIndex`.

**Comment by dcefram** [comment]
To add to this issue, latest versions of React is now throwing a warning due to the use of `javascript:void(0)`. Actual warning:

> console.error node_modules/react-dom/cjs/react-dom.development.js:88
> 
> Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:void(0);".

I also agree with using a button instead of an anchor tag, [as is recommended here](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md#case-i-understand-the-previous-cases-but-still-need-an-element-resembling-a-link-that-is-purely-clickable).

**Comment by jimmydief** [comment]
@garygong Can you reopen this one? I'd like to revive #2514.

**Comment by interactivellama** [comment]
@jimmydief I'm cool with not following the SLDS blueprint/HTML strictly. LWC components do not.

**Comment by jimmydief** [comment]
@interactivellama Mind taking a look at #2514? This seems like it would address this issue and unblock upgrading to React 16.9.0 and above for those who dislike deprecation warnings. There are some places where `<a>` => `<button>` makes a lot of sense (e.g. the tab component mentioned in this issue which is unlikely to navigate to another page) but others where the correct tag is more contextual (e.g. options in a combobox menu, some of which may navigate elsewhere while others autocomplete). Seems like it might be easier to address those on a case-by-case basis.

**Comment by jimmydief** [comment]
Fixed by #2829.
