### ISSUE TITLE
Support issue tag on stackoverflow

### ISSUE THREAD

**Issue by gburnett** [salesforce/design-system-react#2519]
I've read a [suggestion](https://github.com/salesforce/design-system-react/blob/master/docs/SUPPORT.md) that any support requests should be made on stackoverflow.

Sadly that `design-system-react` tag does not appear to exist yet.

![Screenshot 2020-05-21 at 11 40 56](https://user-images.githubusercontent.com/1595464/82551529-44af7c00-9b58-11ea-9fda-e17190ea8190.png)

My reputation is far too low to create this tag. 😢   Can anybody help?

**Comment by pogilvie** [comment]
I'm in the same boat.

**Comment by gburnett** [comment]
Over 7 days have passed.

**Comment by gburnett** [comment]
It would be helpful if anybody could create this tag.  I noticed that a `react` tag exists and perhaps this is an alternative.
