### ISSUE TITLE
Fixed Columns Headings + Infinite Scroll/Lazy Load on Data-Tables

### ISSUE THREAD

**Issue by TheJaredWilcurt** [salesforce/design-system-react#255]
My team is in the planning stages for creating a new All Audiences/Audience Lists page using SLDS for React (Boiler Plate).

Here's a screenshot from the (not yet finished) designs:

![Audience Lists](https://cloud.githubusercontent.com/assets/4629794/14753118/308b8d3e-08a1-11e6-90a4-8f6208c2b004.png)

I was told by Vineeth Nair, who is working on these designs, that pagination is meant to be controlled via infinite scroll. He said that it is meant to extend the height of the page and not be contained in a scrollable div (with overflow).

When we start in on coding this project, we'd like to avoid creating the infinite scrolling custom for our app as it seems like a feature that other teams will need in the component as well.

Can we get something like the following as options in data-tables:

| NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION |
| :-- | :-- | :-- | :-- | :-- |
| infiniteScroll | bool | false | false | Enables lazy loading of content when the last row is visible |
| height | number | string | false | 'auto' | This will limit the height of your table and force a scrollbar to appear for the table contents. Accepts a number greater than 0 or the string 'auto'. |
| pageSize | number | false | 25 | If infinite scroll is on this will be the limit on amount of rows to add at a time |
| pageOffset | number | false |  |  |

**Comment by interactivellama** [comment]
Closing and combining with #676
