### ISSUE TITLE
NodeJS dependencies break the build

### ISSUE THREAD

**Issue by volkanunsal** [salesforce/design-system-react#2595]
This library is breaking my build because it looks like it has indirect dependencies on the Node.js libraries `crypto` and `cluster` at runtime. The `crypto` library is a direct dependency of `nanoid@2.1.11`, which is a direct dependency of `shortid@2.2.15`.

```
shortid -> nanoid -> crypto
shortid --> cluster
```

<img width="823" alt="Screen Shot 2020-08-25 at 5 19 49 PM" src="https://user-images.githubusercontent.com/151600/91229543-0b0e8400-e6f8-11ea-82a8-d2d41a7b06f9.png">

I'd appreciate any advice of how to get around these dependency issues.

**Comment by volkanunsal** [comment]
I think this library needs to vendor `shortid` and run the grunt task of the project, which generates [a file output for the browser](https://github.com/dylang/shortid/blob/master/Gruntfile.js#L11). Then you can update package.json's `main` property to point to the browserified entrypoint.

**Comment by garygong** [comment]
Thanks for opening the issue, will look into this!

**Comment by davidlygagnon** [comment]
I'm going to take a look at this - @volkanunsal Can you give me a bit more info on how to repro? You mention it breaks the build. What's the error message you get? Which environment are you on? Thanks!

**Comment by volkanunsal** [comment]
I’m using rollup with a few basic plugins, e.g commonjs, node-resolve. I can paste it here tomorrow morning.

**Comment by volkanunsal** [comment]
[Here is the link to repo.](https://github.com/volkanunsal/dashboard/tree/shortid-issue) 

After you clone it, you need to run:

```
yarn install
yarn run dev
open http://localhost:10001/
```

If you look back to the console, you should see these error messages:

<img width="716" alt="Screen Shot 2020-08-27 at 8 08 49 AM" src="https://user-images.githubusercontent.com/151600/91440416-8f6a1f80-e83c-11ea-80ea-bd45280d0089.png">

**Comment by volkanunsal** [comment]
The more I dig into this issue, the more I see that the problem is not in this package, but in Rollup's node module resolution algorithm, which is not able to handle external modules specified in the `browser` mappings of the package definition file. 

[Here is an issue on that.](https://github.com/rollup/plugins/issues/472)

**Comment by davidlygagnon** [comment]
Awesome. Thanks!
