### ISSUE TITLE
Support infinite scrolling with fixed column headers

### ISSUE THREAD

**Issue by Prophetess** [salesforce/design-system-react#2642]
DataTable should support infinite scrolling with fixed column headers.

My proposal is to follow similarly to how [lightning:datatable](https://developer.salesforce.com/docs/component-library/bundle/lightning:datatable/example) implemented infinite scrolling.

Provide these new props:
Property | Type | Description
-------- | ---- | -----------
hasMore | boolean | Specifies whether there's more data to be loaded and displays a spinner at the bottom of the table if so. The default is false.
onLoadMore | function | The action triggered when infinite loading loads more data.
loadMoreOffset | number | Determines when to trigger infinite loading based on how many pixels the table's scroll position is from the bottom of the table. The default is 20.

This solution will not do any window rendering but will allow the consumer to add additional rows to the items array.

**Comment by lkretzschmar** [comment]
This would be awesome, I just came here to request this as well. What is the process for these requests, does someone respond to these or put them on a roadmap? Tag them?

**Comment by garygong** [comment]
The proposal looks good to me!
