### ISSUE TITLE
Unable to render SVG icon within Datepicker in any browser

### ISSUE THREAD

**Issue by tniggel** [salesforce/design-system-react#2644]
I am working in the Quip platform (which runs on React), using the SLDS-React Datepicker component within a SLDS-React DataTableCell but have been unable to render any of the SLDS icons (.SVG files) within the Datepicker. It seems the following code snippet (which is generated from SLDS, and should be rendering the right arrow used to navigate between months) is restricting the SVG icon from displaying at all. 

I have included the assets in my build at the specified path and can open & view the asset in another tab using the same path included below. I was at first trying to request these icons from where they are stored within Quip, but encountered CORS issues and decided to upload the files along with my Live App code instead.

This code is just an example of icon usage, but this occurs in multiple places.

`
<button class="slds-button slds-button_icon-container" type="button">
        <svg aria-hidden="true" class="slds-button__icon">
                <use href="dist/assets/right.svg">
                </use>
        </svg>
        <span class="slds-assistive-text">Next month</span>
</button>
`

This is how I am instantiating the Datepicker component:

`
return (
        <IconSettings onRequestIconPath={({category, name}) => `dist/assets/${name}.svg`}>
                <DatePicker
                 align='right'
                 labels={{}}
                 onChange={(event, data) => {
                 this.state.editMode = false;
                 this.passUpdate(this.state.property, this.state.rowId, this.state.children);
                                }}
                 formatter={(date) => {
                          let newDate = date ? moment(date).format('YYYY-MM-DD') : '';
                          this.state.children = newDate;
                          return newDate;
                 }}
                 menuPosition='overflowBoundaryElement'
                 parser={(dateString) => {
                         return moment(dateString, 'MM-DD-YYYY').toDate();
                 }}
                 value={this.state.children}
                 />
        </IconSettings>
)
`

I have not added any styling to the components. I have also seen that editing the Button HTML inline from the browser and replacing the <svg component with an <img component, passing in the path to the icon as the src parameter, works perfectly.

I have tried everything I can think of to load these icons, including using the Sprite svg instead and adding styling to try and force the icon to show, but nothing works. Adding an <img tag directly on the front-end seems to be the only way these images will render within this App.

Since I cannot modify the SLDS code myself to change these tags and replace the <svg with an <img, how can I get my icons to render within the Datepicker component? 

Browser version: Chrome 83.0.4103.61 (but this also fails in Firefox & Safari)
React version: 16.13.1
SLDS-React version: 0.10.19

**Comment by garygong** [comment]
Your usage of `IconSettings` looks ok to me.  Have you verified that the path `dist/assets/${name}.svg` points to a file that exists?

**Comment by tniggel** [comment]
Thanks for taking a look - yes, all the .svg files that this component would reference are accessible in the App build, and are viewable from the DOM.

**Comment by garygong** [comment]
Can you share a sample project where you see this happening?

**Comment by tniggel** [comment]
Unfortunately I can't, as the codebase is proprietary for my client and I am restricted in what I can share. Understand that leaves us with little troubleshooting options - I can share at least that both the icon and the DatePicker were imported directly from SLDS in the versions stated above. The best way to replicate would likely be within the Quip platform, if at all possible.

**Comment by garygong** [comment]
Maybe you can create a standalone project that isolates the problem while excluding any proprietary code?

**Comment by tniggel** [comment]
Good point - I should be able to do this within a test Quip site that I could share publicly. I will work on that and get back to you

**Comment by interactivellama** [comment]
Please update if this is still an issue.
