### ISSUE TITLE
Using <DataTable /> with props "stacked" or "stackedHorizontal" is broken

### ISSUE THREAD

**Issue by jcro21** [salesforce/design-system-react#2688]
I've submitted a PR with the changes here https://github.com/salesforce/design-system-react/pull/2685

This issue was submitted by another user a while ago (with pictures and more description of the problem) https://github.com/salesforce/design-system-react/issues/1580 but as it's closed I thought I'd submit another.

### Problem
As the issue above mentions, the `stacked` and `stackedHorizontal` properties of `DataTableCell` aren't fulfilling the SLDS components spec, causing the component to display no column/field names/labels at all and so be unusable for its intended purpose and environment.

### Cause
The reason this occurs is that the SLDS css utilises the `data-label` attribute on `(<td> | <th>)` to display column labels, and here in design-system-react it's not being output by `DataTableCell`.

### Fix
[PR here](https://github.com/salesforce/design-system-react/pull/2685) The fix is a simple 2 line addition to `components/data-table/cell.jsx` ([these two](https://github.com/jcro21/design-system-react/commit/c34b6760d502fe6b0914c97c2281d2371fd2e73e)) to add the `data-label` attribute to cells so the SLDS css has access to the column label values and can display the column label next to the cell data value on small viewports as expected.

**Comment by garygong** [comment]
Fixed in https://github.com/salesforce/design-system-react/pull/2685
