### ISSUE TITLE
Auto-align the selected item on the view when the combo-box is opened

### ISSUE THREAD

**Issue by chaitanyakaul** [salesforce/design-system-react#2745]
When the combo-box is opened the item that's already selected doesn't get scrolled into view which means the user has to scroll down to get to the selected item. 
This is especially a problem for components like [year-picker](https://react.lightningdesignsystem.com/components/date-pickers/)(which uses the Read-only Combobox) in which the year range might start from 1900 making the user scroll a lot to get to the required selection.

Ideal behavior->

![image](https://user-images.githubusercontent.com/1298398/105553557-74e88500-5cba-11eb-84ba-1b45df1bb0dc.png)

Ideally, item that's already selected should be on the bottom of the list when the box is opened.

**Comment by interactivellama** [comment]
I think something like this in `handleOpen` will work. It probably needs some QA and maybe limited to only single select readonly variant?

```
    const index = findIndex(this.getOptions(), (item) =>
    isEqual(item, this.props.selection[0])
    );

    menuItemSelectScroll({
      container: this.menuRef,
      focusedIndex: index,
    });
```

**Comment by chaitanyakaul** [comment]
Yeah. I was thinking more of the same. And yes, it should be restricted to the `readonly` variant.
