### ISSUE TITLE
Warning: Legacy context API in React 17

### ISSUE THREAD

**Issue by jwhaley5** [salesforce/design-system-react#2800]
I got this warning about using a Legacy Context API. This could be an error with my Component structure, but I have gotten this warning using SLDS React components in many places. I'm curious if this is due to something I am doing or if this version of design-system-react was meant strictly for use with React 16.

Here is one of the warning messages the app gives:

Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: SLDSIconSettings, SLDSMenuDropdown

**Comment by garygong** [comment]
Thanks for opening an issue.  I'll be working on updating the project to use React 17 so that this warning won't be a problem anymore. (https://github.com/salesforce/design-system-react/issues/2818)
