### ISSUE TITLE
Update project to use React 17

### ISSUE THREAD

**Issue by garygong** [salesforce/design-system-react#2818]
We need to make sure that we:
- Avoid using legacy context API
- Avoid using `javascript:` links
- Replace deprecated lifecycle methods

**Comment by Azmarie** [comment]
While in React strict mode, I discovered [this warning ](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage)for using `findDOMNode`. There're over 10 references of this in DSR 😔

<img width="1670" alt="Screen Shot 2021-04-12 at 11 14 43 AM" src="https://user-images.githubusercontent.com/29130256/114441468-4aeb8400-9b80-11eb-8e14-cdecc7a46822.png">
