### ISSUE TITLE
Filter Component: Correct Delete Icon for remove filter action?

### ISSUE THREAD

**Issue by danigonlinea** [salesforce/design-system-react#2819]
As described in the docs, this is the [Filter Component ](https://react.lightningdesignsystem.com/components/filters/#examples)
![image](https://user-images.githubusercontent.com/1208620/113399406-78764780-93a0-11eb-8e3b-dc5384a8280f.png)

I realized that the icon for removing the filter from filter panel is not the same as it is on the filter panel for Listviews which is displayed as a cross icon:

![image](https://user-images.githubusercontent.com/1208620/113399699-ec185480-93a0-11eb-99c4-63506efdfcb7.png)

I'm wondering what the correct icon could be. Thanks.

**Comment by interactivellama** [comment]
UI patterns map in this library map to SLDS blueprints and not to existing products. See https://www.lightningdesignsystem.com/components/expression/#With-an-Expression-Group-2
