### ISSUE TITLE
Documentation site issues with latest version of library

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#2882]
Issues include:
* Style/font updates (removal of Salesforce Sans from Design System) 
* Alert examples do not render
* Icons missing from Dropdown menu (`iconCategory` is marked as required in `SLDSButton`, but its value is `undefined`)

This does not appear to be an issue with the library in production, since examples work in [Storybook deployment](http://design-system-react-components.herokuapp.com/?path=/story/sldsmenudropdown--base-with-icon-dropdown-right-aligned) but appear to be an issue with usages of stories within CodeMirror examples on website.

See [staging site](https://design-system-react-staging.herokuapp.com/)

**Comment by garygong** [comment]
There's still an issue with the Custom Trigger example for `Dropdown`.

**Comment by interactivellama** [comment]
Confirmed that is is a site only issue.
