### ISSUE TITLE
StackOverflow tag unavailable

### ISSUE THREAD

**Issue by lampsbr** [salesforce/design-system-react#2883]
Hello! 

The stackoverflow tag recommended for support doesn't exist yet. =(
Also it can't be created if you don't have 1500 reputation in stackoverflow, so I couldn't create a ticket with the correct tag.

Since I'm already here annoying you guys, this is the support ticket that I created: https://stackoverflow.com/questions/67637501/how-to-show-boolean-based-values-in-datatable-cell-content-using-lightning-des

I don't know how to correctly customize the cells of my Datatable, and I don't know how to ask for help. Do you guys have some chat support in irc, discord, telegram, gitter etc? 

Thanks =]

**Comment by interactivellama** [comment]
Appears to be answered here. Feel free to re-open if not: https://stackoverflow.com/a/67638432
