### ISSUE TITLE
[TypeScript] BuilderHeaderUtilities export is missing

### ISSUE THREAD

**Issue by ghingis** [salesforce/design-system-react#2890]
Hey!

BuilderHeaderUtilities and SLDSBuilderHeaderUtilities is missing from the exports (`lib/components/index.d.ts`) and the `lib/components/builder-header/utilities.d.ts` is missing bot in 0.10.33 and 0.10.34 release.

Could you fix this and make a new release?

**Comment by interactivellama** [comment]
@garygong SLDSBuilderHeaderUtilities is missing.
