### ISSUE TITLE
ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by soql101** [salesforce/design-system-react#2900]
code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@">=16.3" from @salesforce/design-system-react@0.10.35
npm ERR!   node_modules/@salesforce/design-system-react
npm ERR!     @salesforce/design-system-react@"*" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@">=16.3" from @salesforce/design-system-react@0.10.35
npm ERR!     node_modules/@salesforce/design-system-react
npm ERR!       @salesforce/design-system-react@"*" from the root project
npm ERR!   1 more (react-contenteditable)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-highlighter@0.4.3
npm ERR! node_modules/@salesforce/design-system-react/node_modules/react-highlighter
npm ERR!   react-highlighter@"^0.4.3" from @salesforce/design-system-react@0.10.35
npm ERR!   node_modules/@salesforce/design-system-react
npm ERR!     @salesforce/design-system-react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by goody** [comment]
@soql101 how did you resolve this?  Running into the same issue since the recent update.
