### ISSUE TITLE
Not able to set maxLength and rows property in the Textarea component

### ISSUE THREAD

**Issue by anujsingla** [salesforce/design-system-react#2917]
We are accepting the maxLength property in the Textarea component but we are setting it in the wrong way in HTML textarea.
https://github.com/salesforce/design-system-react/blob/master/components/textarea/index.jsx#L304
It should be like "maxlength={maxLength}" and the value should be number not string.

We are not accepting rows property for the textarea so we should accept this value from the parent component.

**Comment by interactivellama** [comment]
That property seems to working at https://react.lightningdesignsystem.com/components/textareas/

<img width="832" alt="Screen Shot 2021-07-12 at 3 41 42 PM" src="https://user-images.githubusercontent.com/1290832/125359550-abc55c80-e327-11eb-9980-50f08888a2a3.png">
