### ISSUE TITLE
Vertical Navigation: Missing icon and notification

### ISSUE THREAD

**Issue by gnzzz** [salesforce/design-system-react#2934]
Currently the Vertical Navigation is missing
- [Items with icons](https://www.lightningdesignsystem.com/components/vertical-navigation/#Items-with-Icons)
- [Items with notifications](https://www.lightningdesignsystem.com/components/vertical-navigation/#Items-with-Notifications)

from the SLDS design.

I'm proposing adding two optional fields, [similar to how Badge is done](https://react.lightningdesignsystem.com/components/badges/), in the Item object to define an Icon and a Badge for notifications. For example:

```
[
  {
    id: 'store',
    label: 'Store',
    items: [
      {
        id: 'credit_store',
        label: 'credit',
        url: 'store/credit',
        icon: <Icon category="utility" name="moneybag" size="xx-small" />,
        notification: <Badge id="badge-base-example" content="423 Credits Available" />,
      },
      { id: 'transactions_store', label: 'Transactions', url: 'store/transactions' },
    ],
  }
];
```

**Comment by gnzzz** [comment]
I realised there is some inconsistency in the way that icons are done for other components when I started to implement this.

For badges the prop is a component:
```
<Badge
	id="badge-base-example-light"
	color="light"
	content="423 Credits Available"
	icon={<Icon category="utility" name="moneybag" size="xx-small" />}
/>
```
and for buttons it's passed as the props of the icon with `icon` as a prefix:
```
<Button
	assistiveText={{ icon: 'Icon Bare Small' }}
	iconCategory="utility"
	iconName="settings"
	iconSize="small"
	iconVariant="bare"
	onClick={() => {
		console.log('Icon Bare Clicked');
	}}
	variant="icon"
/>
```

@interactivellama which of these approaches is the current preferred way?

**Comment by interactivellama** [comment]
Good question! In short, the `Badge` way is preferred since it limits "duplicate" props. 

See https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#reuse-existing-component-props-by-using-component-no-button-iconclassname-

**Comment by interactivellama** [comment]
Also, thanks for wanting to contribute. I like the proposal. What do you think about `notificationBadge` instead of `notification` so that consumers already know what to pass in?

**Comment by gnzzz** [comment]
Thanks for the feedback. Yes, `notificationBadge` seems to make more sense to make it clear what it does.

**Comment by gnzzz** [comment]
I've opened an MR for this change. I struggled to get the typings correct and ended up using `any` which isn't ideal. If you have some suggestion to get that right then I'll change it.

**Comment by gnzzz** [comment]
@interactivellama is there any further changes needed on the PR?

**Comment by interactivellama** [comment]
@gnzzz Thanks for the ping! PR is merged now.
