### ISSUE TITLE
Can we get a new tagged release

### ISSUE THREAD

**Issue by beekermememe** [salesforce/design-system-react#2945]
Is it possible to get a release, the last one was July 21 and there are a few fixes I'd like to use that have been added since then (it is now August 2), thanks

**Comment by interactivellama** [comment]
@beekermememe Yes, we will get one out this week.

**Comment by beekermememe** [comment]
thanks!

**Comment by interactivellama** [comment]
These issues were blocking release on Friday. The new re-sizeable grids feature isn't compete with accessibility and some edge cases. I will try to get this out on Monday.

**Comment by interactivellama** [comment]
The new version is up. https://github.com/salesforce/design-system-react/releases/tag/v0.10.36
