### ISSUE TITLE
Modal not fading in properly

### ISSUE THREAD

**Issue by chriscorwin** [salesforce/design-system-react#296]
Not sure why, but modal the modal backdrop is popping into existence at full opacity.

A quick glance tells me the markup is... convoluted, and may not exactly match what is required, but I am not going to dig into it right this second, so capturing here.

[Screengrab of it in action](https://drive.google.com/a/salesforce.com/file/d/0BzNgjRM-0AcmYXhDRi12dkR4MmM/view). (Salesforce-only access, Google Drive link)

**Comment by bzenSFDC** [comment]
@interactivellama this issue is resolved as of 0.83, as there's a parent div rendering with class `slds-modal slds-fade-in-open` `slds-fade-in-open` is doing the correct fade-in.
