### ISSUE TITLE
Disabled option of the Dropdown component triggers the onSelect event

### ISSUE THREAD

**Issue by jnavaratnam** [salesforce/design-system-react#2987]
Steps to repro the problem:
1. Follow https://github.com/salesforce/design-system-react/blob/master/docs/create-react-app.md to create a test app
2. Copy the very first example in https://react.lightningdesignsystem.com/components/menu-dropdowns/ into the App.js as follows:
```
import './App.css';

import { Dropdown, IconSettings } from "@salesforce/design-system-react";

function App() {
  return (
    <div className="App">
      <IconSettings iconPath="/icons">
        <Dropdown
          assistiveText={{ icon: "More Options" }}
          iconCategory="utility"
          iconName="down"
          iconVariant="border-filled"
          onSelect={(value) => {
            console.log("selected: ", value);
          }}
          options={[
            { label: "Menu Item One", value: "A0" },
            { label: "Menu Item Two", value: "B0", disabled: true },
            { label: "Menu Item Three", value: "C0" },
            { type: "divider" },
            { label: "Menu Item Four", value: "D0" },
            { label: "Menu Item Five", value: "E0" },
            { label: "Menu Item Six", value: "F0" },
            { type: "divider" },
            { label: "Menu Item Seven", value: "G0" },
          ]}
        />
      </IconSettings>
    </div>
  );
}

export default App;
```
3. Now the app should render a dropdown with some options. Open the developer console and click each option and notice it logs the clicked option to console.
4. Notice the second option in the dropdown is a disabled option, but clicking on this also logs to the console, meaning a disabled item is triggering the click events which is not expected.

**Comment by ashutosh887** [comment]
I would like to work on this Issue
Please assign to me and guide me once

**Comment by Go1dExperience** [comment]
Hi, I don't think there is a "disabled" property mentioned anywhere: [options](https://react.lightningdesignsystem.com/components/menu-dropdowns/#prop-options).
The only disabled in menu-dropdown is to disable the dropdown itself, not individual item.
