### ISSUE TITLE
Combobox - Incorrect PropTypes type for 'disabled' prop in options array.

### ISSUE THREAD

**Issue by Streudal** [salesforce/design-system-react#2988]
I'm getting an error for the 'disabled' prop that is part of option object for the options prop on the Combobox component. Here is the error: 

![image](https://user-images.githubusercontent.com/35472790/147506036-59bf0232-adb2-4673-9652-295b4d1cf965.png)

and the current shape of the object for options in combobox.jsx: 
![image](https://user-images.githubusercontent.com/35472790/147506098-23d68430-fab6-434d-a900-763af36caa95.png)

I believe the fix is to just make the 'disabled' prop PropTypes.bool instead of PropTypes.boolean and all should be good to go. Just like this:
![image](https://user-images.githubusercontent.com/35472790/147506274-d44c7f70-6a0f-4b1c-839f-26f9674488c6.png)

I tested this by changing it from the node_modules directory and the error went away. Please let me know if I can be of any more assistance in this.

**Comment by Streudal** [comment]
Bumping thread to see if any movement has been made towards this issue.

**Comment by ashutosh887** [comment]
I would like to work on this Issue
Please assign to me and guide me once

**Comment by DevGautam2000** [comment]
Would like to work on this issue.
Please assign this to me.
