### ISSUE TITLE
Popover not trapping Escape key when rendered inside the Modal component

### ISSUE THREAD

**Issue by bxiao** [salesforce/design-system-react#3031]
When a Popover component is used inside a Modal component and if the popover is open, pressing the Escape key closes both the popover and the modal.

Expected behavior: Pressing Escape key when the popover is open should only close the popover. Modal should remain open.

**Comment by interactivellama** [comment]
This line may help also. In the Combobox PR fix, this is what stops the event from bubbling
https://github.com/salesforce/design-system-react/blob/master/utilities/key-callbacks.js#L16

```
if (stopPropagation) {
			EventUtil.trapEvent(event);
		}
```
So something like this should do it in 
https://github.com/salesforce/design-system-react/blob/master/utilities/keyboard-navigable-dialog.js#L46

```
case KEYS.ESCAPE:
	if (isOpen) {
		toggleOpen();
		EventUtil.trapEvent(event);
	}
break;
```
