### ISSUE TITLE
Page header doesn't display truncated text via Tooltip

### ISSUE THREAD

**Issue by shravansnyu** [salesforce/design-system-react#3090]
[UI] Truncated Text when mouse hovered over displays 'Tooltip' rather than the actual truncated text.
![image](https://user-images.githubusercontent.com/17942697/213306813-ff226ec5-ab40-4b80-8a9d-acd22a9c235f.png)

**Comment by chuyler** [comment]
Now there are two tooltips.  Two images below.  One shows current version in demo, the other shows release 0.10.52 on my own product.  It appears the content of the blue tooltip is fixed, but why are there two tooltips?

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/19213316/220821507-a8f7075c-4d49-402f-8e66-a0ecb05de8b0.png">


<img width="526" alt="image" src="https://user-images.githubusercontent.com/19213316/220821376-64531397-3e0a-490b-a23c-3219370cfb5d.png">

**Comment by interactivellama** [comment]
Is the gray one a built in browser `title`? Truncate CSS should have a `title`
