### ISSUE TITLE
The Pills Container component tries to access a property of undefined (runtime major crash)

### ISSUE THREAD

**Issue by VladimirParmonD** [salesforce/design-system-react#3138]
**Error summary**: the [Pills Component](https://react.lightningdesignsystem.com/components/pill-container/) causes a major crash / runtime error

**Where the error occurs**:
design-system-react\components\pill-container\private\selected-listbox.jsx
at **line 149**, function **getIcon**

**Error description**: The function getIcon (pic 1) seems to handle the icon display for the currently selected option. Option === current selection, which legitimately can be undefined according to the component props (pic 2). The code tries to access the property option.icon and this results in an error "Cannot access property icon of undefined"

**Proposed solution**: since both selection and icon are optional props (pic 2), either change the props typings OR use optional chaining (?.) operator in the code. From the looks of it, the latter is preferable since the code handles the possible undefined everywhere except this one place. Seems like just a simple oversight but causes a big trouble in the app
![image](https://github.com/salesforce/design-system-react/assets/124684344/5bd2ffba-9b13-4f4a-8de9-9df15989b8b4)
![image](https://github.com/salesforce/design-system-react/assets/124684344/c3590de9-51fa-4216-9fae-5773528f3249)

**Comment by shadwar123** [comment]
Hi, I'm new to open source I have applied the optional channing. Could you please assign it to me? It can be my first contribution.   Thanks!

![Screenshot 2024-08-26 164719](https://github.com/user-attachments/assets/bdd7a170-eff8-46d0-97dc-0966a10b5e7a)
@interactivellama
