### ISSUE TITLE
 JavaScript defaultProps in functional components with newer versions of React (18.3+)

### ISSUE THREAD

**Issue by VladimirParmonD** [salesforce/design-system-react#3142]
If possible, please update the components so they no longer use soon-to-be-removed default values in functional component props. This relatively small change will help to use the lib while leveraging latest React features. defaultProps can be easily replaced by default parameters.
Error is: 
"Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead."

**Comment by xulingzhihou** [comment]
yes I have been seeing this issue too. I will take up this issue and try to fix it
