### ISSUE TITLE
DataTable: Default text attribute when table is empty

### ISSUE THREAD

**Issue by dangolant-salesforce** [salesforce/design-system-react#365]
Our design spec requires us to have a message on the table body when there is no data in it.  A value that can be set on the DataTable component in DSR that creates a default text value for the table when it is empty would be very useful.

Spec is below:
![image](https://cloud.githubusercontent.com/assets/19716856/16459345/7b26a52a-3df0-11e6-99fa-c3c20073d8a4.png)

**Comment by interactivellama** [comment]
We an Illustration component now thanks to the awesome @qyiming ! Closing this issue.

For future reference, the UX pattern is: Remove the `<DataTable />` and replace the body of the `Card` or whatever the container is with an empty state `<Illustration />` component.

See https://react.lightningdesignsystem.com/components/illustrations/ and https://www.lightningdesignsystem.com/components/illustration/ for more info.
