### ISSUE TITLE
Add Flippable prop to all components using Dialog

### ISSUE THREAD

**Issue by donnieberg** [salesforce/design-system-react#372]
- When it's added, make sure to fix visual bug of when Component is inside Modal and the popover appears outside of it.
  <img width="700" alt="screen shot 2016-06-30 at 3 40 00 pm" src="https://cloud.githubusercontent.com/assets/3860705/16509458/d5d9d5bc-3ef1-11e6-8f40-92bbf9fa6483.png">

**Comment by interactivellama** [comment]
Flippable will be the default going forward with hasStaticAlignment being a prop with all Dialog using components
