### ISSUE TITLE
Page Header: Support inline edit

### ISSUE THREAD

**Issue by mbeard** [salesforce/design-system-react#374]
For the page header component, need to support optional inline editing of all fields.  Note: the save interaction for editing the name/title is slightly different than other fields.

**Name/Title**
- Default state of the field would be read only, with an edit icon next to it
- Clicking on the field, it becomes editable and the icon changes to undo
- Clicking anywhere outside of the field (or enter key) would save value and revert the field back to readonly
- Clicking the undo action would discard the value and revert the field back to readonly with the original value

**Other fields**
- Default state of the field would be read only, with an edit icon next to it
- Clicking on the field, it becomes editable
- The only way to exit the edit popover is to click "cancel/done"

https://salesforce.invisionapp.com/share/937T7ZPPF#/screens/170578741

**Comment by interactivellama** [comment]
Adding features are the responsibility of the consuming product team. Please follow up if any B2C UXE or SLDS decisions need to be made.
