### ISSUE TITLE
Add checkProps to GlobalNavigationBarLink and MenuDropdown to warn folks if they don't use the right event prop

### ISSUE THREAD

**Issue by kevinparkerson** [salesforce/design-system-react#475]
I noticed that GlobalNavigationBarRegion has inconsistent prop names for the "onSelect" event in it's sub-components. GlobalNavigationBarLink is "onClick," while GlobalNavigationBarDropdown is "onSelect." These should probably both be one or the other for consistency purposes.

for example, this:
https://github.com/salesforce-ux/design-system-react/blob/master/stories/global-navigation-bar/index.jsx#L49

compared to:
https://github.com/salesforce-ux/design-system-react/blob/master/stories/global-navigation-bar/index.jsx#L55

**Comment by interactivellama** [comment]
I'm going to call this read the documentation, unless someone wants to take it.
