### ISSUE TITLE
Replace Modal's default true prop: dismissable

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#503]
JSX props should not be true by default.

My suggestion is to deprecate `dismissable` and remove it from the propTypes and use the following.

```
/**
 * If true, Modals cannot be dismissed by clicking on the close icon or pressing esc key.
 */
disableClose: React.PropTypes.bool,
``
```

This should first be warned with a console error with dismissable is used.

This should not be a breaking change.

**Comment by aswinshenoy** [comment]
I wish to work on this, I believe I can do this in a day.
