### ISSUE TITLE
Right-Align Data-Table cells

### ISSUE THREAD

**Issue by jwilcurt-salesforce-com** [salesforce/design-system-react#585]
For numeric values in particular, our design calls for right-aligned text in specific columns.

Can this be added to the Data-Table, or if it already exists have the documentation updated to more clearly explain how to use it.
- https://jira.exacttarget.com:8443/browse/CONBLD-4789

**Comment by interactivellama** [comment]
Adding features are the responsibility of the consuming product team. Please follow up if any B2C UXE or SLDS decisions need to be made.
