### ISSUE TITLE
Global Navigation menu items should have the ability to roll up into "more" dropdown

### ISSUE THREAD

**Issue by swilliamset** [salesforce/design-system-react#594]
If global navigation is not wide enough to display all the secondary region items it currently cuts off or is overlapped by the tertiary region. The items should shift from the secondary region into a "more" dropdown at the end of the secondary region.

**active items will remain in the secondary region.**
# 

Pre SLDS design 
![pre slds preposed design](https://cloud.githubusercontent.com/assets/347227/17632769/21f2d418-6098-11e6-8fe1-086b5cb4a096.png)

at the moment this is a placeholder

no work needs to be done until SLDS provides html/css for the solution

**Comment by interactivellama** [comment]
Adding features are the responsibility of the consuming product team. Please follow up if any B2C UXE or SLDS decisions need to be made.
