### ISSUE TITLE
Add Optional Icon for Object Home & Related List Page Header

### ISSUE THREAD

**Issue by kwilloughby** [salesforce/design-system-react#612]
Currently, I believe only 2 of 4 React Page Headers support an icon to the left of the page title. Please add support for an optional icon for the other 2.

Below is an example from GUS. An icon is used consistently throughout Setup as well.

I already spoke with DBB and Jamin about this need. This is needed for 06.

![image](https://cloud.githubusercontent.com/assets/18220268/17826124/b1d8dd4a-663b-11e6-8f79-ce7bd7194c1b.png)

@jamin-hall @pixelprodotco

**Comment by interactivellama** [comment]
Adding features are the responsibility of the consuming product team. Please follow up if any B2C UXE or SLDS decisions need to be made.
