### ISSUE TITLE
Inline Edit Panel Component (MVP)

### ISSUE THREAD

**Issue by kwilloughby** [salesforce/design-system-react#621]
I’m working on a design that needs to leverage the inline edit panel (see my design). I found this pattern in SLDS, Org62, and GUS. SLDS already has a Panels component but it doesn’t work exactly the same as Org62 and GUS. In Org62 and GUS the “Cancel” and “Save” buttons are always visible and float above the content if the page is too long.

This is needed for 206 (aka 01).

My Design:
https://drive.google.com/a/salesforce.com/file/d/0B3O8X0GI27exR2J2UU1ZT05NLUU/view?usp=sharing

SLDS Panels Component:
https://latest-206.lightningdesignsystem.com/components/panels#flavor-detail-panel-form-edit-mode

Org62 Example:
Leads > Click on Name > Click on Details Tab

@jamin-hall @tweettypography

**Comment by interactivellama** [comment]
Adding features are the responsibility of the consuming product team. Please follow up if any B2C UXE or SLDS decisions need to be made.
