### ISSUE TITLE
Popover: Panel Variant

### ISSUE THREAD

**Issue by swilliamset** [salesforce/design-system-react#667]
https://latest-206.lightningdesignsystem.com/components/popovers/#flavor-panels

Upcoming need for mc lex (aka marketing cloud global nav lighting experience)

Timeline for usage in lex is next sprint (9/12-9/23).

Considering the dsr need lex can hold starting the work until the second half of the sprint (9/19).

**Comment by interactivellama** [comment]
Popover base variant is present now.

**Comment by interactivellama** [comment]
Adding features are the responsibility of the consuming product team. Please follow up if any B2C UXE or SLDS decisions need to be made.
