### ISSUE TITLE
Add Support for Data Table Scrolling

### ISSUE THREAD

**Issue by kwilloughby** [salesforce/design-system-react#676]
I'd like to add support for data table scrolling. Below is an example. In this example the table header remains visible at all times. The example also shows horizontal scrolling because the table is too wide.

![image](https://cloud.githubusercontent.com/assets/18220268/18531623/3a8bc364-7aa5-11e6-9b00-50650a31b4a9.png)

**Comment by interactivellama** [comment]
@kevinparkerson

I think the CSS if present for this in SLDS, but that it's just hidden on the SLDS site.

You can get inspiration from this component too https://developer.salesforce.com/docs/component-library/bundle/lightning:datatable/example

**Comment by interactivellama** [comment]
@kevinparkerson Here is Alex B's code from 2016 https://github.com/interactivellama/design-system-react/tree/bado22-datatable-fixed-header

**Comment by kevinparkerson** [comment]
@interactivellama here is all I was thinking:
```
/**
 * Set this to `true` for a data-table with fixed headers and scrolling columns / rows
 */
fixedHeader: PropTypes.bool,
/**
 * By default this function resizes the display headers when fixedHeader is `true`, but this behavior can be overridden
 */
onFixedHeaderResize: PropTypes.func,
/**
 * By default this function attaches/detaches listeners for window resize and tbody scrolling when fixedHeader is `true`, but this behavior can be overridden. Passes `true` or `false` depending on whether listeners should be attached or detached.
 */
onToggleFixedHeaderListeners: PropTypes.func,
```
