### ISSUE TITLE
Import SLDS designs tokens for use in library

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#684]
Currently, we have hexadecimals scattered around for style overrides and things that are outside SLDS (e.g.- menus that are not DOM descendants of their trigger but still need a hover effect on the trigger while the menu is open).

**Comment by futuremint** [comment]
The token sources are in the SLDS package: https://github.com/salesforce-ux/design-system/tree/v2.6.2/design-tokens

**Comment by interactivellama** [comment]
YAML! It'd be nice if they were JSON. If they were, we could import the JSON into the component that needed it.

**Comment by futuremint** [comment]
https://www.npmjs.com/package/yaml-to-json might work?
