### ISSUE TITLE
Prop width(value:0) will be treated as a Unitless number in future versions of React

### ISSUE THREAD

**Issue by scott-joe** [salesforce/design-system-react#714]
[This line](https://github.com/salesforce-ux/design-system-react/blob/master/components/notification/index.jsx#L205) of code in notifications is causing a warning in Chrome dev tools concerning how it's going to be handled in future versions of React.

```
Warning: a `div` tag (owner: `Notification`) was passed a numeric string value for CSS property `width` (value: `0`) which will be treated as a unitless number in a future version of React.
```

**Comment by interactivellama** [comment]
Notification is deprecated. Please use Alert and Toast. Closing.
