### ISSUE TITLE
Tooltip within modal

### ISSUE THREAD

**Issue by scott-joe** [salesforce/design-system-react#722]
Tooltip's visibility is not bound to parent containers such as a modal. Could hide tooltip as soon as text is no longer visible.

![2016-10-16 19 05 16](https://cloud.githubusercontent.com/assets/2026866/19421642/cf64bb34-93d3-11e6-9f1e-f83db02e302a.gif)

**Comment by interactivellama** [comment]
Should be fixed by PopperJS upgrade.
