### ISSUE TITLE
Toast: needs to be able to open more than one at a time.

### ISSUE THREAD

**Issue by chriscorwin** [salesforce/design-system-react#760]
# Multiple Toasts Problem

Okay, so, i’m thinking about the multiple toasts problem.

See #674 for more background.

And, it _is_ a problem, because we need to both be able to display _toasts_ in exactly, and only ever, one `.slds-notify-container`.... _unless_ the toast is a part of a modal, in which case it is theoretically possible that there is an open toast, in a container on the main part of the page, but _also_ a modal open that needs it’s own toast.

When a `Toast` is needing opened, discover if there is already an `.slds-notify-container` open that has an `.slds-notify—toast` in it, but that is _not_ a part of a `Modal`, and “simply” attach the new `Toast` to the existing container, rather than making a new one.

Of course, notifications can be self-dimissing, on a timer, and the timer for the previously-shown notification container still needs to run on it's own schedule, but _not_ kill off its container when it is time to close, or else the new one will dissapear also.

Additionally, I'm not sure, at all, how "hijacking" another `Notification`'s container can/should work in React.

Perhaps what is needed is some sort of _Notificaitons Manager™_ that can handle messages in and out of, rather than the `Notification` component itself handling its own hide/show and container placement.

---

Apparently you can only open 1 toast at a time, because _each_ toast provides its own `.slds-notify-container`, and just plops any additional ones right over the first one, rather than stacking them.

You can try it yourself by replacing the code in the toast example on the DSR site:

```
class NotificationExample extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            isOpen1: false,
            isOpen2: false
        }
    }

    toggleOpen(){
        this.setState({ isOpen1: !this.state.isOpen1, isOpen2: !this.state.isOpen2 });
    }

    render(){
        return (
            <div>
                <SLDSButton label="Open Toast" onClick={this.toggleOpen.bind(this)} variant="brand" />

                <SLDSNotification
                    content="There was a problem updating the record."
                    iconName="notification"
                    isOpen={this.state.isOpen1}
                    onDismiss={this.toggleOpen.bind(this)}
                    texture={true}
                    theme="error"
                    variant="toast"
                    />

                <SLDSNotification
                    content="There was a problem updating the record."
                    iconName="notification"
                    isOpen={this.state.isOpen2}
                    onDismiss={this.toggleOpen.bind(this)}
                    texture={true}
                    theme="error"
                    variant="toast"
                    />
            </div>
        );
    }

}

ReactDOM.render(<NotificationExample />, mountNode);
```

Pretty sure this isn’t what we want.

**Comment by interactivellama** [comment]
This is now doable due to the Toast refactor that made the container a different component.
