### ISSUE TITLE
Support dropdown on page header title

### ISSUE THREAD

**Issue by mbeard** [salesforce/design-system-react#791]
The page header title should support an optional element for switching views.  For example, in this [SLDS example](https://www.lightningdesignsystem.com/components/page-headers/#flavor-object-home) clicking on "My Leads" should display a dropdown with additional views to switch to.

See [example](https://gus.lightning.force.com/one/one.app#/sObject/CollaborationGroup/home?t=1481056935167) in GUS for this behavior as well.

**Comment by interactivellama** [comment]
Adding features are the responsibility of the consuming product team. Please follow up if any B2C UXE or SLDS decisions need to be made.
