### ISSUE TITLE
Sunset tooltip prop on dropdown component

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#813]
Dropdowns have a tooltip prop that get's passed down to `button`. It is currently broken.

**Comment by devgopesh** [comment]
@interactivellama Does adding tooltip should make a tooltip appear over a button. Tooltip prop is generally passed to button-trigger.jsx from menu-dropdown.jsx which I think is not needed as it is making a dropdown appear on a trigger. Can you clarify me on this?

**Comment by interactivellama** [comment]
@devgopesh Since, no is complaining about this prop being broken (in two plus years), I think the best path forward is just adding a checkProp sunset like this https://github.com/salesforce/design-system-react/blob/master/components/alert/check-props.js#L14

Let's cut our losses and move forward.
