### ISSUE TITLE
The required indicators (*) of Lookup and Input differ

### ISSUE THREAD

**Issue by minevskiy** [salesforce/design-system-react#866]
The required indicator of Input has a tooltip "required" (hard-coded to English) and a question-mark-styled mouse pointer.
![image](https://cloud.githubusercontent.com/assets/14121307/22672976/2450c94c-ec8c-11e6-9cca-953c2be7213c.png)

The required indicator of Lookup has neither of the above.

**Comment by interactivellama** [comment]
Closing all Lookup and Picklist issues. Please re-create for combobox if issue still exists.
