### ISSUE TITLE
Data Table - Add option for required single select

### ISSUE THREAD

**Issue by donnieberg** [salesforce/design-system-react#882]
Single select would behave like radio buttons where you can only select one row in the table. Multi-select is how it works now. This isn't a variant in SLDS but we need it on IoT. Maybe we keep the styling the same and just remove the top "select all" checkbox.

Added recently
https://lightningdesignsystem.com/components/data-tables/

**Comment by interactivellama** [comment]
@kevinparkerson What do you think about the following props proposal for this issue?

```
		/**
		 * `multiple` or `single` selection of rows. This used to be a boolean. `selectRows` without text will result in `multiple` row selection in order to be backward compatible.
		 */
		selectRows: PropTypes.oneOfType([
			PropTypes.bool,
			PropTypes.oneOf(['multiple', 'single']),
		]),
```
