### ISSUE TITLE
Add spinner to doc site

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#886]
@andyengle Asks where this was this morning.

To add to doc site update
https://github.com/salesforce-ux/design-system-react/blob/master/package.json#L167

and here
https://github.com/salesforce-ux/design-system-react/blob/master/examples/index.js

The spinner intro doc page comments need to be added here:
https://github.com/salesforce-ux/design-system-react/blob/master/components/spinner/index.jsx#L48

> Spinners are CSS loading indicators that should be shown when retrieving data or performing slow computations. In some cases, the first time a parent component loads, a stencil is preferred to indicate network activity.

See https://latest-208.lightningdesignsystem.com/components/spinners

See another published component for how to comment.

Here's how to test the site with your local copy of DSR. https://github.com/salesforce-ux/design-system-react/blob/master/CONTRIBUTING.md#releasing

**Comment by vernak2539** [comment]
Can this get added please? spent a good amount of time looking for it

**Comment by interactivellama** [comment]
Here is the current priority for me and @garygong and @davidlygagnon who are on a product team, but have graciously offered to contribute to DSR regularly. https://github.com/salesforce/design-system-react/milestone/20 It's about 20th from the top of the list (that is bottom).
