### ISSUE TITLE
Move Modal settings to Modal Settings Component 

### ISSUE THREAD

**Issue by aputinski** [salesforce/design-system-react#959]
Currently, to set the icons path, I need to do:

```js
import { setIconsPath } from `design-system-react/components/settings`
```

This has the side effect of requiring `react-modal`

https://github.com/salesforce-ux/design-system-react/blob/master/components/settings.js#L12

I'm importing only the components I need for my application, but `settings` are causing webpack bundle `react-modal` even though I'm not using it.

The proposed solution is to move these settings into the related component:

```js
import Icon from `design-system-react/components/icon`
Icon.setPath('/assets/icons')
```

This targets the 7.x branch.

**Comment by interactivellama** [comment]
Icon settings have been broken out of the global singleton, so I renamed/narrowed this issue to Modal settings.
