### ISSUE TITLE
Migrate to 'create-react-class'

### ISSUE THREAD

**Issue by danrigsby** [salesforce/design-system-react#983]
`React.createClass` is deprecated as of React 15.5: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html.

Ideally we would move to ES6 `class` syntax and pure render functions.  However, the quicker path to compliance for now is to refactor `React.createClass` to use `'create-react-class'` where applicable.

**Comment by interactivellama** [comment]
polyfill use of create-react-class has been implemented.
