### ISSUE TITLE
Picklist <input> needs aria-activedescendant

### ISSUE THREAD

**Issue by donnieberg** [salesforce/design-system-react#986]
The <input> needs to have an `aria-activedescendant={currentlyFocusedOption}` so that screen readers can tell users what option their "focus" is on. See SLDS Combobox's html:
https://latest-210.lightningdesignsystem.com/components/combobox/?state=open-item-focused&variant=base

**Comment by interactivellama** [comment]
Picklist is dead! Long live Combobox!
