### ISSUE TITLE
Inline edit - add truncation for static content that overflows

### ISSUE THREAD

**Issue by donnieberg** [salesforce/design-system-react#988]
Right now, if the text is too long, it gets cut off when the component is in "static" state. We need to make this so that the user can set the desired width on the static state text and also add ellipses when it goes over that width.

![image](https://cloud.githubusercontent.com/assets/3860705/26429485/efd3248a-409b-11e7-94a4-082223d84094.png)

**Comment by interactivellama** [comment]
Closing Inline Edit is deprecated in #1350. The UX pattern is to use a Popover paired with a edit icon OR swap a read only input with a base input componet.
